#!/usr/bin/env bash
# One-time (idempotent) setup of the Cloudflare tunnel for Vetchium staging.
#
# Creates a named tunnel, adds a DNS CNAME for every staging hostname inside the
# vetchium.com Cloudflare zone, and generates staging/cloudflared/config.yml with
# the tunnel UUID + credentials-file path. Safe to re-run.
#
# Prereq: vetchium.com is on Cloudflare nameservers (it is), and `cloudflared
# tunnel login` has been run at least once (this script triggers it if needed -
# it opens a browser to authorize the cert).
set -euo pipefail

TUNNEL="vetchium-staging"
# Single-level subdomains (<name>-staging.vetchium.com) so they are covered by
# Cloudflare's free Universal SSL (which only covers vetchium.com + *.vetchium.com,
# NOT *.staging.vetchium.com). Two-level wildcard TLS would need paid ACM.
DOMAIN="vetchium.com"
SUFFIX="staging"
HOSTS=(global in us de api hub org admin mail)
PORTS=(8091 8092 8093 8094 8092 8095 8096 8097 8025)

CFG_DIR="$(cd "$(dirname "$0")" && pwd)"

# 1. Authorize cloudflared against the zone (opens a browser the first time).
if [ ! -f "$HOME/.cloudflared/cert.pem" ]; then
  echo ">>> No cert.pem found - launching 'cloudflared tunnel login' (browser)..."
  cloudflared tunnel login
fi

# 2. Create the tunnel if it does not already exist.
if ! cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL"; then
  echo ">>> Creating tunnel $TUNNEL..."
  cloudflared tunnel create "$TUNNEL"
fi

UUID="$(cloudflared tunnel list | awk -v t="$TUNNEL" '$2==t {print $1}')"
CRED="$HOME/.cloudflared/$UUID.json"
echo ">>> Tunnel $TUNNEL = $UUID"
echo ">>> Credentials: $CRED"

# 3. DNS routes (CNAME <host> -> <uuid>.cfargotunnel.com) inside the zone.
for h in "${HOSTS[@]}"; do
  echo ">>> Routing $h-$SUFFIX.$DOMAIN..."
  cloudflared tunnel route dns "$TUNNEL" "$h-$SUFFIX.$DOMAIN" || true
done

# 4. Generate the real config.yml from the host/port map.
{
  echo "# Generated by setup-tunnel.sh - do not edit by hand."
  echo "tunnel: $UUID"
  echo "credentials-file: $CRED"
  echo "ingress:"
  for i in "${!HOSTS[@]}"; do
    printf '  - hostname: %s-%s.%s\n' "${HOSTS[$i]}" "$SUFFIX" "$DOMAIN"
    printf '    service: http://localhost:%s\n' "${PORTS[$i]}"
  done
  echo "  - service: http_status:404"
} >"$CFG_DIR/config.yml"

echo ">>> Wrote $CFG_DIR/config.yml"
echo ">>> Done. Start the tunnel with: staging/cloudflared/run.sh"
