// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_totp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminTOTPEnabled = `-- name: AdminTOTPEnabled :one
SELECT totp_enabled
FROM vetchium.admin_users
WHERE admin_user_id = $1
  AND admin_user_state = 'active'
`

func (q *Queries) AdminTOTPEnabled(ctx context.Context, adminUserID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, adminTOTPEnabled, adminUserID)
	var totp_enabled bool
	err := row.Scan(&totp_enabled)
	return totp_enabled, err
}

const completeAdminRecoveryCodeLogin = `-- name: CompleteAdminRecoveryCodeLogin :one
WITH consumed_code AS (
    UPDATE vetchium.admin_totp_recovery_codes AS r
    SET consumed_at = now()
    WHERE r.admin_user_id = $1
      AND r.code_hash = $2
      AND r.consumed_at IS NULL
    RETURNING r.admin_user_id, r.code_hash
), consumed_challenge AS (
    UPDATE vetchium.admin_login_challenges AS c
    SET consumed_at = now(),
        active = false
    FROM consumed_code AS code
    WHERE c.admin_login_challenge_id = $3
      AND c.admin_user_id = code.admin_user_id
      AND c.active
      AND c.consumed_at IS NULL
      AND c.expires_at > now()
    RETURNING c.admin_user_id
), updated_user AS (
    UPDATE vetchium.admin_users AS u
    SET last_login_at = now(),
        updated_at = now()
    FROM consumed_challenge AS challenge
    WHERE u.admin_user_id = challenge.admin_user_id
    RETURNING u.admin_user_id
), session AS (
    INSERT INTO vetchium.admin_sessions (
        session_token_hash,
        admin_user_id,
        expires_at,
        authenticated_at
    )
    SELECT
        $4,
        admin_user_id,
        $5,
        now()
    FROM updated_user
    RETURNING admin_session_id, created_at, expires_at, authenticated_at,
        admin_user_id
)
SELECT
    session.admin_session_id,
    session.created_at,
    session.expires_at,
    session.authenticated_at,
    count(c.code_hash) FILTER (
        WHERE c.consumed_at IS NULL
          AND c.code_hash <> (SELECT code_hash FROM consumed_code)
    )::bigint AS remaining_codes
FROM session
JOIN vetchium.admin_totp_recovery_codes AS c USING (admin_user_id)
GROUP BY session.admin_session_id, session.created_at, session.expires_at,
    session.authenticated_at
`

type CompleteAdminRecoveryCodeLoginParams struct {
	TargetAdminUserID     pgtype.UUID        `json:"target_admin_user_id"`
	RecoveryCodeHash      []byte             `json:"recovery_code_hash"`
	AdminLoginChallengeID pgtype.UUID        `json:"admin_login_challenge_id"`
	SessionTokenHash      []byte             `json:"session_token_hash"`
	SessionExpiresAt      pgtype.Timestamptz `json:"session_expires_at"`
}

type CompleteAdminRecoveryCodeLoginRow struct {
	AdminSessionID  pgtype.UUID        `json:"admin_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
	RemainingCodes  int64              `json:"remaining_codes"`
}

func (q *Queries) CompleteAdminRecoveryCodeLogin(ctx context.Context, arg CompleteAdminRecoveryCodeLoginParams) (CompleteAdminRecoveryCodeLoginRow, error) {
	row := q.db.QueryRow(ctx, completeAdminRecoveryCodeLogin,
		arg.TargetAdminUserID,
		arg.RecoveryCodeHash,
		arg.AdminLoginChallengeID,
		arg.SessionTokenHash,
		arg.SessionExpiresAt,
	)
	var i CompleteAdminRecoveryCodeLoginRow
	err := row.Scan(
		&i.AdminSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
		&i.RemainingCodes,
	)
	return i, err
}

const confirmAdminTOTPEnrollment = `-- name: ConfirmAdminTOTPEnrollment :one
WITH enrollment AS (
    SELECT e.admin_totp_enrollment_id, e.admin_user_id
    FROM vetchium.admin_totp_enrollments AS e
    WHERE e.admin_totp_enrollment_id = $1
      AND e.admin_user_id = $2
      AND e.active
      AND e.consumed_at IS NULL
      AND e.expires_at > now()
    FOR UPDATE
), updated AS (
    UPDATE vetchium.admin_users
    SET totp_secret_ciphertext = $3,
        totp_enabled = true,
        totp_last_timestep = $4,
        updated_at = now()
    WHERE admin_user_id IN (SELECT admin_user_id FROM enrollment)
      AND NOT totp_enabled
    RETURNING admin_user_id
), consumed AS (
    UPDATE vetchium.admin_totp_enrollments
    SET consumed_at = now(),
        active = false
    WHERE admin_totp_enrollment_id IN (
        SELECT admin_totp_enrollment_id FROM enrollment
    )
      AND EXISTS (SELECT 1 FROM updated)
    RETURNING admin_user_id
), deleted_codes AS (
    DELETE FROM vetchium.admin_totp_recovery_codes
    WHERE admin_user_id IN (SELECT admin_user_id FROM updated)
), inserted_codes AS (
    INSERT INTO vetchium.admin_totp_recovery_codes (
        admin_user_id,
        code_hash
    )
    SELECT u.admin_user_id, code_hash
    FROM updated AS u
    CROSS JOIN unnest($5::bytea[]) AS code_hash
    RETURNING admin_user_id
), sessions AS (
    DELETE FROM vetchium.admin_sessions
    WHERE admin_user_id IN (SELECT admin_user_id FROM updated)
      AND admin_session_id <> $6
), challenges AS (
    UPDATE vetchium.admin_login_challenges
    SET active = false
    WHERE admin_user_id IN (SELECT admin_user_id FROM updated)
      AND active
)
SELECT
    EXISTS (SELECT 1 FROM consumed) AND
    (SELECT count(*) FROM inserted_codes) = 10 AS confirmed
`

type ConfirmAdminTOTPEnrollmentParams struct {
	TargetEnrollmentID    pgtype.UUID `json:"target_enrollment_id"`
	TargetAdminUserID     pgtype.UUID `json:"target_admin_user_id"`
	SecretCiphertext      []byte      `json:"secret_ciphertext"`
	TotpTimestep          pgtype.Int8 `json:"totp_timestep"`
	RecoveryCodeHashes    [][]byte    `json:"recovery_code_hashes"`
	CurrentAdminSessionID pgtype.UUID `json:"current_admin_session_id"`
}

func (q *Queries) ConfirmAdminTOTPEnrollment(ctx context.Context, arg ConfirmAdminTOTPEnrollmentParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, confirmAdminTOTPEnrollment,
		arg.TargetEnrollmentID,
		arg.TargetAdminUserID,
		arg.SecretCiphertext,
		arg.TotpTimestep,
		arg.RecoveryCodeHashes,
		arg.CurrentAdminSessionID,
	)
	var confirmed pgtype.Bool
	err := row.Scan(&confirmed)
	return confirmed, err
}

const createAdminTOTPEnrollment = `-- name: CreateAdminTOTPEnrollment :one
WITH eligible_user AS (
    SELECT u.admin_user_id
    FROM vetchium.admin_users AS u
    WHERE u.admin_user_id = $1
      AND u.admin_user_state = 'active'
      AND NOT u.totp_enabled
), inserted AS (
    INSERT INTO vetchium.admin_totp_enrollments (
        admin_user_id,
        token_hash,
        secret_ciphertext,
        expires_at
    )
    SELECT
        admin_user_id,
        $2,
        $3,
        $4
    FROM eligible_user
    ON CONFLICT (admin_user_id) WHERE active DO UPDATE
    SET token_hash = EXCLUDED.token_hash,
        secret_ciphertext = EXCLUDED.secret_ciphertext,
        created_at = now(),
        expires_at = EXCLUDED.expires_at,
        consumed_at = NULL
    RETURNING admin_totp_enrollment_id, expires_at
)
SELECT admin_totp_enrollment_id, expires_at
FROM inserted
`

type CreateAdminTOTPEnrollmentParams struct {
	TargetAdminUserID pgtype.UUID        `json:"target_admin_user_id"`
	TokenHash         []byte             `json:"token_hash"`
	SecretCiphertext  []byte             `json:"secret_ciphertext"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

type CreateAdminTOTPEnrollmentRow struct {
	AdminTotpEnrollmentID pgtype.UUID        `json:"admin_totp_enrollment_id"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAdminTOTPEnrollment(ctx context.Context, arg CreateAdminTOTPEnrollmentParams) (CreateAdminTOTPEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, createAdminTOTPEnrollment,
		arg.TargetAdminUserID,
		arg.TokenHash,
		arg.SecretCiphertext,
		arg.ExpiresAt,
	)
	var i CreateAdminTOTPEnrollmentRow
	err := row.Scan(&i.AdminTotpEnrollmentID, &i.ExpiresAt)
	return i, err
}

const disableAdminTOTP = `-- name: DisableAdminTOTP :one
WITH updated AS (
    UPDATE vetchium.admin_users AS u
    SET totp_secret_ciphertext = NULL,
        totp_enabled = false,
        totp_last_timestep = NULL,
        updated_at = now()
    WHERE u.admin_user_id = $1
      AND u.admin_user_state = 'active'
    RETURNING u.admin_user_id
), codes AS (
    DELETE FROM vetchium.admin_totp_recovery_codes
    WHERE admin_user_id IN (SELECT admin_user_id FROM updated)
), enrollments AS (
    UPDATE vetchium.admin_totp_enrollments
    SET active = false
    WHERE admin_user_id IN (SELECT admin_user_id FROM updated)
      AND active
), challenges AS (
    UPDATE vetchium.admin_login_challenges
    SET active = false
    WHERE admin_user_id IN (SELECT admin_user_id FROM updated)
      AND active
), sessions AS (
    DELETE FROM vetchium.admin_sessions
    WHERE admin_user_id IN (SELECT admin_user_id FROM updated)
      AND admin_session_id <> $2
)
SELECT EXISTS (SELECT 1 FROM updated) AS disabled
`

type DisableAdminTOTPParams struct {
	TargetAdminUserID     pgtype.UUID `json:"target_admin_user_id"`
	CurrentAdminSessionID pgtype.UUID `json:"current_admin_session_id"`
}

func (q *Queries) DisableAdminTOTP(ctx context.Context, arg DisableAdminTOTPParams) (bool, error) {
	row := q.db.QueryRow(ctx, disableAdminTOTP, arg.TargetAdminUserID, arg.CurrentAdminSessionID)
	var disabled bool
	err := row.Scan(&disabled)
	return disabled, err
}

const getAdminTOTPEnrollment = `-- name: GetAdminTOTPEnrollment :one
SELECT
    e.admin_totp_enrollment_id,
    e.admin_user_id,
    e.secret_ciphertext
FROM vetchium.admin_totp_enrollments AS e
JOIN vetchium.admin_users AS u USING (admin_user_id)
WHERE e.token_hash = $1
  AND e.admin_user_id = $2
  AND e.active
  AND e.consumed_at IS NULL
  AND e.expires_at > now()
  AND u.admin_user_state = 'active'
  AND NOT u.totp_enabled
FOR UPDATE OF e
`

type GetAdminTOTPEnrollmentParams struct {
	TokenHash         []byte      `json:"token_hash"`
	TargetAdminUserID pgtype.UUID `json:"target_admin_user_id"`
}

type GetAdminTOTPEnrollmentRow struct {
	AdminTotpEnrollmentID pgtype.UUID `json:"admin_totp_enrollment_id"`
	AdminUserID           pgtype.UUID `json:"admin_user_id"`
	SecretCiphertext      []byte      `json:"secret_ciphertext"`
}

func (q *Queries) GetAdminTOTPEnrollment(ctx context.Context, arg GetAdminTOTPEnrollmentParams) (GetAdminTOTPEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getAdminTOTPEnrollment, arg.TokenHash, arg.TargetAdminUserID)
	var i GetAdminTOTPEnrollmentRow
	err := row.Scan(&i.AdminTotpEnrollmentID, &i.AdminUserID, &i.SecretCiphertext)
	return i, err
}

const regenerateAdminTOTPRecoveryCodes = `-- name: RegenerateAdminTOTPRecoveryCodes :one
WITH eligible_user AS (
    SELECT u.admin_user_id
    FROM vetchium.admin_users AS u
    WHERE u.admin_user_id = $1
      AND u.admin_user_state = 'active'
      AND u.totp_enabled
    FOR UPDATE
), deleted_codes AS (
    DELETE FROM vetchium.admin_totp_recovery_codes
    WHERE admin_user_id IN (SELECT admin_user_id FROM eligible_user)
), inserted_codes AS (
    INSERT INTO vetchium.admin_totp_recovery_codes (
        admin_user_id,
        code_hash
    )
    SELECT u.admin_user_id, code_hash
    FROM eligible_user AS u
    CROSS JOIN unnest($2::bytea[]) AS code_hash
    RETURNING admin_user_id
), sessions AS (
    DELETE FROM vetchium.admin_sessions
    WHERE admin_user_id IN (SELECT admin_user_id FROM eligible_user)
      AND admin_session_id <> $3
), challenges AS (
    UPDATE vetchium.admin_login_challenges
    SET active = false
    WHERE admin_user_id IN (SELECT admin_user_id FROM eligible_user)
      AND active
)
SELECT (SELECT count(*) FROM inserted_codes) = 10 AS regenerated
`

type RegenerateAdminTOTPRecoveryCodesParams struct {
	TargetAdminUserID     pgtype.UUID `json:"target_admin_user_id"`
	RecoveryCodeHashes    [][]byte    `json:"recovery_code_hashes"`
	CurrentAdminSessionID pgtype.UUID `json:"current_admin_session_id"`
}

func (q *Queries) RegenerateAdminTOTPRecoveryCodes(ctx context.Context, arg RegenerateAdminTOTPRecoveryCodesParams) (bool, error) {
	row := q.db.QueryRow(ctx, regenerateAdminTOTPRecoveryCodes, arg.TargetAdminUserID, arg.RecoveryCodeHashes, arg.CurrentAdminSessionID)
	var regenerated bool
	err := row.Scan(&regenerated)
	return regenerated, err
}
