// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_authorization.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setAdminPermissions = `-- name: SetAdminPermissions :one
WITH target AS (
    SELECT u.admin_user_id, u.admin_user_state
    FROM vetchium.admin_users AS u
    WHERE u.admin_user_id = $1
), managers AS (
    SELECT u.admin_user_id
    FROM vetchium.admin_effective_permissions AS e
    JOIN vetchium.admin_users AS u USING (admin_user_id)
    WHERE e.permission = 'admin:manage_users'
      AND u.admin_user_state = 'active'
), permitted AS (
    SELECT t.admin_user_id
    FROM target AS t
    WHERE EXISTS (
            SELECT 1
            FROM managers
            WHERE managers.admin_user_id <> t.admin_user_id
        )
       OR t.admin_user_state = 'active' AND
            'admin:manage_users' = ANY($2::text[])
       OR NOT EXISTS (SELECT 1 FROM managers)
), deleted AS (
    DELETE FROM vetchium.admin_permissions
    WHERE admin_user_id IN (SELECT admin_user_id FROM permitted)
), inserted AS (
    INSERT INTO vetchium.admin_permissions (admin_user_id, permission)
    SELECT permitted.admin_user_id, requested.permission
    FROM permitted
    CROSS JOIN unnest($2::text[]) AS requested(permission)
    RETURNING admin_user_id
)
SELECT CASE
    WHEN NOT EXISTS (SELECT 1 FROM target) THEN 'not_found'
    WHEN NOT EXISTS (SELECT 1 FROM permitted) THEN 'last_manager'
    ELSE 'ok'
END::text AS result
`

type SetAdminPermissionsParams struct {
	TargetAdminUserID pgtype.UUID `json:"target_admin_user_id"`
	Permissions       []string    `json:"permissions"`
}

// Refused when the replacement would remove the last active administrator
// able to manage administrators, which no remaining principal could undo. A
// tenant that already has none is not held to the invariant it has lost.
func (q *Queries) SetAdminPermissions(ctx context.Context, arg SetAdminPermissionsParams) (string, error) {
	row := q.db.QueryRow(ctx, setAdminPermissions, arg.TargetAdminUserID, arg.Permissions)
	var result string
	err := row.Scan(&result)
	return result, err
}
