// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminSession = `-- name: CreateAdminSession :one
WITH updated_admin_user AS (
    UPDATE vetchium.admin_users AS u
    SET last_login_at = now(),
        updated_at = now()
    WHERE u.admin_user_id = $2
      AND u.admin_user_state = 'active'
    RETURNING u.admin_user_id
)
INSERT INTO vetchium.admin_sessions (
    session_token_hash,
    admin_user_id,
    expires_at
)
SELECT $1, u.admin_user_id, $3
FROM updated_admin_user AS u
RETURNING admin_session_id, created_at, expires_at
`

type CreateAdminSessionParams struct {
	SessionTokenHash []byte             `json:"session_token_hash"`
	AdminUserID      pgtype.UUID        `json:"admin_user_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type CreateAdminSessionRow struct {
	AdminSessionID pgtype.UUID        `json:"admin_session_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (CreateAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, createAdminSession, arg.SessionTokenHash, arg.AdminUserID, arg.ExpiresAt)
	var i CreateAdminSessionRow
	err := row.Scan(&i.AdminSessionID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const deleteAdminSession = `-- name: DeleteAdminSession :execrows
DELETE FROM vetchium.admin_sessions
WHERE session_token_hash = $1
`

func (q *Queries) DeleteAdminSession(ctx context.Context, sessionTokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminSession, sessionTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :execrows
DELETE FROM vetchium.admin_sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAdminSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminUserForLogin = `-- name: GetAdminUserForLogin :one
SELECT
    admin_user_id,
    email_address,
    display_name,
    password_hash,
    admin_user_state
FROM vetchium.admin_users
WHERE email_address = $1
`

type GetAdminUserForLoginRow struct {
	AdminUserID    pgtype.UUID            `json:"admin_user_id"`
	EmailAddress   string                 `json:"email_address"`
	DisplayName    string                 `json:"display_name"`
	PasswordHash   string                 `json:"password_hash"`
	AdminUserState VetchiumAdminUserState `json:"admin_user_state"`
}

func (q *Queries) GetAdminUserForLogin(ctx context.Context, emailAddress string) (GetAdminUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserForLogin, emailAddress)
	var i GetAdminUserForLoginRow
	err := row.Scan(
		&i.AdminUserID,
		&i.EmailAddress,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AdminUserState,
	)
	return i, err
}

const getAuthenticatedAdmin = `-- name: GetAuthenticatedAdmin :one
SELECT
    u.admin_user_id,
    u.email_address,
    u.display_name,
    u.admin_user_state,
    u.last_login_at,
    u.created_at,
    s.admin_session_id,
    s.session_token_hash,
    s.expires_at
FROM vetchium.admin_sessions AS s
JOIN vetchium.admin_users AS u USING (admin_user_id)
WHERE s.session_token_hash = $1
  AND s.expires_at > now()
  AND u.admin_user_state = 'active'
`

type GetAuthenticatedAdminRow struct {
	AdminUserID      pgtype.UUID            `json:"admin_user_id"`
	EmailAddress     string                 `json:"email_address"`
	DisplayName      string                 `json:"display_name"`
	AdminUserState   VetchiumAdminUserState `json:"admin_user_state"`
	LastLoginAt      pgtype.Timestamptz     `json:"last_login_at"`
	CreatedAt        pgtype.Timestamptz     `json:"created_at"`
	AdminSessionID   pgtype.UUID            `json:"admin_session_id"`
	SessionTokenHash []byte                 `json:"session_token_hash"`
	ExpiresAt        pgtype.Timestamptz     `json:"expires_at"`
}

func (q *Queries) GetAuthenticatedAdmin(ctx context.Context, sessionTokenHash []byte) (GetAuthenticatedAdminRow, error) {
	row := q.db.QueryRow(ctx, getAuthenticatedAdmin, sessionTokenHash)
	var i GetAuthenticatedAdminRow
	err := row.Scan(
		&i.AdminUserID,
		&i.EmailAddress,
		&i.DisplayName,
		&i.AdminUserState,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.AdminSessionID,
		&i.SessionTokenHash,
		&i.ExpiresAt,
	)
	return i, err
}
