// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAdminIdempotency = `-- name: CompleteAdminIdempotency :exec
UPDATE vetchium.admin_idempotency_ledger
SET response_status = $4,
    response_ciphertext = $5
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
`

type CompleteAdminIdempotencyParams struct {
	Operation          string      `json:"operation"`
	BindingID          string      `json:"binding_id"`
	IdempotencyKey     string      `json:"idempotency_key"`
	ResponseStatus     pgtype.Int4 `json:"response_status"`
	ResponseCiphertext []byte      `json:"response_ciphertext"`
}

func (q *Queries) CompleteAdminIdempotency(ctx context.Context, arg CompleteAdminIdempotencyParams) error {
	_, err := q.db.Exec(ctx, completeAdminIdempotency,
		arg.Operation,
		arg.BindingID,
		arg.IdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseCiphertext,
	)
	return err
}

const createAdminIdempotency = `-- name: CreateAdminIdempotency :exec
INSERT INTO vetchium.admin_idempotency_ledger (
    operation,
    binding_id,
    idempotency_key,
    request_digest,
    expires_at
)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAdminIdempotencyParams struct {
	Operation      string             `json:"operation"`
	BindingID      string             `json:"binding_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestDigest  []byte             `json:"request_digest"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAdminIdempotency(ctx context.Context, arg CreateAdminIdempotencyParams) error {
	_, err := q.db.Exec(ctx, createAdminIdempotency,
		arg.Operation,
		arg.BindingID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.ExpiresAt,
	)
	return err
}

const deleteAdminIdempotency = `-- name: DeleteAdminIdempotency :exec
DELETE FROM vetchium.admin_idempotency_ledger
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
`

type DeleteAdminIdempotencyParams struct {
	Operation      string `json:"operation"`
	BindingID      string `json:"binding_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) DeleteAdminIdempotency(ctx context.Context, arg DeleteAdminIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteAdminIdempotency, arg.Operation, arg.BindingID, arg.IdempotencyKey)
	return err
}

const deleteExpiredAdminIdempotency = `-- name: DeleteExpiredAdminIdempotency :exec
DELETE FROM vetchium.admin_idempotency_ledger
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
  AND expires_at <= now()
`

type DeleteExpiredAdminIdempotencyParams struct {
	Operation      string `json:"operation"`
	BindingID      string `json:"binding_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) DeleteExpiredAdminIdempotency(ctx context.Context, arg DeleteExpiredAdminIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredAdminIdempotency, arg.Operation, arg.BindingID, arg.IdempotencyKey)
	return err
}

const getAdminIdempotency = `-- name: GetAdminIdempotency :one
SELECT request_digest, response_status, response_ciphertext, expires_at
FROM vetchium.admin_idempotency_ledger
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
  AND expires_at > now()
FOR UPDATE
`

type GetAdminIdempotencyParams struct {
	Operation      string `json:"operation"`
	BindingID      string `json:"binding_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetAdminIdempotencyRow struct {
	RequestDigest      []byte             `json:"request_digest"`
	ResponseStatus     pgtype.Int4        `json:"response_status"`
	ResponseCiphertext []byte             `json:"response_ciphertext"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetAdminIdempotency(ctx context.Context, arg GetAdminIdempotencyParams) (GetAdminIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getAdminIdempotency, arg.Operation, arg.BindingID, arg.IdempotencyKey)
	var i GetAdminIdempotencyRow
	err := row.Scan(
		&i.RequestDigest,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.ExpiresAt,
	)
	return i, err
}

const lockAdminEmailCredentialMutation = `-- name: LockAdminEmailCredentialMutation :one
SELECT admin_user_id
FROM vetchium.admin_users
WHERE email_address = $1
FOR UPDATE
`

func (q *Queries) LockAdminEmailCredentialMutation(ctx context.Context, emailAddress string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAdminEmailCredentialMutation, emailAddress)
	var admin_user_id pgtype.UUID
	err := row.Scan(&admin_user_id)
	return admin_user_id, err
}

const lockAdminIdempotency = `-- name: LockAdminIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockAdminIdempotency(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockAdminIdempotency, dollar_1)
	return err
}

const lockAdminUserCredentialMutation = `-- name: LockAdminUserCredentialMutation :one
SELECT admin_user_id
FROM vetchium.admin_users
WHERE admin_user_id = $1
FOR UPDATE
`

func (q *Queries) LockAdminUserCredentialMutation(ctx context.Context, adminUserID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAdminUserCredentialMutation, adminUserID)
	var admin_user_id pgtype.UUID
	err := row.Scan(&admin_user_id)
	return admin_user_id, err
}
