// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAdminSetup = `-- name: CompleteAdminSetup :one
WITH invitation AS (
    SELECT i.admin_invitation_id, i.email_address
    FROM vetchium.admin_invitations AS i
    WHERE i.token_hash = $1
      AND i.active
      AND i.consumed_at IS NULL
      AND i.expires_at > now()
    FOR UPDATE
), existing_user AS (
    SELECT 1
    FROM vetchium.admin_users
    WHERE email_address = (SELECT email_address FROM invitation)
), inserted_user AS (
    INSERT INTO vetchium.admin_users (
        admin_user_id,
        email_address,
        display_name,
        password_hash,
        primary_display_name_language,
        preferred_language,
        preferred_timezone
    )
    SELECT
        $2,
        email_address,
        $3,
        $4,
        $5,
        $6,
        $7
    FROM invitation
    WHERE NOT EXISTS (SELECT 1 FROM existing_user)
    ON CONFLICT (email_address) DO NOTHING
    RETURNING admin_user_id
), names AS (
    INSERT INTO vetchium.admin_display_names (
        admin_user_id,
        language_code,
        display_name
    )
    SELECT
        u.admin_user_id,
        names.language_code,
        names.display_name
    FROM inserted_user AS u
    CROSS JOIN LATERAL (
        SELECT
            unnest($8::text[]) AS language_code,
            unnest($9::text[]) AS display_name
    ) AS names
    RETURNING admin_user_id
), consumed AS (
    UPDATE vetchium.admin_invitations
    SET consumed_at = now(),
        active = false
    WHERE admin_invitation_id = (
        SELECT admin_invitation_id FROM invitation
    )
      AND EXISTS (SELECT 1 FROM inserted_user)
      AND EXISTS (SELECT 1 FROM names)
    RETURNING admin_invitation_id
)
SELECT
    CASE
        WHEN EXISTS (SELECT 1 FROM inserted_user) AND
            EXISTS (SELECT 1 FROM consumed) THEN 'ok'
        WHEN NOT EXISTS (SELECT 1 FROM invitation) THEN 'invalid_token'
        ELSE 'user_exists'
    END::text AS result,
    (SELECT admin_user_id FROM inserted_user) AS admin_user_id
`

type CompleteAdminSetupParams struct {
	InvitationTokenHash []byte      `json:"invitation_token_hash"`
	NewAdminUserID      pgtype.UUID `json:"new_admin_user_id"`
	PrimaryDisplayName  string      `json:"primary_display_name"`
	PasswordHash        string      `json:"password_hash"`
	PrimaryLanguage     string      `json:"primary_language"`
	PreferredLanguage   pgtype.Text `json:"preferred_language"`
	PreferredTimezone   pgtype.Text `json:"preferred_timezone"`
	LanguageCodes       []string    `json:"language_codes"`
	DisplayNames        []string    `json:"display_names"`
}

type CompleteAdminSetupRow struct {
	Result      string      `json:"result"`
	AdminUserID pgtype.UUID `json:"admin_user_id"`
}

func (q *Queries) CompleteAdminSetup(ctx context.Context, arg CompleteAdminSetupParams) (CompleteAdminSetupRow, error) {
	row := q.db.QueryRow(ctx, completeAdminSetup,
		arg.InvitationTokenHash,
		arg.NewAdminUserID,
		arg.PrimaryDisplayName,
		arg.PasswordHash,
		arg.PrimaryLanguage,
		arg.PreferredLanguage,
		arg.PreferredTimezone,
		arg.LanguageCodes,
		arg.DisplayNames,
	)
	var i CompleteAdminSetupRow
	err := row.Scan(&i.Result, &i.AdminUserID)
	return i, err
}

const createAdminInvitation = `-- name: CreateAdminInvitation :one
WITH existing_user AS (
    SELECT 1
    FROM vetchium.admin_users AS u
    WHERE u.email_address = $1
), upserted AS (
    INSERT INTO vetchium.admin_invitations (
        admin_invitation_id,
        email_address,
        token_hash,
        invited_by,
        expires_at
    )
    SELECT
        $2,
        $1,
        $3,
        $4,
        $5
    WHERE NOT EXISTS (SELECT 1 FROM existing_user)
    ON CONFLICT (email_address) WHERE active DO UPDATE
    SET admin_invitation_id = EXCLUDED.admin_invitation_id,
        token_hash = EXCLUDED.token_hash,
        invited_by = EXCLUDED.invited_by,
        created_at = EXCLUDED.created_at,
        expires_at = EXCLUDED.expires_at,
        consumed_at = NULL,
        active = true
    WHERE admin_invitations.expires_at <= now()
    RETURNING admin_invitation_id, expires_at
), outbox AS (
    INSERT INTO vetchium.admin_email_outbox (
        kind,
        recipient_email_address,
        payload_ciphertext
    )
    SELECT
        'invitation',
        $1,
        $6
    FROM upserted
    RETURNING admin_email_outbox_id
)
SELECT
    CASE
        WHEN EXISTS (SELECT 1 FROM upserted) THEN 'ok'
        WHEN EXISTS (SELECT 1 FROM existing_user) THEN 'user_exists'
        ELSE 'pending'
    END::text AS result,
    (SELECT admin_invitation_id FROM upserted) AS admin_invitation_id,
    (SELECT expires_at FROM upserted) AS expires_at,
    EXISTS (SELECT 1 FROM outbox) AS queued
`

type CreateAdminInvitationParams struct {
	TargetEmailAddress string             `json:"target_email_address"`
	AdminInvitationID  pgtype.UUID        `json:"admin_invitation_id"`
	TokenHash          []byte             `json:"token_hash"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	PayloadCiphertext  []byte             `json:"payload_ciphertext"`
}

type CreateAdminInvitationRow struct {
	Result            string             `json:"result"`
	AdminInvitationID pgtype.UUID        `json:"admin_invitation_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Queued            bool               `json:"queued"`
}

func (q *Queries) CreateAdminInvitation(ctx context.Context, arg CreateAdminInvitationParams) (CreateAdminInvitationRow, error) {
	row := q.db.QueryRow(ctx, createAdminInvitation,
		arg.TargetEmailAddress,
		arg.AdminInvitationID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.PayloadCiphertext,
	)
	var i CreateAdminInvitationRow
	err := row.Scan(
		&i.Result,
		&i.AdminInvitationID,
		&i.ExpiresAt,
		&i.Queued,
	)
	return i, err
}
