// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: federation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyHubProfileAlias = `-- name: ApplyHubProfileAlias :one
WITH previous AS (
    SELECT u.hub_user_did, u.profile_alias, u.alias_last_changed_at
    FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
      AND u.hub_plan_oid <> 'hub-free-tier'
      AND u.profile_alias IS NOT DISTINCT FROM
          $2::text
      AND (u.profile_version = $3
           OR $4::text IS NULL)
    FOR UPDATE
), updated AS (
    UPDATE vetchium.hub_users AS u
    SET profile_alias = $4,
        alias_last_changed_at = now(),
        profile_version = profile_version + 1,
        updated_at = now()
    FROM previous
    WHERE u.hub_user_did = previous.hub_user_did
      AND u.profile_alias IS DISTINCT FROM $4
    RETURNING u.hub_user_did, u.profile_alias, u.alias_last_changed_at,
        u.profile_version, previous.profile_alias AS previous_alias
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $5, 'hub.profile.alias-changed', 'hub_user',
        hub_user_did::text, 'hub_user', hub_user_did::text, 'hub-api',
        $6, jsonb_build_object(
            'schema_version', 1, 'previous_alias', previous_alias,
            'alias', profile_alias,
            'profile_version', profile_version
        )
    FROM updated
)
SELECT hub_user_did, profile_alias, alias_last_changed_at, profile_version
FROM updated
`

type ApplyHubProfileAliasParams struct {
	HubUserDid             pgtype.UUID `json:"hub_user_did"`
	PreviousAlias          pgtype.Text `json:"previous_alias"`
	ExpectedProfileVersion int64       `json:"expected_profile_version"`
	ProfileAlias           pgtype.Text `json:"profile_alias"`
	TenantID               string      `json:"tenant_id"`
	IdempotencyKey         pgtype.Text `json:"idempotency_key"`
}

type ApplyHubProfileAliasRow struct {
	HubUserDid         pgtype.UUID        `json:"hub_user_did"`
	ProfileAlias       pgtype.Text        `json:"profile_alias"`
	AliasLastChangedAt pgtype.Timestamptz `json:"alias_last_changed_at"`
	ProfileVersion     int64              `json:"profile_version"`
}

func (q *Queries) ApplyHubProfileAlias(ctx context.Context, arg ApplyHubProfileAliasParams) (ApplyHubProfileAliasRow, error) {
	row := q.db.QueryRow(ctx, applyHubProfileAlias,
		arg.HubUserDid,
		arg.PreviousAlias,
		arg.ExpectedProfileVersion,
		arg.ProfileAlias,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i ApplyHubProfileAliasRow
	err := row.Scan(
		&i.HubUserDid,
		&i.ProfileAlias,
		&i.AliasLastChangedAt,
		&i.ProfileVersion,
	)
	return i, err
}

const claimFederationOutboxEvent = `-- name: ClaimFederationOutboxEvent :one
WITH candidate AS (
    SELECT event_id
    FROM vetchium.federation_outbox
    WHERE delivered_at IS NULL AND failed_at IS NULL
      AND next_attempt_at <= now()
      AND (leased_until IS NULL OR leased_until <= now())
    ORDER BY next_attempt_at, created_at, event_id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
), claimed AS (
    UPDATE vetchium.federation_outbox AS event
    SET lease_token = $1,
        leased_until = now() + interval '1 minute',
        attempt_count = attempt_count + 1
    WHERE event.event_id = (SELECT event_id FROM candidate)
    RETURNING event.event_id, event.destination_tenant_id, event.kind,
        event.aggregate_type, event.aggregate_id, event.aggregate_version,
        event.payload, event.payload_digest, event.attempt_count,
        event.next_attempt_at, event.lease_token, event.leased_until,
        event.created_at, event.delivered_at, event.failed_at,
        event.last_error
)
SELECT event_id, destination_tenant_id, kind, aggregate_type, aggregate_id,
    aggregate_version, payload, payload_digest, attempt_count,
    next_attempt_at, lease_token, leased_until, created_at, delivered_at,
    failed_at, last_error
FROM claimed
`

type ClaimFederationOutboxEventRow struct {
	EventID             pgtype.UUID        `json:"event_id"`
	DestinationTenantID string             `json:"destination_tenant_id"`
	Kind                string             `json:"kind"`
	AggregateType       string             `json:"aggregate_type"`
	AggregateID         string             `json:"aggregate_id"`
	AggregateVersion    int64              `json:"aggregate_version"`
	Payload             []byte             `json:"payload"`
	PayloadDigest       []byte             `json:"payload_digest"`
	AttemptCount        int32              `json:"attempt_count"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseToken          pgtype.UUID        `json:"lease_token"`
	LeasedUntil         pgtype.Timestamptz `json:"leased_until"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DeliveredAt         pgtype.Timestamptz `json:"delivered_at"`
	FailedAt            pgtype.Timestamptz `json:"failed_at"`
	LastError           pgtype.Text        `json:"last_error"`
}

func (q *Queries) ClaimFederationOutboxEvent(ctx context.Context, leaseToken pgtype.UUID) (ClaimFederationOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, claimFederationOutboxEvent, leaseToken)
	var i ClaimFederationOutboxEventRow
	err := row.Scan(
		&i.EventID,
		&i.DestinationTenantID,
		&i.Kind,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.PayloadDigest,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.LastError,
	)
	return i, err
}

const completeFederationOutboxEvent = `-- name: CompleteFederationOutboxEvent :execrows
UPDATE vetchium.federation_outbox
SET delivered_at = now(), lease_token = NULL, leased_until = NULL,
    last_error = NULL
WHERE event_id = $1
  AND lease_token = $2
  AND delivered_at IS NULL AND failed_at IS NULL
`

type CompleteFederationOutboxEventParams struct {
	EventID    pgtype.UUID `json:"event_id"`
	LeaseToken pgtype.UUID `json:"lease_token"`
}

func (q *Queries) CompleteFederationOutboxEvent(ctx context.Context, arg CompleteFederationOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeFederationOutboxEvent, arg.EventID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createFederationOperation = `-- name: CreateFederationOperation :one
INSERT INTO vetchium.federation_operations (
    operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, expires_at
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11
)
RETURNING operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, state, response_status,
    response_ciphertext, attempt_count, next_attempt_at, last_error,
    created_at, updated_at, completed_at, expires_at
`

type CreateFederationOperationParams struct {
	OperationID        pgtype.UUID        `json:"operation_id"`
	CommandID          pgtype.UUID        `json:"command_id"`
	Kind               string             `json:"kind"`
	TargetAuthority    string             `json:"target_authority"`
	AggregateID        string             `json:"aggregate_id"`
	OwnerPrincipalType string             `json:"owner_principal_type"`
	OwnerPrincipalID   string             `json:"owner_principal_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestDigest      []byte             `json:"request_digest"`
	PayloadBytes       []byte             `json:"payload_bytes"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateFederationOperation(ctx context.Context, arg CreateFederationOperationParams) (VetchiumFederationOperation, error) {
	row := q.db.QueryRow(ctx, createFederationOperation,
		arg.OperationID,
		arg.CommandID,
		arg.Kind,
		arg.TargetAuthority,
		arg.AggregateID,
		arg.OwnerPrincipalType,
		arg.OwnerPrincipalID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.PayloadBytes,
		arg.ExpiresAt,
	)
	var i VetchiumFederationOperation
	err := row.Scan(
		&i.OperationID,
		&i.CommandID,
		&i.Kind,
		&i.TargetAuthority,
		&i.AggregateID,
		&i.OwnerPrincipalType,
		&i.OwnerPrincipalID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadBytes,
		&i.State,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createFederationOutboxEvent = `-- name: CreateFederationOutboxEvent :one
INSERT INTO vetchium.federation_outbox (
    event_id, destination_tenant_id, kind, aggregate_type, aggregate_id,
    aggregate_version, payload, payload_digest
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8
)
RETURNING event_id, destination_tenant_id, kind, aggregate_type,
    aggregate_id, aggregate_version, payload, payload_digest, attempt_count,
    next_attempt_at, lease_token, leased_until, created_at, delivered_at,
    failed_at, last_error
`

type CreateFederationOutboxEventParams struct {
	EventID             pgtype.UUID `json:"event_id"`
	DestinationTenantID string      `json:"destination_tenant_id"`
	Kind                string      `json:"kind"`
	AggregateType       string      `json:"aggregate_type"`
	AggregateID         string      `json:"aggregate_id"`
	AggregateVersion    int64       `json:"aggregate_version"`
	Payload             []byte      `json:"payload"`
	PayloadDigest       []byte      `json:"payload_digest"`
}

func (q *Queries) CreateFederationOutboxEvent(ctx context.Context, arg CreateFederationOutboxEventParams) (VetchiumFederationOutbox, error) {
	row := q.db.QueryRow(ctx, createFederationOutboxEvent,
		arg.EventID,
		arg.DestinationTenantID,
		arg.Kind,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
		arg.PayloadDigest,
	)
	var i VetchiumFederationOutbox
	err := row.Scan(
		&i.EventID,
		&i.DestinationTenantID,
		&i.Kind,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.PayloadDigest,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.LastError,
	)
	return i, err
}

const getFederationCommandResult = `-- name: GetFederationCommandResult :one
SELECT command_id, source_tenant_id, kind, aggregate_id, request_digest,
    response_status, response_body, completed_at
FROM vetchium.federation_command_ledger
WHERE command_id = $1
`

func (q *Queries) GetFederationCommandResult(ctx context.Context, commandID pgtype.UUID) (VetchiumFederationCommandLedger, error) {
	row := q.db.QueryRow(ctx, getFederationCommandResult, commandID)
	var i VetchiumFederationCommandLedger
	err := row.Scan(
		&i.CommandID,
		&i.SourceTenantID,
		&i.Kind,
		&i.AggregateID,
		&i.RequestDigest,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CompletedAt,
	)
	return i, err
}

const getFederationOperation = `-- name: GetFederationOperation :one
SELECT operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, state, response_status,
    response_ciphertext, attempt_count, next_attempt_at, last_error,
    created_at, updated_at, completed_at, expires_at
FROM vetchium.federation_operations
WHERE operation_id = $1
  AND expires_at > now()
`

func (q *Queries) GetFederationOperation(ctx context.Context, operationID pgtype.UUID) (VetchiumFederationOperation, error) {
	row := q.db.QueryRow(ctx, getFederationOperation, operationID)
	var i VetchiumFederationOperation
	err := row.Scan(
		&i.OperationID,
		&i.CommandID,
		&i.Kind,
		&i.TargetAuthority,
		&i.AggregateID,
		&i.OwnerPrincipalType,
		&i.OwnerPrincipalID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadBytes,
		&i.State,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getFederationOperationByIdempotency = `-- name: GetFederationOperationByIdempotency :one
SELECT operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, state, response_status,
    response_ciphertext, attempt_count, next_attempt_at, last_error,
    created_at, updated_at, completed_at, expires_at
FROM vetchium.federation_operations
WHERE kind = $1
  AND aggregate_id = $2
  AND idempotency_key = $3
  AND expires_at > now()
`

type GetFederationOperationByIdempotencyParams struct {
	Kind           string `json:"kind"`
	AggregateID    string `json:"aggregate_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetFederationOperationByIdempotency(ctx context.Context, arg GetFederationOperationByIdempotencyParams) (VetchiumFederationOperation, error) {
	row := q.db.QueryRow(ctx, getFederationOperationByIdempotency, arg.Kind, arg.AggregateID, arg.IdempotencyKey)
	var i VetchiumFederationOperation
	err := row.Scan(
		&i.OperationID,
		&i.CommandID,
		&i.Kind,
		&i.TargetAuthority,
		&i.AggregateID,
		&i.OwnerPrincipalType,
		&i.OwnerPrincipalID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadBytes,
		&i.State,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getHubAliasMutationState = `-- name: GetHubAliasMutationState :one
SELECT u.hub_plan_oid, u.profile_alias, u.alias_last_changed_at,
    u.profile_version,
    EXISTS (
        SELECT 1 FROM vetchium.federation_operations AS operation
        WHERE operation.kind = 'hub-alias-change'
          AND operation.aggregate_id = u.hub_user_did::text
          AND operation.state = 'pending'
    ) AS has_pending_change
FROM vetchium.hub_users AS u
JOIN vetchium.hub_sessions AS session USING (hub_user_did)
WHERE u.hub_user_did = $1
  AND session.hub_session_id = $2
  AND session.expires_at > now()
  AND u.hub_user_state = 'active'
FOR UPDATE OF u
`

type GetHubAliasMutationStateParams struct {
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
	HubSessionID pgtype.UUID `json:"hub_session_id"`
}

type GetHubAliasMutationStateRow struct {
	HubPlanOid         string             `json:"hub_plan_oid"`
	ProfileAlias       pgtype.Text        `json:"profile_alias"`
	AliasLastChangedAt pgtype.Timestamptz `json:"alias_last_changed_at"`
	ProfileVersion     int64              `json:"profile_version"`
	HasPendingChange   bool               `json:"has_pending_change"`
}

func (q *Queries) GetHubAliasMutationState(ctx context.Context, arg GetHubAliasMutationStateParams) (GetHubAliasMutationStateRow, error) {
	row := q.db.QueryRow(ctx, getHubAliasMutationState, arg.HubUserDid, arg.HubSessionID)
	var i GetHubAliasMutationStateRow
	err := row.Scan(
		&i.HubPlanOid,
		&i.ProfileAlias,
		&i.AliasLastChangedAt,
		&i.ProfileVersion,
		&i.HasPendingChange,
	)
	return i, err
}

const getHubFederationOperationStatus = `-- name: GetHubFederationOperationStatus :one
SELECT operation_id, state
FROM vetchium.federation_operations
WHERE operation_id = $1
  AND owner_principal_type = 'hub_user'
  AND owner_principal_id = $2
  AND expires_at > now()
`

type GetHubFederationOperationStatusParams struct {
	OperationID      pgtype.UUID `json:"operation_id"`
	OwnerPrincipalID string      `json:"owner_principal_id"`
}

type GetHubFederationOperationStatusRow struct {
	OperationID pgtype.UUID                      `json:"operation_id"`
	State       VetchiumFederationOperationState `json:"state"`
}

func (q *Queries) GetHubFederationOperationStatus(ctx context.Context, arg GetHubFederationOperationStatusParams) (GetHubFederationOperationStatusRow, error) {
	row := q.db.QueryRow(ctx, getHubFederationOperationStatus, arg.OperationID, arg.OwnerPrincipalID)
	var i GetHubFederationOperationStatusRow
	err := row.Scan(&i.OperationID, &i.State)
	return i, err
}

const hubAliasOperationPreflight = `-- name: HubAliasOperationPreflight :one
SELECT EXISTS (
    SELECT 1 FROM vetchium.hub_users
    WHERE hub_user_did = $1
      AND hub_user_state = 'active'
      AND hub_plan_oid <> 'hub-free-tier'
      AND profile_version = $2
) AS may_dispatch
`

type HubAliasOperationPreflightParams struct {
	HubUserDid             pgtype.UUID `json:"hub_user_did"`
	ExpectedProfileVersion int64       `json:"expected_profile_version"`
}

func (q *Queries) HubAliasOperationPreflight(ctx context.Context, arg HubAliasOperationPreflightParams) (bool, error) {
	row := q.db.QueryRow(ctx, hubAliasOperationPreflight, arg.HubUserDid, arg.ExpectedProfileVersion)
	var may_dispatch bool
	err := row.Scan(&may_dispatch)
	return may_dispatch, err
}

const listRecoverableFederationOperations = `-- name: ListRecoverableFederationOperations :many
SELECT operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, state, response_status,
    response_ciphertext, attempt_count, next_attempt_at, last_error,
    created_at, updated_at, completed_at, expires_at
FROM vetchium.federation_operations
WHERE state = 'pending' AND next_attempt_at <= now()
ORDER BY next_attempt_at, created_at, operation_id
LIMIT $1
`

func (q *Queries) ListRecoverableFederationOperations(ctx context.Context, batchSize int32) ([]VetchiumFederationOperation, error) {
	rows, err := q.db.Query(ctx, listRecoverableFederationOperations, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VetchiumFederationOperation
	for rows.Next() {
		var i VetchiumFederationOperation
		if err := rows.Scan(
			&i.OperationID,
			&i.CommandID,
			&i.Kind,
			&i.TargetAuthority,
			&i.AggregateID,
			&i.OwnerPrincipalType,
			&i.OwnerPrincipalID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.PayloadBytes,
			&i.State,
			&i.ResponseStatus,
			&i.ResponseCiphertext,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoverableHubAliasChanges = `-- name: ListRecoverableHubAliasChanges :many
SELECT operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, state, response_status,
    response_ciphertext, attempt_count, next_attempt_at, last_error,
    created_at, updated_at, completed_at, expires_at
FROM vetchium.federation_operations
WHERE kind = 'hub-alias-change'
  AND state = 'pending' AND next_attempt_at <= now()
ORDER BY next_attempt_at, created_at, operation_id
LIMIT $1
`

func (q *Queries) ListRecoverableHubAliasChanges(ctx context.Context, batchSize int32) ([]VetchiumFederationOperation, error) {
	rows, err := q.db.Query(ctx, listRecoverableHubAliasChanges, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VetchiumFederationOperation
	for rows.Next() {
		var i VetchiumFederationOperation
		if err := rows.Scan(
			&i.OperationID,
			&i.CommandID,
			&i.Kind,
			&i.TargetAuthority,
			&i.AggregateID,
			&i.OwnerPrincipalType,
			&i.OwnerPrincipalID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.PayloadBytes,
			&i.State,
			&i.ResponseStatus,
			&i.ResponseCiphertext,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoverableHubAliasReleases = `-- name: ListRecoverableHubAliasReleases :many
SELECT operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, state, response_status,
    response_ciphertext, attempt_count, next_attempt_at, last_error,
    created_at, updated_at, completed_at, expires_at
FROM vetchium.federation_operations
WHERE kind = 'hub-alias-release'
  AND state = 'pending' AND next_attempt_at <= now()
ORDER BY next_attempt_at, created_at, operation_id
LIMIT $1
`

func (q *Queries) ListRecoverableHubAliasReleases(ctx context.Context, batchSize int32) ([]VetchiumFederationOperation, error) {
	rows, err := q.db.Query(ctx, listRecoverableHubAliasReleases, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VetchiumFederationOperation
	for rows.Next() {
		var i VetchiumFederationOperation
		if err := rows.Scan(
			&i.OperationID,
			&i.CommandID,
			&i.Kind,
			&i.TargetAuthority,
			&i.AggregateID,
			&i.OwnerPrincipalType,
			&i.OwnerPrincipalID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.PayloadBytes,
			&i.State,
			&i.ResponseStatus,
			&i.ResponseCiphertext,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneExpiredFederationOperations = `-- name: PruneExpiredFederationOperations :execrows
DELETE FROM vetchium.federation_operations
WHERE state IN ('succeeded', 'failed') AND expires_at <= now()
`

func (q *Queries) PruneExpiredFederationOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredFederationOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordFederationCommandResult = `-- name: RecordFederationCommandResult :one
INSERT INTO vetchium.federation_command_ledger (
    command_id, source_tenant_id, kind, aggregate_id, request_digest,
    response_status, response_body
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
ON CONFLICT (command_id) DO UPDATE
SET command_id = vetchium.federation_command_ledger.command_id
WHERE vetchium.federation_command_ledger.source_tenant_id =
        EXCLUDED.source_tenant_id
  AND vetchium.federation_command_ledger.kind = EXCLUDED.kind
  AND vetchium.federation_command_ledger.aggregate_id = EXCLUDED.aggregate_id
  AND vetchium.federation_command_ledger.request_digest =
        EXCLUDED.request_digest
  AND vetchium.federation_command_ledger.response_status =
        EXCLUDED.response_status
  AND vetchium.federation_command_ledger.response_body =
        EXCLUDED.response_body
RETURNING command_id, source_tenant_id, kind, aggregate_id, request_digest,
    response_status, response_body, completed_at
`

type RecordFederationCommandResultParams struct {
	CommandID      pgtype.UUID `json:"command_id"`
	SourceTenantID string      `json:"source_tenant_id"`
	Kind           string      `json:"kind"`
	AggregateID    string      `json:"aggregate_id"`
	RequestDigest  []byte      `json:"request_digest"`
	ResponseStatus int32       `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
}

func (q *Queries) RecordFederationCommandResult(ctx context.Context, arg RecordFederationCommandResultParams) (VetchiumFederationCommandLedger, error) {
	row := q.db.QueryRow(ctx, recordFederationCommandResult,
		arg.CommandID,
		arg.SourceTenantID,
		arg.Kind,
		arg.AggregateID,
		arg.RequestDigest,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var i VetchiumFederationCommandLedger
	err := row.Scan(
		&i.CommandID,
		&i.SourceTenantID,
		&i.Kind,
		&i.AggregateID,
		&i.RequestDigest,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CompletedAt,
	)
	return i, err
}

const recordFederationInboxReceipt = `-- name: RecordFederationInboxReceipt :one
INSERT INTO vetchium.federation_inbox (
    event_id, source_tenant_id, kind, aggregate_type, aggregate_id,
    aggregate_version, payload_digest
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
ON CONFLICT (event_id) DO UPDATE
SET event_id = vetchium.federation_inbox.event_id
WHERE vetchium.federation_inbox.source_tenant_id = EXCLUDED.source_tenant_id
  AND vetchium.federation_inbox.kind = EXCLUDED.kind
  AND vetchium.federation_inbox.aggregate_type = EXCLUDED.aggregate_type
  AND vetchium.federation_inbox.aggregate_id = EXCLUDED.aggregate_id
  AND vetchium.federation_inbox.aggregate_version = EXCLUDED.aggregate_version
  AND vetchium.federation_inbox.payload_digest = EXCLUDED.payload_digest
RETURNING event_id, source_tenant_id, kind, aggregate_type, aggregate_id,
    aggregate_version, payload_digest, received_at, applied_at
`

type RecordFederationInboxReceiptParams struct {
	EventID          pgtype.UUID `json:"event_id"`
	SourceTenantID   string      `json:"source_tenant_id"`
	Kind             string      `json:"kind"`
	AggregateType    string      `json:"aggregate_type"`
	AggregateID      string      `json:"aggregate_id"`
	AggregateVersion int64       `json:"aggregate_version"`
	PayloadDigest    []byte      `json:"payload_digest"`
}

func (q *Queries) RecordFederationInboxReceipt(ctx context.Context, arg RecordFederationInboxReceiptParams) (VetchiumFederationInbox, error) {
	row := q.db.QueryRow(ctx, recordFederationInboxReceipt,
		arg.EventID,
		arg.SourceTenantID,
		arg.Kind,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.PayloadDigest,
	)
	var i VetchiumFederationInbox
	err := row.Scan(
		&i.EventID,
		&i.SourceTenantID,
		&i.Kind,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.PayloadDigest,
		&i.ReceivedAt,
		&i.AppliedAt,
	)
	return i, err
}

const recordFederationOperationRetry = `-- name: RecordFederationOperationRetry :execrows
UPDATE vetchium.federation_operations
SET attempt_count = attempt_count + 1,
    next_attempt_at = now() + LEAST(
        interval '5 minutes',
        interval '1 second' * power(2, LEAST(attempt_count, 8))
    ),
    last_error = left($1, 200),
    updated_at = now()
WHERE operation_id = $2 AND state = 'pending'
`

type RecordFederationOperationRetryParams struct {
	LastError   string      `json:"last_error"`
	OperationID pgtype.UUID `json:"operation_id"`
}

func (q *Queries) RecordFederationOperationRetry(ctx context.Context, arg RecordFederationOperationRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordFederationOperationRetry, arg.LastError, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveFederationOperation = `-- name: ResolveFederationOperation :one
UPDATE vetchium.federation_operations
SET state = $1,
    response_status = $2,
    response_ciphertext = $3,
    payload_bytes = decode('', 'hex'),
    completed_at = now(),
    updated_at = now(),
    last_error = NULL
WHERE operation_id = $4
  AND state = 'pending'
  AND $1::vetchium.federation_operation_state IN (
      'succeeded', 'failed'
  )
RETURNING operation_id, command_id, kind, target_authority, aggregate_id,
    owner_principal_type, owner_principal_id, idempotency_key,
    request_digest, payload_bytes, state, response_status,
    response_ciphertext, attempt_count, next_attempt_at, last_error,
    created_at, updated_at, completed_at, expires_at
`

type ResolveFederationOperationParams struct {
	State              VetchiumFederationOperationState `json:"state"`
	ResponseStatus     pgtype.Int4                      `json:"response_status"`
	ResponseCiphertext []byte                           `json:"response_ciphertext"`
	OperationID        pgtype.UUID                      `json:"operation_id"`
}

func (q *Queries) ResolveFederationOperation(ctx context.Context, arg ResolveFederationOperationParams) (VetchiumFederationOperation, error) {
	row := q.db.QueryRow(ctx, resolveFederationOperation,
		arg.State,
		arg.ResponseStatus,
		arg.ResponseCiphertext,
		arg.OperationID,
	)
	var i VetchiumFederationOperation
	err := row.Scan(
		&i.OperationID,
		&i.CommandID,
		&i.Kind,
		&i.TargetAuthority,
		&i.AggregateID,
		&i.OwnerPrincipalType,
		&i.OwnerPrincipalID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadBytes,
		&i.State,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const retryFederationOutboxEvent = `-- name: RetryFederationOutboxEvent :execrows
UPDATE vetchium.federation_outbox
SET lease_token = NULL, leased_until = NULL,
    next_attempt_at = now() + LEAST(
        interval '5 minutes',
        interval '1 second' * power(2, LEAST(attempt_count, 8))
    ),
    last_error = left($1, 200)
WHERE event_id = $2
  AND lease_token = $3
  AND delivered_at IS NULL AND failed_at IS NULL
`

type RetryFederationOutboxEventParams struct {
	LastError  string      `json:"last_error"`
	EventID    pgtype.UUID `json:"event_id"`
	LeaseToken pgtype.UUID `json:"lease_token"`
}

func (q *Queries) RetryFederationOutboxEvent(ctx context.Context, arg RetryFederationOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryFederationOutboxEvent, arg.LastError, arg.EventID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
