// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_email.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimHubEmail = `-- name: ClaimHubEmail :one
WITH candidate AS (
    SELECT hub_email_outbox_id
    FROM vetchium.hub_email_outbox
    WHERE sent_at IS NULL
      AND failed_at IS NULL
      AND next_attempt_at <= now()
      AND (leased_until IS NULL OR leased_until <= now())
    ORDER BY created_at, hub_email_outbox_id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
), claimed AS (
    UPDATE vetchium.hub_email_outbox
    SET lease_token = $1,
        leased_until = $2,
        attempt_count = attempt_count + 1
    WHERE hub_email_outbox_id = (
        SELECT hub_email_outbox_id FROM candidate
    )
    RETURNING hub_email_outbox_id, kind, recipient_email_address,
        preferred_language, payload_ciphertext, attempt_count
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'hub.email.delivery-claimed',
        'hub_email',
        hub_email_outbox_id::text,
        'worker',
        'email-delivery',
        'workers',
        jsonb_build_object('attempt', attempt_count)
    FROM claimed
)
SELECT
    hub_email_outbox_id,
    kind,
    recipient_email_address,
    preferred_language,
    payload_ciphertext,
    attempt_count
FROM claimed
`

type ClaimHubEmailParams struct {
	LeaseToken  pgtype.UUID        `json:"lease_token"`
	LeasedUntil pgtype.Timestamptz `json:"leased_until"`
	TenantID    string             `json:"tenant_id"`
}

type ClaimHubEmailRow struct {
	HubEmailOutboxID      pgtype.UUID `json:"hub_email_outbox_id"`
	Kind                  string      `json:"kind"`
	RecipientEmailAddress string      `json:"recipient_email_address"`
	PreferredLanguage     string      `json:"preferred_language"`
	PayloadCiphertext     []byte      `json:"payload_ciphertext"`
	AttemptCount          int32       `json:"attempt_count"`
}

func (q *Queries) ClaimHubEmail(ctx context.Context, arg ClaimHubEmailParams) (ClaimHubEmailRow, error) {
	row := q.db.QueryRow(ctx, claimHubEmail, arg.LeaseToken, arg.LeasedUntil, arg.TenantID)
	var i ClaimHubEmailRow
	err := row.Scan(
		&i.HubEmailOutboxID,
		&i.Kind,
		&i.RecipientEmailAddress,
		&i.PreferredLanguage,
		&i.PayloadCiphertext,
		&i.AttemptCount,
	)
	return i, err
}

const markHubEmailFailed = `-- name: MarkHubEmailFailed :one
WITH updated AS (
    UPDATE vetchium.hub_email_outbox
    SET failed_at = now(),
        lease_token = NULL,
        leased_until = NULL
    WHERE hub_email_outbox_id = $1
      AND lease_token = $2
      AND sent_at IS NULL
      AND failed_at IS NULL
    RETURNING hub_email_outbox_id, attempt_count
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'hub.email.failed',
        'hub_email',
        hub_email_outbox_id::text,
        'worker',
        'email-delivery',
        'workers',
        jsonb_build_object('attempt', attempt_count)
    FROM updated
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS marked
`

type MarkHubEmailFailedParams struct {
	HubEmailOutboxID pgtype.UUID `json:"hub_email_outbox_id"`
	LeaseToken       pgtype.UUID `json:"lease_token"`
	TenantID         string      `json:"tenant_id"`
}

func (q *Queries) MarkHubEmailFailed(ctx context.Context, arg MarkHubEmailFailedParams) (bool, error) {
	row := q.db.QueryRow(ctx, markHubEmailFailed, arg.HubEmailOutboxID, arg.LeaseToken, arg.TenantID)
	var marked bool
	err := row.Scan(&marked)
	return marked, err
}

const markHubEmailSent = `-- name: MarkHubEmailSent :one
WITH updated AS (
    UPDATE vetchium.hub_email_outbox
    SET sent_at = now(),
        lease_token = NULL,
        leased_until = NULL
    WHERE hub_email_outbox_id = $1
      AND lease_token = $2
      AND sent_at IS NULL
      AND failed_at IS NULL
    RETURNING hub_email_outbox_id, attempt_count
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'hub.email.sent',
        'hub_email',
        hub_email_outbox_id::text,
        'worker',
        'email-delivery',
        'workers',
        jsonb_build_object('attempt', attempt_count)
    FROM updated
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS marked
`

type MarkHubEmailSentParams struct {
	HubEmailOutboxID pgtype.UUID `json:"hub_email_outbox_id"`
	LeaseToken       pgtype.UUID `json:"lease_token"`
	TenantID         string      `json:"tenant_id"`
}

func (q *Queries) MarkHubEmailSent(ctx context.Context, arg MarkHubEmailSentParams) (bool, error) {
	row := q.db.QueryRow(ctx, markHubEmailSent, arg.HubEmailOutboxID, arg.LeaseToken, arg.TenantID)
	var marked bool
	err := row.Scan(&marked)
	return marked, err
}

const scheduleHubEmailRetry = `-- name: ScheduleHubEmailRetry :one
WITH updated AS (
    UPDATE vetchium.hub_email_outbox
    SET next_attempt_at = $1,
        lease_token = NULL,
        leased_until = NULL
    WHERE hub_email_outbox_id = $2
      AND lease_token = $3
      AND sent_at IS NULL
      AND failed_at IS NULL
    RETURNING hub_email_outbox_id, attempt_count
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'hub.email.retry-scheduled',
        'hub_email',
        hub_email_outbox_id::text,
        'worker',
        'email-delivery',
        'workers',
        jsonb_build_object('attempt', attempt_count)
    FROM updated
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS marked
`

type ScheduleHubEmailRetryParams struct {
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	HubEmailOutboxID pgtype.UUID        `json:"hub_email_outbox_id"`
	LeaseToken       pgtype.UUID        `json:"lease_token"`
	TenantID         string             `json:"tenant_id"`
}

func (q *Queries) ScheduleHubEmailRetry(ctx context.Context, arg ScheduleHubEmailRetryParams) (bool, error) {
	row := q.db.QueryRow(ctx, scheduleHubEmailRetry,
		arg.NextAttemptAt,
		arg.HubEmailOutboxID,
		arg.LeaseToken,
		arg.TenantID,
	)
	var marked bool
	err := row.Scan(&marked)
	return marked, err
}
