// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHubMyInfo = `-- name: GetHubMyInfo :one
SELECT
    u.hub_user_did,
    u.handle,
    u.email_address,
    u.display_name,
    u.preferred_language,
    u.resident_country,
    u.totp_enabled,
    recovery.remaining_codes AS recovery_codes_remaining,
    s.authenticated_at
FROM vetchium.hub_sessions AS s
JOIN vetchium.hub_users AS u USING (hub_user_did)
CROSS JOIN LATERAL (
    SELECT count(*)::bigint AS remaining_codes
    FROM vetchium.hub_totp_recovery_codes AS r
    WHERE r.hub_user_did = u.hub_user_did
      AND r.consumed_at IS NULL
) AS recovery
WHERE s.hub_session_id = $1
  AND u.hub_user_did = $2
  AND s.expires_at > now()
  AND u.hub_user_state = 'active'
`

type GetHubMyInfoParams struct {
	HubSessionID pgtype.UUID `json:"hub_session_id"`
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
}

type GetHubMyInfoRow struct {
	HubUserDid             pgtype.UUID        `json:"hub_user_did"`
	Handle                 string             `json:"handle"`
	EmailAddress           string             `json:"email_address"`
	DisplayName            string             `json:"display_name"`
	PreferredLanguage      string             `json:"preferred_language"`
	ResidentCountry        string             `json:"resident_country"`
	TotpEnabled            bool               `json:"totp_enabled"`
	RecoveryCodesRemaining int64              `json:"recovery_codes_remaining"`
	AuthenticatedAt        pgtype.Timestamptz `json:"authenticated_at"`
}

func (q *Queries) GetHubMyInfo(ctx context.Context, arg GetHubMyInfoParams) (GetHubMyInfoRow, error) {
	row := q.db.QueryRow(ctx, getHubMyInfo, arg.HubSessionID, arg.HubUserDid)
	var i GetHubMyInfoRow
	err := row.Scan(
		&i.HubUserDid,
		&i.Handle,
		&i.EmailAddress,
		&i.DisplayName,
		&i.PreferredLanguage,
		&i.ResidentCountry,
		&i.TotpEnabled,
		&i.RecoveryCodesRemaining,
		&i.AuthenticatedAt,
	)
	return i, err
}

const setHubPreferredLanguage = `-- name: SetHubPreferredLanguage :one
WITH updated AS (
    UPDATE vetchium.hub_users
    SET preferred_language = $1,
        updated_at = now()
    WHERE hub_user_did = $2
      AND hub_user_state = 'active'
    RETURNING hub_user_did, preferred_language
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'hub.profile.preferred-language-set',
        'hub_user',
        hub_user_did::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        jsonb_build_object('preferred_language', preferred_language)
    FROM updated
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS changed
`

type SetHubPreferredLanguageParams struct {
	PreferredLanguage string      `json:"preferred_language"`
	HubUserDid        pgtype.UUID `json:"hub_user_did"`
	TenantID          string      `json:"tenant_id"`
}

func (q *Queries) SetHubPreferredLanguage(ctx context.Context, arg SetHubPreferredLanguageParams) (bool, error) {
	row := q.db.QueryRow(ctx, setHubPreferredLanguage, arg.PreferredLanguage, arg.HubUserDid, arg.TenantID)
	var changed bool
	err := row.Scan(&changed)
	return changed, err
}

const setHubResidentCountry = `-- name: SetHubResidentCountry :one
WITH updated AS (
    UPDATE vetchium.hub_users
    SET resident_country = $1,
        updated_at = now()
    WHERE hub_user_did = $2
      AND hub_user_state = 'active'
    RETURNING hub_user_did, resident_country
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'hub.profile.resident-country-set',
        'hub_user',
        hub_user_did::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        jsonb_build_object('resident_country', resident_country)
    FROM updated
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS changed
`

type SetHubResidentCountryParams struct {
	ResidentCountry string      `json:"resident_country"`
	HubUserDid      pgtype.UUID `json:"hub_user_did"`
	TenantID        string      `json:"tenant_id"`
}

func (q *Queries) SetHubResidentCountry(ctx context.Context, arg SetHubResidentCountryParams) (bool, error) {
	row := q.db.QueryRow(ctx, setHubResidentCountry, arg.ResidentCountry, arg.HubUserDid, arg.TenantID)
	var changed bool
	err := row.Scan(&changed)
	return changed, err
}
