// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateHubSession = `-- name: AuthenticateHubSession :one
SELECT
    u.hub_user_did,
    s.hub_session_id,
    s.authenticated_at
FROM vetchium.hub_sessions AS s
JOIN vetchium.hub_users AS u USING (hub_user_did)
WHERE s.session_token_hash = $1
  AND s.expires_at > now()
  AND u.hub_user_state = 'active'
`

type AuthenticateHubSessionRow struct {
	HubUserDid      pgtype.UUID        `json:"hub_user_did"`
	HubSessionID    pgtype.UUID        `json:"hub_session_id"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
}

func (q *Queries) AuthenticateHubSession(ctx context.Context, sessionTokenHash []byte) (AuthenticateHubSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateHubSession, sessionTokenHash)
	var i AuthenticateHubSessionRow
	err := row.Scan(&i.HubUserDid, &i.HubSessionID, &i.AuthenticatedAt)
	return i, err
}

const completeHubTOTPLogin = `-- name: CompleteHubTOTPLogin :one
WITH accepted_timestep AS (
    UPDATE vetchium.hub_users AS u
    SET totp_last_timestep = $1,
        last_login_at = now(),
        updated_at = now()
    WHERE u.hub_user_did = $2
      AND u.hub_user_state = 'active'
      AND u.totp_enabled
      AND (
          u.totp_last_timestep IS NULL OR
          u.totp_last_timestep < $1
      )
    RETURNING u.hub_user_did
), consumed AS (
    UPDATE vetchium.hub_login_challenges AS c
    SET consumed_at = now(),
        active = false
    FROM accepted_timestep AS u
    WHERE c.hub_login_challenge_id = $3
      AND c.hub_user_did = u.hub_user_did
      AND c.active
      AND c.consumed_at IS NULL
      AND c.expires_at > now()
    RETURNING c.hub_user_did
), session AS (
    INSERT INTO vetchium.hub_sessions (
        session_token_hash,
        hub_user_did,
        expires_at,
        authenticated_at,
        remembered
    )
    SELECT
        $4,
        hub_user_did,
        $5,
        now(),
        $6
    FROM consumed
    RETURNING hub_session_id, hub_user_did, created_at, expires_at,
        authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $7,
        'hub.session.created-with-totp',
        'hub_session',
        hub_session_id::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        $8,
        jsonb_build_object('remembered', $6::boolean)
    FROM session
)
SELECT hub_session_id, created_at, expires_at, authenticated_at
FROM session
`

type CompleteHubTOTPLoginParams struct {
	LastTotpTimestep    pgtype.Int8        `json:"last_totp_timestep"`
	HubUserDid          pgtype.UUID        `json:"hub_user_did"`
	HubLoginChallengeID pgtype.UUID        `json:"hub_login_challenge_id"`
	SessionTokenHash    []byte             `json:"session_token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	Remembered          bool               `json:"remembered"`
	TenantID            string             `json:"tenant_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
}

type CompleteHubTOTPLoginRow struct {
	HubSessionID    pgtype.UUID        `json:"hub_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
}

func (q *Queries) CompleteHubTOTPLogin(ctx context.Context, arg CompleteHubTOTPLoginParams) (CompleteHubTOTPLoginRow, error) {
	row := q.db.QueryRow(ctx, completeHubTOTPLogin,
		arg.LastTotpTimestep,
		arg.HubUserDid,
		arg.HubLoginChallengeID,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.Remembered,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CompleteHubTOTPLoginRow
	err := row.Scan(
		&i.HubSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
	)
	return i, err
}

const createHubLoginChallenge = `-- name: CreateHubLoginChallenge :one
WITH eligible_user AS (
    SELECT u.hub_user_did
    FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.password_hash = $2
      AND u.hub_user_state = 'active'
      AND u.totp_enabled
    FOR UPDATE
), challenge AS (
    INSERT INTO vetchium.hub_login_challenges (
        hub_user_did,
        token_hash,
        remembered,
        expires_at
    )
    SELECT
        hub_user_did,
        $3,
        $4,
        $5
    FROM eligible_user
    ON CONFLICT (hub_user_did) WHERE active DO UPDATE
    SET token_hash = EXCLUDED.token_hash,
        remembered = EXCLUDED.remembered,
        created_at = now(),
        expires_at = EXCLUDED.expires_at,
        consumed_at = NULL
    RETURNING hub_login_challenge_id, hub_user_did, expires_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $6,
        'hub.login-challenge.created',
        'hub_login_challenge',
        hub_login_challenge_id::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        jsonb_build_object('remembered', $4::boolean)
    FROM challenge
)
SELECT hub_login_challenge_id, expires_at FROM challenge
`

type CreateHubLoginChallengeParams struct {
	HubUserDid           pgtype.UUID        `json:"hub_user_did"`
	VerifiedPasswordHash string             `json:"verified_password_hash"`
	TokenHash            []byte             `json:"token_hash"`
	Remembered           bool               `json:"remembered"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	TenantID             string             `json:"tenant_id"`
}

type CreateHubLoginChallengeRow struct {
	HubLoginChallengeID pgtype.UUID        `json:"hub_login_challenge_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHubLoginChallenge(ctx context.Context, arg CreateHubLoginChallengeParams) (CreateHubLoginChallengeRow, error) {
	row := q.db.QueryRow(ctx, createHubLoginChallenge,
		arg.HubUserDid,
		arg.VerifiedPasswordHash,
		arg.TokenHash,
		arg.Remembered,
		arg.ExpiresAt,
		arg.TenantID,
	)
	var i CreateHubLoginChallengeRow
	err := row.Scan(&i.HubLoginChallengeID, &i.ExpiresAt)
	return i, err
}

const createHubSession = `-- name: CreateHubSession :one
WITH updated_user AS (
    UPDATE vetchium.hub_users AS u
    SET last_login_at = now(),
        updated_at = now()
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
      AND u.password_hash = $2
      AND NOT u.totp_enabled
    RETURNING u.hub_user_did
), session AS (
    INSERT INTO vetchium.hub_sessions (
        session_token_hash,
        hub_user_did,
        expires_at,
        authenticated_at,
        remembered
    )
    SELECT
        $3,
        hub_user_did,
        $4,
        now(),
        $5
    FROM updated_user
    RETURNING hub_session_id, hub_user_did, created_at, expires_at,
        authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $6,
        'hub.session.created',
        'hub_session',
        hub_session_id::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        jsonb_build_object('remembered', $5::boolean)
    FROM session
)
SELECT hub_session_id, created_at, expires_at, authenticated_at
FROM session
`

type CreateHubSessionParams struct {
	HubUserDid           pgtype.UUID        `json:"hub_user_did"`
	VerifiedPasswordHash string             `json:"verified_password_hash"`
	SessionTokenHash     []byte             `json:"session_token_hash"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Remembered           bool               `json:"remembered"`
	TenantID             string             `json:"tenant_id"`
}

type CreateHubSessionRow struct {
	HubSessionID    pgtype.UUID        `json:"hub_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
}

func (q *Queries) CreateHubSession(ctx context.Context, arg CreateHubSessionParams) (CreateHubSessionRow, error) {
	row := q.db.QueryRow(ctx, createHubSession,
		arg.HubUserDid,
		arg.VerifiedPasswordHash,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.Remembered,
		arg.TenantID,
	)
	var i CreateHubSessionRow
	err := row.Scan(
		&i.HubSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
	)
	return i, err
}

const deleteHubSessionByTokenHash = `-- name: DeleteHubSessionByTokenHash :exec
WITH deleted AS (
    DELETE FROM vetchium.hub_sessions
    WHERE session_token_hash = $1
    RETURNING hub_session_id, hub_user_did
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $2,
        'hub.session.revoked',
        'hub_session',
        hub_session_id::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        jsonb_build_object('reason', 'logout')
    FROM deleted
    RETURNING audit_event_id
)
SELECT 1 FROM audit
`

type DeleteHubSessionByTokenHashParams struct {
	SessionTokenHash []byte `json:"session_token_hash"`
	TenantID         string `json:"tenant_id"`
}

func (q *Queries) DeleteHubSessionByTokenHash(ctx context.Context, arg DeleteHubSessionByTokenHashParams) error {
	_, err := q.db.Exec(ctx, deleteHubSessionByTokenHash, arg.SessionTokenHash, arg.TenantID)
	return err
}

const getHubLoginChallenge = `-- name: GetHubLoginChallenge :one
SELECT
    c.hub_login_challenge_id,
    c.hub_user_did,
    c.remembered,
    u.totp_secret_ciphertext,
    u.preferred_language,
    u.resident_country,
    u.handle
FROM vetchium.hub_login_challenges AS c
JOIN vetchium.hub_users AS u USING (hub_user_did)
WHERE c.token_hash = $1
  AND c.active
  AND c.consumed_at IS NULL
  AND c.expires_at > now()
  AND u.hub_user_state = 'active'
  AND u.totp_enabled
FOR UPDATE OF c
`

type GetHubLoginChallengeRow struct {
	HubLoginChallengeID  pgtype.UUID `json:"hub_login_challenge_id"`
	HubUserDid           pgtype.UUID `json:"hub_user_did"`
	Remembered           bool        `json:"remembered"`
	TotpSecretCiphertext []byte      `json:"totp_secret_ciphertext"`
	PreferredLanguage    string      `json:"preferred_language"`
	ResidentCountry      string      `json:"resident_country"`
	Handle               string      `json:"handle"`
}

func (q *Queries) GetHubLoginChallenge(ctx context.Context, tokenHash []byte) (GetHubLoginChallengeRow, error) {
	row := q.db.QueryRow(ctx, getHubLoginChallenge, tokenHash)
	var i GetHubLoginChallengeRow
	err := row.Scan(
		&i.HubLoginChallengeID,
		&i.HubUserDid,
		&i.Remembered,
		&i.TotpSecretCiphertext,
		&i.PreferredLanguage,
		&i.ResidentCountry,
		&i.Handle,
	)
	return i, err
}

const getHubPasswordForReauthentication = `-- name: GetHubPasswordForReauthentication :one
SELECT u.password_hash
FROM vetchium.hub_sessions AS s
JOIN vetchium.hub_users AS u USING (hub_user_did)
WHERE s.hub_session_id = $1
  AND s.hub_user_did = $2
  AND s.expires_at > now()
  AND u.hub_user_state = 'active'
`

type GetHubPasswordForReauthenticationParams struct {
	HubSessionID pgtype.UUID `json:"hub_session_id"`
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
}

func (q *Queries) GetHubPasswordForReauthentication(ctx context.Context, arg GetHubPasswordForReauthenticationParams) (string, error) {
	row := q.db.QueryRow(ctx, getHubPasswordForReauthentication, arg.HubSessionID, arg.HubUserDid)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getHubUserForLogin = `-- name: GetHubUserForLogin :one
SELECT
    hub_user_did,
    handle,
    email_address,
    password_hash,
    hub_user_state,
    totp_enabled,
    totp_secret_ciphertext,
    preferred_language,
    resident_country
FROM vetchium.hub_users
WHERE email_address = $1
`

type GetHubUserForLoginRow struct {
	HubUserDid           pgtype.UUID          `json:"hub_user_did"`
	Handle               string               `json:"handle"`
	EmailAddress         string               `json:"email_address"`
	PasswordHash         string               `json:"password_hash"`
	HubUserState         VetchiumHubUserState `json:"hub_user_state"`
	TotpEnabled          bool                 `json:"totp_enabled"`
	TotpSecretCiphertext []byte               `json:"totp_secret_ciphertext"`
	PreferredLanguage    string               `json:"preferred_language"`
	ResidentCountry      string               `json:"resident_country"`
}

func (q *Queries) GetHubUserForLogin(ctx context.Context, emailAddress string) (GetHubUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getHubUserForLogin, emailAddress)
	var i GetHubUserForLoginRow
	err := row.Scan(
		&i.HubUserDid,
		&i.Handle,
		&i.EmailAddress,
		&i.PasswordHash,
		&i.HubUserState,
		&i.TotpEnabled,
		&i.TotpSecretCiphertext,
		&i.PreferredLanguage,
		&i.ResidentCountry,
	)
	return i, err
}

const reauthenticateHubSession = `-- name: ReauthenticateHubSession :one
WITH updated AS (
    UPDATE vetchium.hub_sessions AS s
    SET authenticated_at = now()
    FROM vetchium.hub_users AS u
    WHERE s.hub_session_id = $1
      AND s.hub_user_did = $2
      AND s.expires_at > now()
      AND u.hub_user_did = s.hub_user_did
      AND u.hub_user_state = 'active'
      AND u.password_hash = $3
    RETURNING s.hub_session_id, s.hub_user_did, s.authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'hub.session.reauthenticated',
        'hub_session',
        hub_session_id::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        jsonb_build_object('authentication_refreshed', true)
    FROM updated
)
SELECT authenticated_at FROM updated
`

type ReauthenticateHubSessionParams struct {
	HubSessionID         pgtype.UUID `json:"hub_session_id"`
	HubUserDid           pgtype.UUID `json:"hub_user_did"`
	VerifiedPasswordHash string      `json:"verified_password_hash"`
	TenantID             string      `json:"tenant_id"`
}

func (q *Queries) ReauthenticateHubSession(ctx context.Context, arg ReauthenticateHubSessionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, reauthenticateHubSession,
		arg.HubSessionID,
		arg.HubUserDid,
		arg.VerifiedPasswordHash,
		arg.TenantID,
	)
	var authenticated_at pgtype.Timestamptz
	err := row.Scan(&authenticated_at)
	return authenticated_at, err
}

const resolveHubLoginChallengeUser = `-- name: ResolveHubLoginChallengeUser :one
SELECT hub_user_did
FROM vetchium.hub_login_challenges
WHERE token_hash = $1
  AND active
  AND consumed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) ResolveHubLoginChallengeUser(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveHubLoginChallengeUser, tokenHash)
	var hub_user_did pgtype.UUID
	err := row.Scan(&hub_user_did)
	return hub_user_did, err
}
