// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueHubSubscriptions = `-- name: ClaimDueHubSubscriptions :many
SELECT
    hub_user_did,
    hub_plan_oid,
    subscription_billing_interval,
    subscription_anchor_at,
    subscription_period_start,
    subscription_period_end,
    scheduled_hub_plan_oid,
    scheduled_billing_interval
FROM vetchium.hub_users
WHERE subscription_period_end <= $1
  AND hub_user_did <> ALL (
      COALESCE($2::uuid[], '{}')
  )
ORDER BY subscription_period_end, hub_user_did
LIMIT $3
FOR NO KEY UPDATE SKIP LOCKED
`

type ClaimDueHubSubscriptionsParams struct {
	At                 pgtype.Timestamptz `json:"at"`
	SkippedHubUserDids []pgtype.UUID      `json:"skipped_hub_user_dids"`
	BatchSize          int32              `json:"batch_size"`
}

type ClaimDueHubSubscriptionsRow struct {
	HubUserDid                  pgtype.UUID                    `json:"hub_user_did"`
	HubPlanOid                  string                         `json:"hub_plan_oid"`
	SubscriptionBillingInterval NullVetchiumHubBillingInterval `json:"subscription_billing_interval"`
	SubscriptionAnchorAt        pgtype.Timestamptz             `json:"subscription_anchor_at"`
	SubscriptionPeriodStart     pgtype.Timestamptz             `json:"subscription_period_start"`
	SubscriptionPeriodEnd       pgtype.Timestamptz             `json:"subscription_period_end"`
	ScheduledHubPlanOid         pgtype.Text                    `json:"scheduled_hub_plan_oid"`
	ScheduledBillingInterval    NullVetchiumHubBillingInterval `json:"scheduled_billing_interval"`
}

// The worker passes a non-nil, possibly empty, exclusion slice. pgx v5
// encodes a nil Go slice as SQL NULL, and `x <> ALL (NULL)` is never true, so
// the COALESCE also guards a caller that does pass nil.
func (q *Queries) ClaimDueHubSubscriptions(ctx context.Context, arg ClaimDueHubSubscriptionsParams) ([]ClaimDueHubSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, claimDueHubSubscriptions, arg.At, arg.SkippedHubUserDids, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueHubSubscriptionsRow
	for rows.Next() {
		var i ClaimDueHubSubscriptionsRow
		if err := rows.Scan(
			&i.HubUserDid,
			&i.HubPlanOid,
			&i.SubscriptionBillingInterval,
			&i.SubscriptionAnchorAt,
			&i.SubscriptionPeriodStart,
			&i.SubscriptionPeriodEnd,
			&i.ScheduledHubPlanOid,
			&i.ScheduledBillingInterval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHubMySubscription = `-- name: GetHubMySubscription :one
SELECT
    u.hub_plan_oid,
    u.subscription_billing_interval,
    u.subscription_anchor_at,
    u.subscription_period_start,
    u.subscription_period_end,
    u.scheduled_hub_plan_oid,
    u.scheduled_billing_interval
FROM vetchium.hub_sessions AS s
JOIN vetchium.hub_users AS u USING (hub_user_did)
WHERE s.hub_session_id = $1
  AND u.hub_user_did = $2
  AND s.expires_at > now()
  AND u.hub_user_state = 'active'
`

type GetHubMySubscriptionParams struct {
	HubSessionID pgtype.UUID `json:"hub_session_id"`
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
}

type GetHubMySubscriptionRow struct {
	HubPlanOid                  string                         `json:"hub_plan_oid"`
	SubscriptionBillingInterval NullVetchiumHubBillingInterval `json:"subscription_billing_interval"`
	SubscriptionAnchorAt        pgtype.Timestamptz             `json:"subscription_anchor_at"`
	SubscriptionPeriodStart     pgtype.Timestamptz             `json:"subscription_period_start"`
	SubscriptionPeriodEnd       pgtype.Timestamptz             `json:"subscription_period_end"`
	ScheduledHubPlanOid         pgtype.Text                    `json:"scheduled_hub_plan_oid"`
	ScheduledBillingInterval    NullVetchiumHubBillingInterval `json:"scheduled_billing_interval"`
}

func (q *Queries) GetHubMySubscription(ctx context.Context, arg GetHubMySubscriptionParams) (GetHubMySubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getHubMySubscription, arg.HubSessionID, arg.HubUserDid)
	var i GetHubMySubscriptionRow
	err := row.Scan(
		&i.HubPlanOid,
		&i.SubscriptionBillingInterval,
		&i.SubscriptionAnchorAt,
		&i.SubscriptionPeriodStart,
		&i.SubscriptionPeriodEnd,
		&i.ScheduledHubPlanOid,
		&i.ScheduledBillingInterval,
	)
	return i, err
}

const lockHubSubscriptionForChange = `-- name: LockHubSubscriptionForChange :one
SELECT
    hub_plan_oid,
    subscription_billing_interval,
    subscription_anchor_at,
    subscription_period_start,
    subscription_period_end,
    scheduled_hub_plan_oid,
    scheduled_billing_interval
FROM vetchium.hub_users
WHERE hub_user_did = $1
  AND hub_user_state = 'active'
FOR NO KEY UPDATE
`

type LockHubSubscriptionForChangeRow struct {
	HubPlanOid                  string                         `json:"hub_plan_oid"`
	SubscriptionBillingInterval NullVetchiumHubBillingInterval `json:"subscription_billing_interval"`
	SubscriptionAnchorAt        pgtype.Timestamptz             `json:"subscription_anchor_at"`
	SubscriptionPeriodStart     pgtype.Timestamptz             `json:"subscription_period_start"`
	SubscriptionPeriodEnd       pgtype.Timestamptz             `json:"subscription_period_end"`
	ScheduledHubPlanOid         pgtype.Text                    `json:"scheduled_hub_plan_oid"`
	ScheduledBillingInterval    NullVetchiumHubBillingInterval `json:"scheduled_billing_interval"`
}

func (q *Queries) LockHubSubscriptionForChange(ctx context.Context, hubUserDid pgtype.UUID) (LockHubSubscriptionForChangeRow, error) {
	row := q.db.QueryRow(ctx, lockHubSubscriptionForChange, hubUserDid)
	var i LockHubSubscriptionForChangeRow
	err := row.Scan(
		&i.HubPlanOid,
		&i.SubscriptionBillingInterval,
		&i.SubscriptionAnchorAt,
		&i.SubscriptionPeriodStart,
		&i.SubscriptionPeriodEnd,
		&i.ScheduledHubPlanOid,
		&i.ScheduledBillingInterval,
	)
	return i, err
}

const saveHubSubscriptionStates = `-- name: SaveHubSubscriptionStates :one
WITH states AS (
    SELECT
        (elem ->> 'hub_user_did')::uuid AS hub_user_did,
        (elem ->> 'hub_plan_oid')::text AS hub_plan_oid,
        (elem ->> 'subscription_billing_interval')::
            vetchium.hub_billing_interval AS subscription_billing_interval,
        (elem ->> 'subscription_anchor_at')::timestamptz
            AS subscription_anchor_at,
        (elem ->> 'subscription_period_start')::timestamptz
            AS subscription_period_start,
        (elem ->> 'subscription_period_end')::timestamptz
            AS subscription_period_end,
        (elem ->> 'scheduled_hub_plan_oid')::text AS scheduled_hub_plan_oid,
        (elem ->> 'scheduled_billing_interval')::
            vetchium.hub_billing_interval AS scheduled_billing_interval
    FROM jsonb_array_elements($1::jsonb) AS elem
), updated AS (
    UPDATE vetchium.hub_users AS u
    SET hub_plan_oid = states.hub_plan_oid,
        subscription_billing_interval = states.subscription_billing_interval,
        subscription_anchor_at = states.subscription_anchor_at,
        subscription_period_start = states.subscription_period_start,
        subscription_period_end = states.subscription_period_end,
        scheduled_hub_plan_oid = states.scheduled_hub_plan_oid,
        scheduled_billing_interval = states.scheduled_billing_interval,
        updated_at = now()
    FROM states
    WHERE u.hub_user_did = states.hub_user_did
    RETURNING u.hub_user_did
), events AS (
    SELECT
        (elem ->> 'hub_user_did')::uuid AS hub_user_did,
        (elem ->> 'action')::text AS action,
        (elem ->> 'actor_type')::text AS actor_type,
        (elem ->> 'actor_id')::text AS actor_id,
        (elem -> 'payload')::jsonb AS payload
    FROM jsonb_array_elements($2::jsonb) AS elem
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id,
        action,
        entity_type,
        entity_id,
        actor_type,
        actor_id,
        source,
        idempotency_key,
        payload
    )
    SELECT
        $3,
        events.action,
        'hub_subscription',
        events.hub_user_did::text,
        events.actor_type,
        events.actor_id,
        $4,
        $5,
        events.payload
    FROM events
    JOIN updated ON updated.hub_user_did = events.hub_user_did
    RETURNING audit_event_id, entity_id
)
SELECT
    (SELECT count(*) FROM updated)::bigint AS updated_count,
    (SELECT count(*) FROM audit)::bigint AS audited_count,
    (SELECT count(DISTINCT entity_id) FROM audit)::bigint
        AS audited_user_count
`

type SaveHubSubscriptionStatesParams struct {
	States         []byte      `json:"states"`
	Events         []byte      `json:"events"`
	TenantID       string      `json:"tenant_id"`
	Source         string      `json:"source"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

type SaveHubSubscriptionStatesRow struct {
	UpdatedCount     int64 `json:"updated_count"`
	AuditedCount     int64 `json:"audited_count"`
	AuditedUserCount int64 `json:"audited_user_count"`
}

// The single write statement shared by the set-plan handler and the worker.
// A jsonb array with explicit `->>`/`->` field extraction lets one statement
// serve both a single-row caller and a batch caller; sqlc cannot resolve
// columns from jsonb_to_recordset's column-definition-list form, and parallel
// unnest arrays would read worse with eight state columns.
func (q *Queries) SaveHubSubscriptionStates(ctx context.Context, arg SaveHubSubscriptionStatesParams) (SaveHubSubscriptionStatesRow, error) {
	row := q.db.QueryRow(ctx, saveHubSubscriptionStates,
		arg.States,
		arg.Events,
		arg.TenantID,
		arg.Source,
		arg.IdempotencyKey,
	)
	var i SaveHubSubscriptionStatesRow
	err := row.Scan(&i.UpdatedCount, &i.AuditedCount, &i.AuditedUserCount)
	return i, err
}
