// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_profile_details.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHubLanguageAbility = `-- name: AddHubLanguageAbility :one
WITH owner AS (
    SELECT u.hub_user_did FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), inserted AS (
    INSERT INTO vetchium.hub_language_abilities (
        hub_user_did, ability, language_tag
    )
    SELECT owner.hub_user_did, $2, $3
    FROM owner
    WHERE (SELECT count(*) FROM vetchium.hub_language_abilities AS existing
           WHERE existing.hub_user_did = owner.hub_user_did
             AND existing.ability = $2) < 25
    ON CONFLICT DO NOTHING
    RETURNING hub_user_did, ability, language_tag, created_at
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM inserted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $4, 'hub.profile.language-added',
        'hub_language_ability', ability::text || ':' || language_tag,
        'hub_user',
        hub_user_did::text, 'hub-api', $5,
        jsonb_build_object(
            'schema_version', 1,
            'ability', ability, 'language_tag', language_tag,
            'profile_version', versioned.profile_version
        )
    FROM inserted CROSS JOIN versioned
)
SELECT inserted.hub_user_did, inserted.ability, inserted.language_tag,
    inserted.created_at, versioned.profile_version
FROM inserted CROSS JOIN versioned
`

type AddHubLanguageAbilityParams struct {
	HubUserDid     pgtype.UUID                    `json:"hub_user_did"`
	Ability        VetchiumHubLanguageAbilityKind `json:"ability"`
	LanguageTag    string                         `json:"language_tag"`
	TenantID       string                         `json:"tenant_id"`
	IdempotencyKey pgtype.Text                    `json:"idempotency_key"`
}

type AddHubLanguageAbilityRow struct {
	HubUserDid     pgtype.UUID                    `json:"hub_user_did"`
	Ability        VetchiumHubLanguageAbilityKind `json:"ability"`
	LanguageTag    string                         `json:"language_tag"`
	CreatedAt      pgtype.Timestamptz             `json:"created_at"`
	ProfileVersion int64                          `json:"profile_version"`
}

func (q *Queries) AddHubLanguageAbility(ctx context.Context, arg AddHubLanguageAbilityParams) (AddHubLanguageAbilityRow, error) {
	row := q.db.QueryRow(ctx, addHubLanguageAbility,
		arg.HubUserDid,
		arg.Ability,
		arg.LanguageTag,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i AddHubLanguageAbilityRow
	err := row.Scan(
		&i.HubUserDid,
		&i.Ability,
		&i.LanguageTag,
		&i.CreatedAt,
		&i.ProfileVersion,
	)
	return i, err
}

const createHubCertification = `-- name: CreateHubCertification :one
WITH owner AS (
    SELECT u.hub_user_did FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), inserted AS (
    INSERT INTO vetchium.hub_certifications (
        certification_id, hub_user_did, title, credential_url
    )
    SELECT $2, owner.hub_user_did,
        $3, $4
    FROM owner
    WHERE (SELECT count(*) FROM vetchium.hub_certifications AS existing
           WHERE existing.hub_user_did = owner.hub_user_did) < 50
    RETURNING certification_id, hub_user_did, title, credential_url,
        created_at, updated_at
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM inserted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $5, 'hub.profile.certification-created',
        'hub_certification', certification_id::text, 'hub_user',
        hub_user_did::text, 'hub-api', $6,
        jsonb_build_object(
            'schema_version', 1, 'profile_version', versioned.profile_version,
            'title', title,
            'credential_url_sha256', encode(
                sha256(convert_to(credential_url, 'UTF8')), 'hex'
            )
        )
    FROM inserted CROSS JOIN versioned
)
SELECT inserted.certification_id, inserted.hub_user_did, inserted.title,
    inserted.credential_url, inserted.created_at, inserted.updated_at,
    versioned.profile_version
FROM inserted CROSS JOIN versioned
`

type CreateHubCertificationParams struct {
	HubUserDid      pgtype.UUID `json:"hub_user_did"`
	CertificationID pgtype.UUID `json:"certification_id"`
	Title           string      `json:"title"`
	CredentialUrl   string      `json:"credential_url"`
	TenantID        string      `json:"tenant_id"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
}

type CreateHubCertificationRow struct {
	CertificationID pgtype.UUID        `json:"certification_id"`
	HubUserDid      pgtype.UUID        `json:"hub_user_did"`
	Title           string             `json:"title"`
	CredentialUrl   string             `json:"credential_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProfileVersion  int64              `json:"profile_version"`
}

func (q *Queries) CreateHubCertification(ctx context.Context, arg CreateHubCertificationParams) (CreateHubCertificationRow, error) {
	row := q.db.QueryRow(ctx, createHubCertification,
		arg.HubUserDid,
		arg.CertificationID,
		arg.Title,
		arg.CredentialUrl,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CreateHubCertificationRow
	err := row.Scan(
		&i.CertificationID,
		&i.HubUserDid,
		&i.Title,
		&i.CredentialUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileVersion,
	)
	return i, err
}

const createHubEducationalQualification = `-- name: CreateHubEducationalQualification :one
WITH owner AS (
    SELECT u.hub_user_did FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), inserted AS (
    INSERT INTO vetchium.hub_educational_qualifications (
        educational_qualification_id, hub_user_did, institution_domain,
        degree, title, supporting_text, start_month, end_month
    )
    SELECT $2, owner.hub_user_did,
        $3, $4, $5,
        $6, $7, $8
    FROM owner
    WHERE ($7::date IS NULL OR
            $7::date <= date_trunc('month', now())::date)
      AND ($8::date IS NULL OR
            $8::date <= date_trunc('month', now())::date)
      AND (SELECT count(*)
           FROM vetchium.hub_educational_qualifications AS existing
           WHERE existing.hub_user_did = owner.hub_user_did) < 30
    RETURNING educational_qualification_id, hub_user_did,
        institution_domain, degree, title, supporting_text, start_month,
        end_month, created_at, updated_at
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM inserted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $9, 'hub.profile.education-created',
        'hub_educational_qualification', educational_qualification_id::text,
        'hub_user', hub_user_did::text, 'hub-api', $10,
        jsonb_build_object(
            'schema_version', 1, 'profile_version', versioned.profile_version,
            'institution_domain', institution_domain, 'degree', degree,
            'title', title, 'start_month', start_month,
            'end_month', end_month,
            'has_supporting_text', supporting_text IS NOT NULL
        )
    FROM inserted CROSS JOIN versioned
)
SELECT inserted.educational_qualification_id, inserted.hub_user_did,
    inserted.institution_domain, inserted.degree, inserted.title,
    inserted.supporting_text, inserted.start_month, inserted.end_month,
    inserted.created_at, inserted.updated_at, versioned.profile_version
FROM inserted CROSS JOIN versioned
`

type CreateHubEducationalQualificationParams struct {
	HubUserDid                 pgtype.UUID `json:"hub_user_did"`
	EducationalQualificationID pgtype.UUID `json:"educational_qualification_id"`
	InstitutionDomain          string      `json:"institution_domain"`
	Degree                     string      `json:"degree"`
	Title                      pgtype.Text `json:"title"`
	SupportingText             pgtype.Text `json:"supporting_text"`
	StartMonth                 pgtype.Date `json:"start_month"`
	EndMonth                   pgtype.Date `json:"end_month"`
	TenantID                   string      `json:"tenant_id"`
	IdempotencyKey             pgtype.Text `json:"idempotency_key"`
}

type CreateHubEducationalQualificationRow struct {
	EducationalQualificationID pgtype.UUID        `json:"educational_qualification_id"`
	HubUserDid                 pgtype.UUID        `json:"hub_user_did"`
	InstitutionDomain          string             `json:"institution_domain"`
	Degree                     string             `json:"degree"`
	Title                      pgtype.Text        `json:"title"`
	SupportingText             pgtype.Text        `json:"supporting_text"`
	StartMonth                 pgtype.Date        `json:"start_month"`
	EndMonth                   pgtype.Date        `json:"end_month"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ProfileVersion             int64              `json:"profile_version"`
}

func (q *Queries) CreateHubEducationalQualification(ctx context.Context, arg CreateHubEducationalQualificationParams) (CreateHubEducationalQualificationRow, error) {
	row := q.db.QueryRow(ctx, createHubEducationalQualification,
		arg.HubUserDid,
		arg.EducationalQualificationID,
		arg.InstitutionDomain,
		arg.Degree,
		arg.Title,
		arg.SupportingText,
		arg.StartMonth,
		arg.EndMonth,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CreateHubEducationalQualificationRow
	err := row.Scan(
		&i.EducationalQualificationID,
		&i.HubUserDid,
		&i.InstitutionDomain,
		&i.Degree,
		&i.Title,
		&i.SupportingText,
		&i.StartMonth,
		&i.EndMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileVersion,
	)
	return i, err
}

const createHubWorkExperience = `-- name: CreateHubWorkExperience :one
WITH owner AS (
    SELECT u.hub_user_did
    FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), inserted AS (
    INSERT INTO vetchium.hub_work_experiences (
        work_experience_id, hub_user_did, employer_domain, job_title,
        start_month, end_month, location, description
    )
    SELECT
        $2, owner.hub_user_did,
        $3, $4, $5,
        $6, $7, $8
    FROM owner
    WHERE $5::date <= date_trunc('month', now())::date
      AND ($6::date IS NULL OR
        $6::date <= date_trunc('month', now())::date)
      AND (SELECT count(*) FROM vetchium.hub_work_experiences AS existing
           WHERE existing.hub_user_did = owner.hub_user_did) < 50
    RETURNING work_experience_id, hub_user_did, employer_domain, job_title,
        start_month, end_month, location, description, created_at, updated_at
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM inserted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $9, 'hub.profile.work-experience-created',
        'hub_work_experience', work_experience_id::text, 'hub_user',
        hub_user_did::text, 'hub-api', $10,
        jsonb_build_object(
            'schema_version', 1, 'profile_version', versioned.profile_version,
            'employer_domain', employer_domain, 'job_title', job_title,
            'start_month', start_month, 'end_month', end_month,
            'location', location, 'has_description', description IS NOT NULL
        )
    FROM inserted CROSS JOIN versioned
)
SELECT inserted.work_experience_id, inserted.hub_user_did,
    inserted.employer_domain, inserted.job_title, inserted.start_month,
    inserted.end_month, inserted.location, inserted.description,
    inserted.created_at, inserted.updated_at, versioned.profile_version
FROM inserted CROSS JOIN versioned
`

type CreateHubWorkExperienceParams struct {
	HubUserDid       pgtype.UUID `json:"hub_user_did"`
	WorkExperienceID pgtype.UUID `json:"work_experience_id"`
	EmployerDomain   string      `json:"employer_domain"`
	JobTitle         string      `json:"job_title"`
	StartMonth       pgtype.Date `json:"start_month"`
	EndMonth         pgtype.Date `json:"end_month"`
	Location         pgtype.Text `json:"location"`
	Description      pgtype.Text `json:"description"`
	TenantID         string      `json:"tenant_id"`
	IdempotencyKey   pgtype.Text `json:"idempotency_key"`
}

type CreateHubWorkExperienceRow struct {
	WorkExperienceID pgtype.UUID        `json:"work_experience_id"`
	HubUserDid       pgtype.UUID        `json:"hub_user_did"`
	EmployerDomain   string             `json:"employer_domain"`
	JobTitle         string             `json:"job_title"`
	StartMonth       pgtype.Date        `json:"start_month"`
	EndMonth         pgtype.Date        `json:"end_month"`
	Location         pgtype.Text        `json:"location"`
	Description      pgtype.Text        `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProfileVersion   int64              `json:"profile_version"`
}

func (q *Queries) CreateHubWorkExperience(ctx context.Context, arg CreateHubWorkExperienceParams) (CreateHubWorkExperienceRow, error) {
	row := q.db.QueryRow(ctx, createHubWorkExperience,
		arg.HubUserDid,
		arg.WorkExperienceID,
		arg.EmployerDomain,
		arg.JobTitle,
		arg.StartMonth,
		arg.EndMonth,
		arg.Location,
		arg.Description,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CreateHubWorkExperienceRow
	err := row.Scan(
		&i.WorkExperienceID,
		&i.HubUserDid,
		&i.EmployerDomain,
		&i.JobTitle,
		&i.StartMonth,
		&i.EndMonth,
		&i.Location,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileVersion,
	)
	return i, err
}

const deleteHubCertification = `-- name: DeleteHubCertification :one
WITH deleted AS (
    DELETE FROM vetchium.hub_certifications AS c
    WHERE c.certification_id = $1
      AND c.hub_user_did = $2
      AND EXISTS (
          SELECT 1 FROM vetchium.hub_users AS u
          WHERE u.hub_user_did = $2
            AND u.hub_user_state = 'active'
          FOR UPDATE
      )
    RETURNING certification_id, hub_user_did, title, credential_url
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM deleted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $3, 'hub.profile.certification-deleted',
        'hub_certification', certification_id::text, 'hub_user',
        hub_user_did::text, 'hub-api', $4,
        jsonb_build_object(
            'schema_version', 1, 'profile_version', versioned.profile_version,
            'title', title,
            'credential_url_sha256', encode(
                sha256(convert_to(credential_url, 'UTF8')), 'hex'
            )
        )
    FROM deleted CROSS JOIN versioned
)
SELECT deleted.certification_id, versioned.profile_version
FROM deleted CROSS JOIN versioned
`

type DeleteHubCertificationParams struct {
	CertificationID pgtype.UUID `json:"certification_id"`
	HubUserDid      pgtype.UUID `json:"hub_user_did"`
	TenantID        string      `json:"tenant_id"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
}

type DeleteHubCertificationRow struct {
	CertificationID pgtype.UUID `json:"certification_id"`
	ProfileVersion  int64       `json:"profile_version"`
}

func (q *Queries) DeleteHubCertification(ctx context.Context, arg DeleteHubCertificationParams) (DeleteHubCertificationRow, error) {
	row := q.db.QueryRow(ctx, deleteHubCertification,
		arg.CertificationID,
		arg.HubUserDid,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i DeleteHubCertificationRow
	err := row.Scan(&i.CertificationID, &i.ProfileVersion)
	return i, err
}

const deleteHubEducationalQualification = `-- name: DeleteHubEducationalQualification :one
WITH deleted AS (
    DELETE FROM vetchium.hub_educational_qualifications AS e
    WHERE e.educational_qualification_id =
            $1
      AND e.hub_user_did = $2
      AND EXISTS (
          SELECT 1 FROM vetchium.hub_users AS u
          WHERE u.hub_user_did = $2
            AND u.hub_user_state = 'active'
          FOR UPDATE
      )
    RETURNING educational_qualification_id, hub_user_did,
        institution_domain, degree, title, supporting_text, start_month,
        end_month
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM deleted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $3, 'hub.profile.education-deleted',
        'hub_educational_qualification', educational_qualification_id::text,
        'hub_user', hub_user_did::text, 'hub-api', $4,
        jsonb_build_object(
            'schema_version', 1, 'profile_version', versioned.profile_version,
            'institution_domain', institution_domain, 'degree', degree,
            'title', title, 'start_month', start_month,
            'end_month', end_month,
            'had_supporting_text', supporting_text IS NOT NULL
        )
    FROM deleted CROSS JOIN versioned
)
SELECT deleted.educational_qualification_id, versioned.profile_version
FROM deleted CROSS JOIN versioned
`

type DeleteHubEducationalQualificationParams struct {
	EducationalQualificationID pgtype.UUID `json:"educational_qualification_id"`
	HubUserDid                 pgtype.UUID `json:"hub_user_did"`
	TenantID                   string      `json:"tenant_id"`
	IdempotencyKey             pgtype.Text `json:"idempotency_key"`
}

type DeleteHubEducationalQualificationRow struct {
	EducationalQualificationID pgtype.UUID `json:"educational_qualification_id"`
	ProfileVersion             int64       `json:"profile_version"`
}

func (q *Queries) DeleteHubEducationalQualification(ctx context.Context, arg DeleteHubEducationalQualificationParams) (DeleteHubEducationalQualificationRow, error) {
	row := q.db.QueryRow(ctx, deleteHubEducationalQualification,
		arg.EducationalQualificationID,
		arg.HubUserDid,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i DeleteHubEducationalQualificationRow
	err := row.Scan(&i.EducationalQualificationID, &i.ProfileVersion)
	return i, err
}

const deleteHubLanguageAbility = `-- name: DeleteHubLanguageAbility :one
WITH deleted AS (
    DELETE FROM vetchium.hub_language_abilities AS l
    WHERE l.hub_user_did = $1
      AND l.ability = $2
      AND l.language_tag = $3
      AND EXISTS (
          SELECT 1 FROM vetchium.hub_users AS u
          WHERE u.hub_user_did = $1
            AND u.hub_user_state = 'active'
          FOR UPDATE
      )
    RETURNING hub_user_did, ability, language_tag
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM deleted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $4, 'hub.profile.language-deleted',
        'hub_language_ability', ability::text || ':' || language_tag,
        'hub_user',
        hub_user_did::text, 'hub-api', $5,
        jsonb_build_object(
            'schema_version', 1,
            'ability', ability, 'language_tag', language_tag,
            'profile_version', versioned.profile_version
        )
    FROM deleted CROSS JOIN versioned
)
SELECT deleted.language_tag, versioned.profile_version
FROM deleted CROSS JOIN versioned
`

type DeleteHubLanguageAbilityParams struct {
	HubUserDid     pgtype.UUID                    `json:"hub_user_did"`
	Ability        VetchiumHubLanguageAbilityKind `json:"ability"`
	LanguageTag    string                         `json:"language_tag"`
	TenantID       string                         `json:"tenant_id"`
	IdempotencyKey pgtype.Text                    `json:"idempotency_key"`
}

type DeleteHubLanguageAbilityRow struct {
	LanguageTag    string `json:"language_tag"`
	ProfileVersion int64  `json:"profile_version"`
}

func (q *Queries) DeleteHubLanguageAbility(ctx context.Context, arg DeleteHubLanguageAbilityParams) (DeleteHubLanguageAbilityRow, error) {
	row := q.db.QueryRow(ctx, deleteHubLanguageAbility,
		arg.HubUserDid,
		arg.Ability,
		arg.LanguageTag,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i DeleteHubLanguageAbilityRow
	err := row.Scan(&i.LanguageTag, &i.ProfileVersion)
	return i, err
}

const deleteHubWorkExperience = `-- name: DeleteHubWorkExperience :one
WITH deleted AS (
    DELETE FROM vetchium.hub_work_experiences AS w
    WHERE w.work_experience_id = $1
      AND w.hub_user_did = $2
      AND EXISTS (
          SELECT 1 FROM vetchium.hub_users AS u
          WHERE u.hub_user_did = $2
            AND u.hub_user_state = 'active'
          FOR UPDATE
      )
    RETURNING work_experience_id, hub_user_did, employer_domain, job_title,
        start_month, end_month, location, description
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM deleted)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $3, 'hub.profile.work-experience-deleted',
        'hub_work_experience', work_experience_id::text, 'hub_user',
        hub_user_did::text, 'hub-api', $4,
        jsonb_build_object(
            'schema_version', 1, 'profile_version', versioned.profile_version,
            'employer_domain', employer_domain, 'job_title', job_title,
            'start_month', start_month, 'end_month', end_month,
            'location', location, 'had_description', description IS NOT NULL
        )
    FROM deleted CROSS JOIN versioned
)
SELECT deleted.work_experience_id, versioned.profile_version
FROM deleted CROSS JOIN versioned
`

type DeleteHubWorkExperienceParams struct {
	WorkExperienceID pgtype.UUID `json:"work_experience_id"`
	HubUserDid       pgtype.UUID `json:"hub_user_did"`
	TenantID         string      `json:"tenant_id"`
	IdempotencyKey   pgtype.Text `json:"idempotency_key"`
}

type DeleteHubWorkExperienceRow struct {
	WorkExperienceID pgtype.UUID `json:"work_experience_id"`
	ProfileVersion   int64       `json:"profile_version"`
}

func (q *Queries) DeleteHubWorkExperience(ctx context.Context, arg DeleteHubWorkExperienceParams) (DeleteHubWorkExperienceRow, error) {
	row := q.db.QueryRow(ctx, deleteHubWorkExperience,
		arg.WorkExperienceID,
		arg.HubUserDid,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i DeleteHubWorkExperienceRow
	err := row.Scan(&i.WorkExperienceID, &i.ProfileVersion)
	return i, err
}

const getHubAliasState = `-- name: GetHubAliasState :one
SELECT u.profile_alias, u.alias_last_changed_at
FROM vetchium.hub_sessions AS s
JOIN vetchium.hub_users AS u USING (hub_user_did)
WHERE s.hub_session_id = $1
  AND u.hub_user_did = $2
  AND s.expires_at > now()
  AND u.hub_user_state = 'active'
`

type GetHubAliasStateParams struct {
	HubSessionID pgtype.UUID `json:"hub_session_id"`
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
}

type GetHubAliasStateRow struct {
	ProfileAlias       pgtype.Text        `json:"profile_alias"`
	AliasLastChangedAt pgtype.Timestamptz `json:"alias_last_changed_at"`
}

func (q *Queries) GetHubAliasState(ctx context.Context, arg GetHubAliasStateParams) (GetHubAliasStateRow, error) {
	row := q.db.QueryRow(ctx, getHubAliasState, arg.HubSessionID, arg.HubUserDid)
	var i GetHubAliasStateRow
	err := row.Scan(&i.ProfileAlias, &i.AliasLastChangedAt)
	return i, err
}

const getHubProfileViewer = `-- name: GetHubProfileViewer :one
SELECT handle
FROM vetchium.hub_users
WHERE hub_user_did = $1
  AND hub_user_state = 'active'
`

func (q *Queries) GetHubProfileViewer(ctx context.Context, hubUserDid pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getHubProfileViewer, hubUserDid)
	var handle string
	err := row.Scan(&handle)
	return handle, err
}

const getHubPublicProfile = `-- name: GetHubPublicProfile :one
SELECT
    u.display_name,
    u.handle,
    u.profile_alias,
    u.resident_country,
    u.biography,
    u.profile_version,
    picture.object_id AS profile_picture_object_id,
    COALESCE(picture.format::text, '')::text AS profile_picture_format,
    COALESCE(work.items, '[]'::jsonb) AS work_experiences,
    COALESCE(certifications.items, '[]'::jsonb) AS certifications,
    COALESCE(languages.items, '[]'::jsonb) AS language_abilities,
    COALESCE(education.items, '[]'::jsonb) AS educational_qualifications
FROM vetchium.hub_users AS u
LEFT JOIN LATERAL (
    SELECT p.object_id, p.format
    FROM vetchium.hub_profile_picture_objects AS p
    WHERE p.hub_user_did = u.hub_user_did AND p.state = 'active'
) AS picture ON true
LEFT JOIN LATERAL (
    SELECT jsonb_agg(
        jsonb_build_object(
            'id', w.work_experience_id,
            'employer_domain', w.employer_domain,
            'job_title', w.job_title,
            'start_month', to_char(w.start_month, 'YYYY-MM'),
            'end_month', to_char(w.end_month, 'YYYY-MM'),
            'location', w.location,
            'description', w.description
        ) ORDER BY (w.end_month IS NULL) DESC, w.start_month DESC,
            w.work_experience_id
    ) AS items
    FROM vetchium.hub_work_experiences AS w
    WHERE w.hub_user_did = u.hub_user_did
) AS work ON true
LEFT JOIN LATERAL (
    SELECT jsonb_agg(
        jsonb_build_object(
            'id', c.certification_id,
            'title', c.title,
            'credential_url', c.credential_url
        ) ORDER BY c.created_at DESC, c.certification_id
    ) AS items
    FROM vetchium.hub_certifications AS c
    WHERE c.hub_user_did = u.hub_user_did
) AS certifications ON true
LEFT JOIN LATERAL (
    SELECT jsonb_agg(
        jsonb_build_object('ability', l.ability, 'language_tag', l.language_tag)
        ORDER BY l.ability, l.language_tag
    ) AS items
    FROM vetchium.hub_language_abilities AS l
    WHERE l.hub_user_did = u.hub_user_did
) AS languages ON true
LEFT JOIN LATERAL (
    SELECT jsonb_agg(
        jsonb_build_object(
            'id', e.educational_qualification_id,
            'institution_domain', e.institution_domain,
            'degree', e.degree,
            'title', e.title,
            'supporting_text', e.supporting_text,
            'start_month', to_char(e.start_month, 'YYYY-MM'),
            'end_month', to_char(e.end_month, 'YYYY-MM')
        ) ORDER BY
            CASE
                WHEN e.start_month IS NOT NULL AND e.end_month IS NULL THEN 0
                WHEN e.start_month IS NOT NULL THEN 1
                WHEN e.end_month IS NOT NULL THEN 2
                ELSE 3
            END,
            e.start_month DESC NULLS LAST,
            e.end_month DESC NULLS LAST,
            e.educational_qualification_id
    ) AS items
    FROM vetchium.hub_educational_qualifications AS e
    WHERE e.hub_user_did = u.hub_user_did
) AS education ON true
WHERE u.hub_user_did = $1
  AND u.hub_user_state = 'active'
`

type GetHubPublicProfileRow struct {
	DisplayName               string      `json:"display_name"`
	Handle                    string      `json:"handle"`
	ProfileAlias              pgtype.Text `json:"profile_alias"`
	ResidentCountry           string      `json:"resident_country"`
	Biography                 pgtype.Text `json:"biography"`
	ProfileVersion            int64       `json:"profile_version"`
	ProfilePictureObjectID    pgtype.UUID `json:"profile_picture_object_id"`
	ProfilePictureFormat      string      `json:"profile_picture_format"`
	WorkExperiences           []byte      `json:"work_experiences"`
	Certifications            []byte      `json:"certifications"`
	LanguageAbilities         []byte      `json:"language_abilities"`
	EducationalQualifications []byte      `json:"educational_qualifications"`
}

func (q *Queries) GetHubPublicProfile(ctx context.Context, hubUserDid pgtype.UUID) (GetHubPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getHubPublicProfile, hubUserDid)
	var i GetHubPublicProfileRow
	err := row.Scan(
		&i.DisplayName,
		&i.Handle,
		&i.ProfileAlias,
		&i.ResidentCountry,
		&i.Biography,
		&i.ProfileVersion,
		&i.ProfilePictureObjectID,
		&i.ProfilePictureFormat,
		&i.WorkExperiences,
		&i.Certifications,
		&i.LanguageAbilities,
		&i.EducationalQualifications,
	)
	return i, err
}

const setHubPublicProfile = `-- name: SetHubPublicProfile :one
WITH previous AS (
    SELECT u.hub_user_did, u.display_name, u.biography
    FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), updated AS (
    UPDATE vetchium.hub_users AS u
    SET display_name = $2,
        biography = $3,
        profile_version = u.profile_version + 1,
        updated_at = now()
    FROM previous
    WHERE u.hub_user_did = previous.hub_user_did
      AND (u.display_name, u.biography) IS DISTINCT FROM
          ($2, $3)
    RETURNING u.hub_user_did, u.display_name, u.biography, u.profile_version,
        previous.display_name AS previous_display_name,
        previous.biography AS previous_biography
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $4,
        'hub.profile.public-fields-set',
        'hub_user',
        hub_user_did::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        $5,
        jsonb_build_object(
            'schema_version', 1,
            'previous_display_name', previous_display_name,
            'display_name', display_name,
            'biography_changed', biography IS DISTINCT FROM previous_biography
        )
    FROM updated
)
SELECT hub_user_did, display_name, biography, profile_version FROM updated
`

type SetHubPublicProfileParams struct {
	HubUserDid     pgtype.UUID `json:"hub_user_did"`
	DisplayName    string      `json:"display_name"`
	Biography      pgtype.Text `json:"biography"`
	TenantID       string      `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

type SetHubPublicProfileRow struct {
	HubUserDid     pgtype.UUID `json:"hub_user_did"`
	DisplayName    string      `json:"display_name"`
	Biography      pgtype.Text `json:"biography"`
	ProfileVersion int64       `json:"profile_version"`
}

func (q *Queries) SetHubPublicProfile(ctx context.Context, arg SetHubPublicProfileParams) (SetHubPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, setHubPublicProfile,
		arg.HubUserDid,
		arg.DisplayName,
		arg.Biography,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i SetHubPublicProfileRow
	err := row.Scan(
		&i.HubUserDid,
		&i.DisplayName,
		&i.Biography,
		&i.ProfileVersion,
	)
	return i, err
}

const updateHubCertification = `-- name: UpdateHubCertification :one
WITH owner AS (
    SELECT u.hub_user_did FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), previous AS (
    SELECT c.certification_id, c.title, c.credential_url
    FROM vetchium.hub_certifications AS c
    JOIN owner USING (hub_user_did)
    WHERE c.certification_id = $2
    FOR UPDATE OF c
), updated AS (
    UPDATE vetchium.hub_certifications AS c
    SET title = $3, credential_url = $4,
        updated_at = now()
    FROM previous
    WHERE c.certification_id = previous.certification_id
    RETURNING c.certification_id, c.hub_user_did, c.title, c.credential_url,
        c.created_at, c.updated_at,
        jsonb_build_object(
            'title', previous.title IS DISTINCT FROM c.title,
            'credential_url', previous.credential_url
                IS DISTINCT FROM c.credential_url
        ) AS field_changes
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM updated)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $5, 'hub.profile.certification-updated',
        'hub_certification', certification_id::text, 'hub_user',
        hub_user_did::text, 'hub-api', $6,
        jsonb_build_object(
            'schema_version', 1, 'field_changes', updated.field_changes,
            'profile_version', versioned.profile_version
        )
    FROM updated CROSS JOIN versioned
)
SELECT updated.certification_id, updated.hub_user_did, updated.title,
    updated.credential_url, updated.created_at, updated.updated_at,
    versioned.profile_version
FROM updated CROSS JOIN versioned
`

type UpdateHubCertificationParams struct {
	HubUserDid      pgtype.UUID `json:"hub_user_did"`
	CertificationID pgtype.UUID `json:"certification_id"`
	Title           string      `json:"title"`
	CredentialUrl   string      `json:"credential_url"`
	TenantID        string      `json:"tenant_id"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
}

type UpdateHubCertificationRow struct {
	CertificationID pgtype.UUID        `json:"certification_id"`
	HubUserDid      pgtype.UUID        `json:"hub_user_did"`
	Title           string             `json:"title"`
	CredentialUrl   string             `json:"credential_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProfileVersion  int64              `json:"profile_version"`
}

func (q *Queries) UpdateHubCertification(ctx context.Context, arg UpdateHubCertificationParams) (UpdateHubCertificationRow, error) {
	row := q.db.QueryRow(ctx, updateHubCertification,
		arg.HubUserDid,
		arg.CertificationID,
		arg.Title,
		arg.CredentialUrl,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i UpdateHubCertificationRow
	err := row.Scan(
		&i.CertificationID,
		&i.HubUserDid,
		&i.Title,
		&i.CredentialUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileVersion,
	)
	return i, err
}

const updateHubEducationalQualification = `-- name: UpdateHubEducationalQualification :one
WITH owner AS (
    SELECT u.hub_user_did FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), previous AS (
    SELECT e.educational_qualification_id, e.institution_domain, e.degree,
        e.title, e.supporting_text, e.start_month, e.end_month
    FROM vetchium.hub_educational_qualifications AS e
    JOIN owner USING (hub_user_did)
    WHERE e.educational_qualification_id =
        $2
    FOR UPDATE OF e
), updated AS (
    UPDATE vetchium.hub_educational_qualifications AS e
    SET institution_domain = $3,
        degree = $4, title = $5,
        supporting_text = $6,
        start_month = $7, end_month = $8,
        updated_at = now()
    FROM previous
    WHERE e.educational_qualification_id =
            previous.educational_qualification_id
      AND ($7::date IS NULL OR
            $7::date <= date_trunc('month', now())::date)
      AND ($8::date IS NULL OR
            $8::date <= date_trunc('month', now())::date)
    RETURNING e.educational_qualification_id, e.hub_user_did,
        e.institution_domain, e.degree, e.title, e.supporting_text,
        e.start_month, e.end_month, e.created_at, e.updated_at,
        jsonb_build_object(
            'institution_domain', previous.institution_domain
                IS DISTINCT FROM e.institution_domain,
            'degree', previous.degree IS DISTINCT FROM e.degree,
            'title', previous.title IS DISTINCT FROM e.title,
            'supporting_text', previous.supporting_text
                IS DISTINCT FROM e.supporting_text,
            'start_month', previous.start_month IS DISTINCT FROM e.start_month,
            'end_month', previous.end_month IS DISTINCT FROM e.end_month
        ) AS field_changes
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM updated)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $9, 'hub.profile.education-updated',
        'hub_educational_qualification', educational_qualification_id::text,
        'hub_user', hub_user_did::text, 'hub-api', $10,
        jsonb_build_object(
            'schema_version', 1, 'field_changes', updated.field_changes,
            'profile_version', versioned.profile_version
        )
    FROM updated CROSS JOIN versioned
)
SELECT updated.educational_qualification_id, updated.hub_user_did,
    updated.institution_domain, updated.degree, updated.title,
    updated.supporting_text, updated.start_month, updated.end_month,
    updated.created_at, updated.updated_at, versioned.profile_version
FROM updated CROSS JOIN versioned
`

type UpdateHubEducationalQualificationParams struct {
	HubUserDid                 pgtype.UUID `json:"hub_user_did"`
	EducationalQualificationID pgtype.UUID `json:"educational_qualification_id"`
	InstitutionDomain          string      `json:"institution_domain"`
	Degree                     string      `json:"degree"`
	Title                      pgtype.Text `json:"title"`
	SupportingText             pgtype.Text `json:"supporting_text"`
	StartMonth                 pgtype.Date `json:"start_month"`
	EndMonth                   pgtype.Date `json:"end_month"`
	TenantID                   string      `json:"tenant_id"`
	IdempotencyKey             pgtype.Text `json:"idempotency_key"`
}

type UpdateHubEducationalQualificationRow struct {
	EducationalQualificationID pgtype.UUID        `json:"educational_qualification_id"`
	HubUserDid                 pgtype.UUID        `json:"hub_user_did"`
	InstitutionDomain          string             `json:"institution_domain"`
	Degree                     string             `json:"degree"`
	Title                      pgtype.Text        `json:"title"`
	SupportingText             pgtype.Text        `json:"supporting_text"`
	StartMonth                 pgtype.Date        `json:"start_month"`
	EndMonth                   pgtype.Date        `json:"end_month"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ProfileVersion             int64              `json:"profile_version"`
}

func (q *Queries) UpdateHubEducationalQualification(ctx context.Context, arg UpdateHubEducationalQualificationParams) (UpdateHubEducationalQualificationRow, error) {
	row := q.db.QueryRow(ctx, updateHubEducationalQualification,
		arg.HubUserDid,
		arg.EducationalQualificationID,
		arg.InstitutionDomain,
		arg.Degree,
		arg.Title,
		arg.SupportingText,
		arg.StartMonth,
		arg.EndMonth,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i UpdateHubEducationalQualificationRow
	err := row.Scan(
		&i.EducationalQualificationID,
		&i.HubUserDid,
		&i.InstitutionDomain,
		&i.Degree,
		&i.Title,
		&i.SupportingText,
		&i.StartMonth,
		&i.EndMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileVersion,
	)
	return i, err
}

const updateHubWorkExperience = `-- name: UpdateHubWorkExperience :one
WITH owner AS (
    SELECT u.hub_user_did
    FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    FOR UPDATE
), previous AS (
    SELECT w.work_experience_id, w.employer_domain, w.job_title,
        w.start_month, w.end_month, w.location, w.description
    FROM vetchium.hub_work_experiences AS w
    JOIN owner USING (hub_user_did)
    WHERE w.work_experience_id = $2
    FOR UPDATE OF w
), updated AS (
    UPDATE vetchium.hub_work_experiences AS w
    SET employer_domain = $3,
        job_title = $4,
        start_month = $5,
        end_month = $6,
        location = $7,
        description = $8,
        updated_at = now()
    FROM previous
    WHERE w.work_experience_id = previous.work_experience_id
      AND $5::date <= date_trunc('month', now())::date
      AND ($6::date IS NULL OR
        $6::date <= date_trunc('month', now())::date)
    RETURNING w.work_experience_id, w.hub_user_did, w.employer_domain,
        w.job_title, w.start_month, w.end_month, w.location, w.description,
        w.created_at, w.updated_at,
        jsonb_build_object(
            'employer_domain', previous.employer_domain
                IS DISTINCT FROM w.employer_domain,
            'job_title', previous.job_title IS DISTINCT FROM w.job_title,
            'start_month', previous.start_month IS DISTINCT FROM w.start_month,
            'end_month', previous.end_month IS DISTINCT FROM w.end_month,
            'location', previous.location IS DISTINCT FROM w.location,
            'description', previous.description IS DISTINCT FROM w.description
        ) AS field_changes
), versioned AS (
    UPDATE vetchium.hub_users AS u
    SET profile_version = profile_version + 1, updated_at = now()
    WHERE u.hub_user_did = (SELECT hub_user_did FROM updated)
    RETURNING profile_version
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT $9, 'hub.profile.work-experience-updated',
        'hub_work_experience', work_experience_id::text, 'hub_user',
        hub_user_did::text, 'hub-api', $10,
        jsonb_build_object(
            'schema_version', 1, 'field_changes', updated.field_changes,
            'profile_version', versioned.profile_version
        )
    FROM updated CROSS JOIN versioned
)
SELECT updated.work_experience_id, updated.hub_user_did,
    updated.employer_domain, updated.job_title, updated.start_month,
    updated.end_month, updated.location, updated.description,
    updated.created_at, updated.updated_at, versioned.profile_version
FROM updated CROSS JOIN versioned
`

type UpdateHubWorkExperienceParams struct {
	HubUserDid       pgtype.UUID `json:"hub_user_did"`
	WorkExperienceID pgtype.UUID `json:"work_experience_id"`
	EmployerDomain   string      `json:"employer_domain"`
	JobTitle         string      `json:"job_title"`
	StartMonth       pgtype.Date `json:"start_month"`
	EndMonth         pgtype.Date `json:"end_month"`
	Location         pgtype.Text `json:"location"`
	Description      pgtype.Text `json:"description"`
	TenantID         string      `json:"tenant_id"`
	IdempotencyKey   pgtype.Text `json:"idempotency_key"`
}

type UpdateHubWorkExperienceRow struct {
	WorkExperienceID pgtype.UUID        `json:"work_experience_id"`
	HubUserDid       pgtype.UUID        `json:"hub_user_did"`
	EmployerDomain   string             `json:"employer_domain"`
	JobTitle         string             `json:"job_title"`
	StartMonth       pgtype.Date        `json:"start_month"`
	EndMonth         pgtype.Date        `json:"end_month"`
	Location         pgtype.Text        `json:"location"`
	Description      pgtype.Text        `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProfileVersion   int64              `json:"profile_version"`
}

func (q *Queries) UpdateHubWorkExperience(ctx context.Context, arg UpdateHubWorkExperienceParams) (UpdateHubWorkExperienceRow, error) {
	row := q.db.QueryRow(ctx, updateHubWorkExperience,
		arg.HubUserDid,
		arg.WorkExperienceID,
		arg.EmployerDomain,
		arg.JobTitle,
		arg.StartMonth,
		arg.EndMonth,
		arg.Location,
		arg.Description,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i UpdateHubWorkExperienceRow
	err := row.Scan(
		&i.WorkExperienceID,
		&i.HubUserDid,
		&i.EmployerDomain,
		&i.JobTitle,
		&i.StartMonth,
		&i.EndMonth,
		&i.Location,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileVersion,
	)
	return i, err
}
