// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_totp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeHubRecoveryCodeLogin = `-- name: CompleteHubRecoveryCodeLogin :one
WITH eligible_challenge AS (
    SELECT c.hub_login_challenge_id, c.hub_user_did
    FROM vetchium.hub_login_challenges AS c
    WHERE c.hub_login_challenge_id = $1
      AND c.hub_user_did = $2
      AND c.active
      AND c.consumed_at IS NULL
      AND c.expires_at > now()
    FOR UPDATE
), consumed_code AS (
    UPDATE vetchium.hub_totp_recovery_codes AS r
    SET consumed_at = now()
    WHERE r.hub_user_did IN (
          SELECT hub_user_did FROM eligible_challenge
      )
      AND r.code_hash = $3
      AND r.consumed_at IS NULL
    RETURNING r.hub_user_did, r.code_hash
), consumed_challenge AS (
    UPDATE vetchium.hub_login_challenges AS c
    SET consumed_at = now(),
        active = false
    FROM consumed_code AS code
    WHERE c.hub_login_challenge_id = $1
      AND c.hub_user_did = code.hub_user_did
      AND c.active
      AND c.consumed_at IS NULL
      AND c.expires_at > now()
    RETURNING c.hub_user_did
), updated_user AS (
    UPDATE vetchium.hub_users AS u
    SET last_login_at = now(),
        updated_at = now()
    FROM consumed_challenge AS challenge
    WHERE u.hub_user_did = challenge.hub_user_did
    RETURNING u.hub_user_did
), session AS (
    INSERT INTO vetchium.hub_sessions (
        session_token_hash,
        hub_user_did,
        expires_at,
        authenticated_at,
        remembered
    )
    SELECT
        $4,
        hub_user_did,
        $5,
        now(),
        $6
    FROM updated_user
    RETURNING hub_session_id, hub_user_did, created_at, expires_at,
        authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $7,
        'hub.session.created-with-recovery-code',
        'hub_session',
        hub_session_id::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        $8,
        jsonb_build_object('remembered', $6::boolean)
    FROM session
)
SELECT
    session.hub_session_id,
    session.created_at,
    session.expires_at,
    session.authenticated_at,
    count(c.code_hash) FILTER (
        WHERE c.consumed_at IS NULL
          AND c.code_hash <> (SELECT code_hash FROM consumed_code)
    )::bigint AS remaining_codes
FROM session
JOIN vetchium.hub_totp_recovery_codes AS c USING (hub_user_did)
GROUP BY session.hub_session_id, session.created_at, session.expires_at,
    session.authenticated_at
`

type CompleteHubRecoveryCodeLoginParams struct {
	HubLoginChallengeID pgtype.UUID        `json:"hub_login_challenge_id"`
	HubUserDid          pgtype.UUID        `json:"hub_user_did"`
	RecoveryCodeHash    []byte             `json:"recovery_code_hash"`
	SessionTokenHash    []byte             `json:"session_token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	Remembered          bool               `json:"remembered"`
	TenantID            string             `json:"tenant_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
}

type CompleteHubRecoveryCodeLoginRow struct {
	HubSessionID    pgtype.UUID        `json:"hub_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
	RemainingCodes  int64              `json:"remaining_codes"`
}

func (q *Queries) CompleteHubRecoveryCodeLogin(ctx context.Context, arg CompleteHubRecoveryCodeLoginParams) (CompleteHubRecoveryCodeLoginRow, error) {
	row := q.db.QueryRow(ctx, completeHubRecoveryCodeLogin,
		arg.HubLoginChallengeID,
		arg.HubUserDid,
		arg.RecoveryCodeHash,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.Remembered,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CompleteHubRecoveryCodeLoginRow
	err := row.Scan(
		&i.HubSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
		&i.RemainingCodes,
	)
	return i, err
}

const confirmHubTOTPEnrollment = `-- name: ConfirmHubTOTPEnrollment :one
WITH enrollment AS (
    SELECT e.hub_totp_enrollment_id, e.hub_user_did
    FROM vetchium.hub_totp_enrollments AS e
    WHERE e.hub_totp_enrollment_id = $1
      AND e.hub_user_did = $2
      AND e.active
      AND e.consumed_at IS NULL
      AND e.expires_at > now()
    FOR UPDATE
), updated AS (
    UPDATE vetchium.hub_users
    SET totp_secret_ciphertext = $3,
        totp_enabled = true,
        totp_last_timestep = $4,
        updated_at = now()
    WHERE hub_user_did IN (SELECT hub_user_did FROM enrollment)
      AND NOT totp_enabled
    RETURNING hub_user_did
), consumed AS (
    UPDATE vetchium.hub_totp_enrollments
    SET consumed_at = now(),
        active = false
    WHERE hub_totp_enrollment_id IN (
        SELECT hub_totp_enrollment_id FROM enrollment
    )
      AND EXISTS (SELECT 1 FROM updated)
    RETURNING hub_user_did
), deleted_codes AS (
    DELETE FROM vetchium.hub_totp_recovery_codes
    WHERE hub_user_did IN (SELECT hub_user_did FROM updated)
), inserted_codes AS (
    INSERT INTO vetchium.hub_totp_recovery_codes (
        hub_user_did,
        code_hash
    )
    SELECT u.hub_user_did, code_hash
    FROM updated AS u
    CROSS JOIN unnest($5::bytea[]) AS code_hash
    RETURNING hub_user_did
), sessions AS (
    DELETE FROM vetchium.hub_sessions
    WHERE hub_user_did IN (SELECT hub_user_did FROM updated)
      AND hub_session_id <> $6
), challenges AS (
    UPDATE vetchium.hub_login_challenges
    SET active = false
    WHERE hub_user_did IN (SELECT hub_user_did FROM updated)
      AND active
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $7,
        'hub.totp.enabled',
        'hub_user',
        hub_user_did::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        $8,
        jsonb_build_object('recovery_codes_created', 10)
    FROM consumed
    WHERE (SELECT count(*) FROM inserted_codes) = 10
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS confirmed
`

type ConfirmHubTOTPEnrollmentParams struct {
	HubTotpEnrollmentID pgtype.UUID `json:"hub_totp_enrollment_id"`
	HubUserDid          pgtype.UUID `json:"hub_user_did"`
	SecretCiphertext    []byte      `json:"secret_ciphertext"`
	TotpTimestep        pgtype.Int8 `json:"totp_timestep"`
	RecoveryCodeHashes  [][]byte    `json:"recovery_code_hashes"`
	CurrentHubSessionID pgtype.UUID `json:"current_hub_session_id"`
	TenantID            string      `json:"tenant_id"`
	IdempotencyKey      pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) ConfirmHubTOTPEnrollment(ctx context.Context, arg ConfirmHubTOTPEnrollmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, confirmHubTOTPEnrollment,
		arg.HubTotpEnrollmentID,
		arg.HubUserDid,
		arg.SecretCiphertext,
		arg.TotpTimestep,
		arg.RecoveryCodeHashes,
		arg.CurrentHubSessionID,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var confirmed bool
	err := row.Scan(&confirmed)
	return confirmed, err
}

const createHubTOTPEnrollment = `-- name: CreateHubTOTPEnrollment :one
WITH eligible_user AS (
    SELECT u.hub_user_did
    FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
      AND NOT u.totp_enabled
), enrollment AS (
    INSERT INTO vetchium.hub_totp_enrollments (
        hub_user_did,
        token_hash,
        secret_ciphertext,
        expires_at
    )
    SELECT
        hub_user_did,
        $2,
        $3,
        $4
    FROM eligible_user
    ON CONFLICT (hub_user_did) WHERE active DO UPDATE
    SET token_hash = EXCLUDED.token_hash,
        secret_ciphertext = EXCLUDED.secret_ciphertext,
        created_at = now(),
        expires_at = EXCLUDED.expires_at,
        consumed_at = NULL
    RETURNING hub_totp_enrollment_id, hub_user_did, expires_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $5,
        'hub.totp-enrollment.started',
        'hub_totp_enrollment',
        hub_totp_enrollment_id::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        $6,
        jsonb_build_object('expires_at', expires_at)
    FROM enrollment
)
SELECT hub_totp_enrollment_id, expires_at FROM enrollment
`

type CreateHubTOTPEnrollmentParams struct {
	HubUserDid       pgtype.UUID        `json:"hub_user_did"`
	TokenHash        []byte             `json:"token_hash"`
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	TenantID         string             `json:"tenant_id"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
}

type CreateHubTOTPEnrollmentRow struct {
	HubTotpEnrollmentID pgtype.UUID        `json:"hub_totp_enrollment_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHubTOTPEnrollment(ctx context.Context, arg CreateHubTOTPEnrollmentParams) (CreateHubTOTPEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, createHubTOTPEnrollment,
		arg.HubUserDid,
		arg.TokenHash,
		arg.SecretCiphertext,
		arg.ExpiresAt,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CreateHubTOTPEnrollmentRow
	err := row.Scan(&i.HubTotpEnrollmentID, &i.ExpiresAt)
	return i, err
}

const disableHubTOTP = `-- name: DisableHubTOTP :one
WITH updated AS (
    UPDATE vetchium.hub_users AS u
    SET totp_secret_ciphertext = NULL,
        totp_enabled = false,
        totp_last_timestep = NULL,
        updated_at = now()
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
    RETURNING u.hub_user_did
), codes AS (
    DELETE FROM vetchium.hub_totp_recovery_codes
    WHERE hub_user_did IN (SELECT hub_user_did FROM updated)
), enrollments AS (
    UPDATE vetchium.hub_totp_enrollments
    SET active = false
    WHERE hub_user_did IN (SELECT hub_user_did FROM updated)
      AND active
), challenges AS (
    UPDATE vetchium.hub_login_challenges
    SET active = false
    WHERE hub_user_did IN (SELECT hub_user_did FROM updated)
      AND active
), sessions AS (
    DELETE FROM vetchium.hub_sessions
    WHERE hub_user_did IN (SELECT hub_user_did FROM updated)
      AND hub_session_id <> $2
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'hub.totp.disabled',
        'hub_user',
        hub_user_did::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        jsonb_build_object('other_sessions_revoked', true)
    FROM updated
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS disabled
`

type DisableHubTOTPParams struct {
	HubUserDid          pgtype.UUID `json:"hub_user_did"`
	CurrentHubSessionID pgtype.UUID `json:"current_hub_session_id"`
	TenantID            string      `json:"tenant_id"`
}

func (q *Queries) DisableHubTOTP(ctx context.Context, arg DisableHubTOTPParams) (bool, error) {
	row := q.db.QueryRow(ctx, disableHubTOTP, arg.HubUserDid, arg.CurrentHubSessionID, arg.TenantID)
	var disabled bool
	err := row.Scan(&disabled)
	return disabled, err
}

const getHubTOTPEnrollment = `-- name: GetHubTOTPEnrollment :one
SELECT
    e.hub_totp_enrollment_id,
    e.hub_user_did,
    e.secret_ciphertext
FROM vetchium.hub_totp_enrollments AS e
JOIN vetchium.hub_users AS u USING (hub_user_did)
WHERE e.token_hash = $1
  AND e.hub_user_did = $2
  AND e.active
  AND e.consumed_at IS NULL
  AND e.expires_at > now()
  AND u.hub_user_state = 'active'
  AND NOT u.totp_enabled
FOR UPDATE OF e
`

type GetHubTOTPEnrollmentParams struct {
	TokenHash  []byte      `json:"token_hash"`
	HubUserDid pgtype.UUID `json:"hub_user_did"`
}

type GetHubTOTPEnrollmentRow struct {
	HubTotpEnrollmentID pgtype.UUID `json:"hub_totp_enrollment_id"`
	HubUserDid          pgtype.UUID `json:"hub_user_did"`
	SecretCiphertext    []byte      `json:"secret_ciphertext"`
}

func (q *Queries) GetHubTOTPEnrollment(ctx context.Context, arg GetHubTOTPEnrollmentParams) (GetHubTOTPEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getHubTOTPEnrollment, arg.TokenHash, arg.HubUserDid)
	var i GetHubTOTPEnrollmentRow
	err := row.Scan(&i.HubTotpEnrollmentID, &i.HubUserDid, &i.SecretCiphertext)
	return i, err
}

const hubTOTPEnabled = `-- name: HubTOTPEnabled :one
SELECT totp_enabled
FROM vetchium.hub_users
WHERE hub_user_did = $1
  AND hub_user_state = 'active'
`

func (q *Queries) HubTOTPEnabled(ctx context.Context, hubUserDid pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hubTOTPEnabled, hubUserDid)
	var totp_enabled bool
	err := row.Scan(&totp_enabled)
	return totp_enabled, err
}

const regenerateHubTOTPRecoveryCodes = `-- name: RegenerateHubTOTPRecoveryCodes :one
WITH eligible_user AS (
    SELECT u.hub_user_did
    FROM vetchium.hub_users AS u
    WHERE u.hub_user_did = $1
      AND u.hub_user_state = 'active'
      AND u.totp_enabled
    FOR UPDATE
), deleted_codes AS (
    DELETE FROM vetchium.hub_totp_recovery_codes
    WHERE hub_user_did IN (SELECT hub_user_did FROM eligible_user)
), inserted_codes AS (
    INSERT INTO vetchium.hub_totp_recovery_codes (
        hub_user_did,
        code_hash
    )
    SELECT u.hub_user_did, code_hash
    FROM eligible_user AS u
    CROSS JOIN unnest($2::bytea[]) AS code_hash
    RETURNING hub_user_did
), sessions AS (
    DELETE FROM vetchium.hub_sessions
    WHERE hub_user_did IN (SELECT hub_user_did FROM eligible_user)
      AND hub_session_id <> $3
), challenges AS (
    UPDATE vetchium.hub_login_challenges
    SET active = false
    WHERE hub_user_did IN (SELECT hub_user_did FROM eligible_user)
      AND active
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $4,
        'hub.totp.recovery-codes-regenerated',
        'hub_user',
        hub_user_did::text,
        'hub_user',
        hub_user_did::text,
        'hub-api',
        $5,
        jsonb_build_object('recovery_codes_created', 10)
    FROM eligible_user
    WHERE (SELECT count(*) FROM inserted_codes) = 10
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS regenerated
`

type RegenerateHubTOTPRecoveryCodesParams struct {
	HubUserDid          pgtype.UUID `json:"hub_user_did"`
	RecoveryCodeHashes  [][]byte    `json:"recovery_code_hashes"`
	CurrentHubSessionID pgtype.UUID `json:"current_hub_session_id"`
	TenantID            string      `json:"tenant_id"`
	IdempotencyKey      pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) RegenerateHubTOTPRecoveryCodes(ctx context.Context, arg RegenerateHubTOTPRecoveryCodesParams) (bool, error) {
	row := q.db.QueryRow(ctx, regenerateHubTOTPRecoveryCodes,
		arg.HubUserDid,
		arg.RecoveryCodeHashes,
		arg.CurrentHubSessionID,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var regenerated bool
	err := row.Scan(&regenerated)
	return regenerated, err
}
