// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotency = `-- name: CompleteIdempotency :exec
UPDATE vetchium.idempotency_ledger
SET response_status = $4,
    response_ciphertext = $5
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
`

type CompleteIdempotencyParams struct {
	Operation          string      `json:"operation"`
	BindingID          string      `json:"binding_id"`
	IdempotencyKey     string      `json:"idempotency_key"`
	ResponseStatus     pgtype.Int4 `json:"response_status"`
	ResponseCiphertext []byte      `json:"response_ciphertext"`
}

func (q *Queries) CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotency,
		arg.Operation,
		arg.BindingID,
		arg.IdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseCiphertext,
	)
	return err
}

const createIdempotency = `-- name: CreateIdempotency :exec
INSERT INTO vetchium.idempotency_ledger (
    operation,
    binding_id,
    idempotency_key,
    request_digest,
    expires_at
)
VALUES ($1, $2, $3, $4, $5)
`

type CreateIdempotencyParams struct {
	Operation      string             `json:"operation"`
	BindingID      string             `json:"binding_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestDigest  []byte             `json:"request_digest"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIdempotency(ctx context.Context, arg CreateIdempotencyParams) error {
	_, err := q.db.Exec(ctx, createIdempotency,
		arg.Operation,
		arg.BindingID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :exec
DELETE FROM vetchium.idempotency_ledger
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
  AND expires_at <= now()
`

type DeleteExpiredIdempotencyParams struct {
	Operation      string `json:"operation"`
	BindingID      string `json:"binding_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) DeleteExpiredIdempotency(ctx context.Context, arg DeleteExpiredIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotency, arg.Operation, arg.BindingID, arg.IdempotencyKey)
	return err
}

const deleteIdempotency = `-- name: DeleteIdempotency :exec
DELETE FROM vetchium.idempotency_ledger
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
`

type DeleteIdempotencyParams struct {
	Operation      string `json:"operation"`
	BindingID      string `json:"binding_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) DeleteIdempotency(ctx context.Context, arg DeleteIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotency, arg.Operation, arg.BindingID, arg.IdempotencyKey)
	return err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT request_digest, response_status, response_ciphertext, expires_at
FROM vetchium.idempotency_ledger
WHERE operation = $1
  AND binding_id = $2
  AND idempotency_key = $3
  AND expires_at > now()
FOR UPDATE
`

type GetIdempotencyParams struct {
	Operation      string `json:"operation"`
	BindingID      string `json:"binding_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetIdempotencyRow struct {
	RequestDigest      []byte             `json:"request_digest"`
	ResponseStatus     pgtype.Int4        `json:"response_status"`
	ResponseCiphertext []byte             `json:"response_ciphertext"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (GetIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.Operation, arg.BindingID, arg.IdempotencyKey)
	var i GetIdempotencyRow
	err := row.Scan(
		&i.RequestDigest,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.ExpiresAt,
	)
	return i, err
}

const lockIdempotency = `-- name: LockIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockIdempotency(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockIdempotency, dollar_1)
	return err
}

const pruneExpiredIdempotency = `-- name: PruneExpiredIdempotency :execrows
WITH candidates AS MATERIALIZED (
    SELECT operation, binding_id, idempotency_key
    FROM vetchium.idempotency_ledger AS candidate
    WHERE expires_at <= now()
    ORDER BY expires_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1000
)
DELETE FROM vetchium.idempotency_ledger AS ledger
USING candidates
WHERE ledger.operation = candidates.operation
  AND ledger.binding_id = candidates.binding_id
  AND ledger.idempotency_key = candidates.idempotency_key
`

func (q *Queries) PruneExpiredIdempotency(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredIdempotency)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
