// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type VetchiumAdminUserState string

const (
	VetchiumAdminUserStateActive   VetchiumAdminUserState = "active"
	VetchiumAdminUserStateDisabled VetchiumAdminUserState = "disabled"
)

func (e *VetchiumAdminUserState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumAdminUserState(s)
	case string:
		*e = VetchiumAdminUserState(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumAdminUserState: %T", src)
	}
	return nil
}

type NullVetchiumAdminUserState struct {
	VetchiumAdminUserState VetchiumAdminUserState `json:"vetchium_admin_user_state"`
	Valid                  bool                   `json:"valid"` // Valid is true if VetchiumAdminUserState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumAdminUserState) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumAdminUserState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumAdminUserState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumAdminUserState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumAdminUserState), nil
}

type VetchiumFederationOperationState string

const (
	VetchiumFederationOperationStatePending   VetchiumFederationOperationState = "pending"
	VetchiumFederationOperationStateSucceeded VetchiumFederationOperationState = "succeeded"
	VetchiumFederationOperationStateFailed    VetchiumFederationOperationState = "failed"
)

func (e *VetchiumFederationOperationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumFederationOperationState(s)
	case string:
		*e = VetchiumFederationOperationState(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumFederationOperationState: %T", src)
	}
	return nil
}

type NullVetchiumFederationOperationState struct {
	VetchiumFederationOperationState VetchiumFederationOperationState `json:"vetchium_federation_operation_state"`
	Valid                            bool                             `json:"valid"` // Valid is true if VetchiumFederationOperationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumFederationOperationState) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumFederationOperationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumFederationOperationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumFederationOperationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumFederationOperationState), nil
}

type VetchiumHubBillingInterval string

const (
	VetchiumHubBillingIntervalMonth VetchiumHubBillingInterval = "month"
	VetchiumHubBillingIntervalYear  VetchiumHubBillingInterval = "year"
)

func (e *VetchiumHubBillingInterval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubBillingInterval(s)
	case string:
		*e = VetchiumHubBillingInterval(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubBillingInterval: %T", src)
	}
	return nil
}

type NullVetchiumHubBillingInterval struct {
	VetchiumHubBillingInterval VetchiumHubBillingInterval `json:"vetchium_hub_billing_interval"`
	Valid                      bool                       `json:"valid"` // Valid is true if VetchiumHubBillingInterval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubBillingInterval) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubBillingInterval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubBillingInterval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubBillingInterval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubBillingInterval), nil
}

type VetchiumHubLanguageAbilityKind string

const (
	VetchiumHubLanguageAbilityKindSpeaking VetchiumHubLanguageAbilityKind = "speaking"
	VetchiumHubLanguageAbilityKindReading  VetchiumHubLanguageAbilityKind = "reading"
	VetchiumHubLanguageAbilityKindWriting  VetchiumHubLanguageAbilityKind = "writing"
)

func (e *VetchiumHubLanguageAbilityKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubLanguageAbilityKind(s)
	case string:
		*e = VetchiumHubLanguageAbilityKind(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubLanguageAbilityKind: %T", src)
	}
	return nil
}

type NullVetchiumHubLanguageAbilityKind struct {
	VetchiumHubLanguageAbilityKind VetchiumHubLanguageAbilityKind `json:"vetchium_hub_language_ability_kind"`
	Valid                          bool                           `json:"valid"` // Valid is true if VetchiumHubLanguageAbilityKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubLanguageAbilityKind) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubLanguageAbilityKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubLanguageAbilityKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubLanguageAbilityKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubLanguageAbilityKind), nil
}

type VetchiumHubProfilePictureFormat string

const (
	VetchiumHubProfilePictureFormatJpeg VetchiumHubProfilePictureFormat = "jpeg"
	VetchiumHubProfilePictureFormatPng  VetchiumHubProfilePictureFormat = "png"
)

func (e *VetchiumHubProfilePictureFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubProfilePictureFormat(s)
	case string:
		*e = VetchiumHubProfilePictureFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubProfilePictureFormat: %T", src)
	}
	return nil
}

type NullVetchiumHubProfilePictureFormat struct {
	VetchiumHubProfilePictureFormat VetchiumHubProfilePictureFormat `json:"vetchium_hub_profile_picture_format"`
	Valid                           bool                            `json:"valid"` // Valid is true if VetchiumHubProfilePictureFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubProfilePictureFormat) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubProfilePictureFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubProfilePictureFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubProfilePictureFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubProfilePictureFormat), nil
}

type VetchiumHubProfilePictureState string

const (
	VetchiumHubProfilePictureStateUploading     VetchiumHubProfilePictureState = "uploading"
	VetchiumHubProfilePictureStateActive        VetchiumHubProfilePictureState = "active"
	VetchiumHubProfilePictureStatePendingDelete VetchiumHubProfilePictureState = "pending_delete"
)

func (e *VetchiumHubProfilePictureState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubProfilePictureState(s)
	case string:
		*e = VetchiumHubProfilePictureState(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubProfilePictureState: %T", src)
	}
	return nil
}

type NullVetchiumHubProfilePictureState struct {
	VetchiumHubProfilePictureState VetchiumHubProfilePictureState `json:"vetchium_hub_profile_picture_state"`
	Valid                          bool                           `json:"valid"` // Valid is true if VetchiumHubProfilePictureState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubProfilePictureState) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubProfilePictureState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubProfilePictureState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubProfilePictureState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubProfilePictureState), nil
}

type VetchiumHubSignupCompletionState string

const (
	VetchiumHubSignupCompletionStatePrepared     VetchiumHubSignupCompletionState = "prepared"
	VetchiumHubSignupCompletionStateReserved     VetchiumHubSignupCompletionState = "reserved"
	VetchiumHubSignupCompletionStateLocalCreated VetchiumHubSignupCompletionState = "local_created"
	VetchiumHubSignupCompletionStateCompleted    VetchiumHubSignupCompletionState = "completed"
	VetchiumHubSignupCompletionStateFailed       VetchiumHubSignupCompletionState = "failed"
)

func (e *VetchiumHubSignupCompletionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubSignupCompletionState(s)
	case string:
		*e = VetchiumHubSignupCompletionState(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubSignupCompletionState: %T", src)
	}
	return nil
}

type NullVetchiumHubSignupCompletionState struct {
	VetchiumHubSignupCompletionState VetchiumHubSignupCompletionState `json:"vetchium_hub_signup_completion_state"`
	Valid                            bool                             `json:"valid"` // Valid is true if VetchiumHubSignupCompletionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubSignupCompletionState) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubSignupCompletionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubSignupCompletionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubSignupCompletionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubSignupCompletionState), nil
}

type VetchiumHubSignupDomainState string

const (
	VetchiumHubSignupDomainStateActive   VetchiumHubSignupDomainState = "active"
	VetchiumHubSignupDomainStateDisabled VetchiumHubSignupDomainState = "disabled"
)

func (e *VetchiumHubSignupDomainState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubSignupDomainState(s)
	case string:
		*e = VetchiumHubSignupDomainState(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubSignupDomainState: %T", src)
	}
	return nil
}

type NullVetchiumHubSignupDomainState struct {
	VetchiumHubSignupDomainState VetchiumHubSignupDomainState `json:"vetchium_hub_signup_domain_state"`
	Valid                        bool                         `json:"valid"` // Valid is true if VetchiumHubSignupDomainState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubSignupDomainState) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubSignupDomainState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubSignupDomainState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubSignupDomainState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubSignupDomainState), nil
}

type VetchiumHubSubscriptionNoticeLead string

const (
	VetchiumHubSubscriptionNoticeLeadSevenDay VetchiumHubSubscriptionNoticeLead = "seven_day"
	VetchiumHubSubscriptionNoticeLeadOneDay   VetchiumHubSubscriptionNoticeLead = "one_day"
)

func (e *VetchiumHubSubscriptionNoticeLead) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubSubscriptionNoticeLead(s)
	case string:
		*e = VetchiumHubSubscriptionNoticeLead(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubSubscriptionNoticeLead: %T", src)
	}
	return nil
}

type NullVetchiumHubSubscriptionNoticeLead struct {
	VetchiumHubSubscriptionNoticeLead VetchiumHubSubscriptionNoticeLead `json:"vetchium_hub_subscription_notice_lead"`
	Valid                             bool                              `json:"valid"` // Valid is true if VetchiumHubSubscriptionNoticeLead is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubSubscriptionNoticeLead) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubSubscriptionNoticeLead, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubSubscriptionNoticeLead.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubSubscriptionNoticeLead) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubSubscriptionNoticeLead), nil
}

type VetchiumHubSubscriptionSource string

const (
	VetchiumHubSubscriptionSourceSimulated VetchiumHubSubscriptionSource = "simulated"
)

func (e *VetchiumHubSubscriptionSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubSubscriptionSource(s)
	case string:
		*e = VetchiumHubSubscriptionSource(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubSubscriptionSource: %T", src)
	}
	return nil
}

type NullVetchiumHubSubscriptionSource struct {
	VetchiumHubSubscriptionSource VetchiumHubSubscriptionSource `json:"vetchium_hub_subscription_source"`
	Valid                         bool                          `json:"valid"` // Valid is true if VetchiumHubSubscriptionSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubSubscriptionSource) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubSubscriptionSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubSubscriptionSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubSubscriptionSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubSubscriptionSource), nil
}

type VetchiumHubUserState string

const (
	VetchiumHubUserStateProvisioning VetchiumHubUserState = "provisioning"
	VetchiumHubUserStateActive       VetchiumHubUserState = "active"
	VetchiumHubUserStateDisabled     VetchiumHubUserState = "disabled"
)

func (e *VetchiumHubUserState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VetchiumHubUserState(s)
	case string:
		*e = VetchiumHubUserState(s)
	default:
		return fmt.Errorf("unsupported scan type for VetchiumHubUserState: %T", src)
	}
	return nil
}

type NullVetchiumHubUserState struct {
	VetchiumHubUserState VetchiumHubUserState `json:"vetchium_hub_user_state"`
	Valid                bool                 `json:"valid"` // Valid is true if VetchiumHubUserState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVetchiumHubUserState) Scan(value interface{}) error {
	if value == nil {
		ns.VetchiumHubUserState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VetchiumHubUserState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVetchiumHubUserState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VetchiumHubUserState), nil
}

type VetchiumAdminEffectivePermission struct {
	AdminUserID pgtype.UUID `json:"admin_user_id"`
	Permission  string      `json:"permission"`
}

type VetchiumAdminEmailOutbox struct {
	AdminEmailOutboxID    pgtype.UUID        `json:"admin_email_outbox_id"`
	Kind                  string             `json:"kind"`
	RecipientEmailAddress string             `json:"recipient_email_address"`
	PayloadCiphertext     []byte             `json:"payload_ciphertext"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SentAt                pgtype.Timestamptz `json:"sent_at"`
}

type VetchiumAdminInvitation struct {
	AdminInvitationID pgtype.UUID        `json:"admin_invitation_id"`
	EmailAddress      string             `json:"email_address"`
	TokenHash         []byte             `json:"token_hash"`
	Permissions       []string           `json:"permissions"`
	InvitedBy         pgtype.UUID        `json:"invited_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	Active            bool               `json:"active"`
}

type VetchiumAdminLoginChallenge struct {
	AdminLoginChallengeID pgtype.UUID        `json:"admin_login_challenge_id"`
	AdminUserID           pgtype.UUID        `json:"admin_user_id"`
	TokenHash             []byte             `json:"token_hash"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt            pgtype.Timestamptz `json:"consumed_at"`
	Active                bool               `json:"active"`
}

type VetchiumAdminPasswordResetToken struct {
	AdminPasswordResetTokenID pgtype.UUID        `json:"admin_password_reset_token_id"`
	AdminUserID               pgtype.UUID        `json:"admin_user_id"`
	TokenHash                 []byte             `json:"token_hash"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt                pgtype.Timestamptz `json:"consumed_at"`
	Active                    bool               `json:"active"`
}

type VetchiumAdminPermission struct {
	AdminUserID pgtype.UUID        `json:"admin_user_id"`
	Permission  string             `json:"permission"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type VetchiumAdminPermissionCatalog struct {
	Permission string `json:"permission"`
}

type VetchiumAdminPermissionImplication struct {
	Permission        string `json:"permission"`
	ImpliedPermission string `json:"implied_permission"`
}

type VetchiumAdminSession struct {
	AdminSessionID   pgtype.UUID        `json:"admin_session_id"`
	AdminUserID      pgtype.UUID        `json:"admin_user_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt  pgtype.Timestamptz `json:"authenticated_at"`
	LastTotpTimestep pgtype.Int8        `json:"last_totp_timestep"`
}

type VetchiumAdminTotpEnrollment struct {
	AdminTotpEnrollmentID pgtype.UUID        `json:"admin_totp_enrollment_id"`
	AdminUserID           pgtype.UUID        `json:"admin_user_id"`
	TokenHash             []byte             `json:"token_hash"`
	SecretCiphertext      []byte             `json:"secret_ciphertext"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt            pgtype.Timestamptz `json:"consumed_at"`
	Active                bool               `json:"active"`
}

type VetchiumAdminTotpRecoveryCode struct {
	AdminUserID pgtype.UUID        `json:"admin_user_id"`
	CodeHash    []byte             `json:"code_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
}

type VetchiumAdminUser struct {
	AdminUserID          pgtype.UUID            `json:"admin_user_id"`
	EmailAddress         string                 `json:"email_address"`
	DisplayName          string                 `json:"display_name"`
	PasswordHash         string                 `json:"password_hash"`
	AdminUserState       VetchiumAdminUserState `json:"admin_user_state"`
	PreferredLanguage    string                 `json:"preferred_language"`
	TotpSecretCiphertext []byte                 `json:"totp_secret_ciphertext"`
	TotpEnabled          bool                   `json:"totp_enabled"`
	TotpLastTimestep     pgtype.Int8            `json:"totp_last_timestep"`
	LastLoginAt          pgtype.Timestamptz     `json:"last_login_at"`
	CreatedAt            pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz     `json:"updated_at"`
}

type VetchiumAuditEvent struct {
	AuditEventID   pgtype.UUID        `json:"audit_event_id"`
	TenantID       string             `json:"tenant_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityID       string             `json:"entity_id"`
	ActorType      string             `json:"actor_type"`
	ActorID        pgtype.Text        `json:"actor_id"`
	Source         string             `json:"source"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type VetchiumFederationCommandLedger struct {
	CommandID      pgtype.UUID        `json:"command_id"`
	SourceTenantID string             `json:"source_tenant_id"`
	Kind           string             `json:"kind"`
	AggregateID    string             `json:"aggregate_id"`
	RequestDigest  []byte             `json:"request_digest"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type VetchiumFederationInbox struct {
	EventID          pgtype.UUID        `json:"event_id"`
	SourceTenantID   string             `json:"source_tenant_id"`
	Kind             string             `json:"kind"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      string             `json:"aggregate_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	PayloadDigest    []byte             `json:"payload_digest"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
}

type VetchiumFederationOperation struct {
	OperationID        pgtype.UUID                      `json:"operation_id"`
	CommandID          pgtype.UUID                      `json:"command_id"`
	Kind               string                           `json:"kind"`
	TargetAuthority    string                           `json:"target_authority"`
	AggregateID        string                           `json:"aggregate_id"`
	OwnerPrincipalType string                           `json:"owner_principal_type"`
	OwnerPrincipalID   string                           `json:"owner_principal_id"`
	IdempotencyKey     string                           `json:"idempotency_key"`
	RequestDigest      []byte                           `json:"request_digest"`
	PayloadBytes       []byte                           `json:"payload_bytes"`
	State              VetchiumFederationOperationState `json:"state"`
	ResponseStatus     pgtype.Int4                      `json:"response_status"`
	ResponseCiphertext []byte                           `json:"response_ciphertext"`
	AttemptCount       int32                            `json:"attempt_count"`
	NextAttemptAt      pgtype.Timestamptz               `json:"next_attempt_at"`
	LastError          pgtype.Text                      `json:"last_error"`
	CreatedAt          pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz               `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz               `json:"completed_at"`
	ExpiresAt          pgtype.Timestamptz               `json:"expires_at"`
}

type VetchiumFederationOutbox struct {
	EventID             pgtype.UUID        `json:"event_id"`
	DestinationTenantID string             `json:"destination_tenant_id"`
	Kind                string             `json:"kind"`
	AggregateType       string             `json:"aggregate_type"`
	AggregateID         string             `json:"aggregate_id"`
	AggregateVersion    int64              `json:"aggregate_version"`
	Payload             []byte             `json:"payload"`
	PayloadDigest       []byte             `json:"payload_digest"`
	AttemptCount        int32              `json:"attempt_count"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseToken          pgtype.UUID        `json:"lease_token"`
	LeasedUntil         pgtype.Timestamptz `json:"leased_until"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DeliveredAt         pgtype.Timestamptz `json:"delivered_at"`
	FailedAt            pgtype.Timestamptz `json:"failed_at"`
	LastError           pgtype.Text        `json:"last_error"`
}

type VetchiumHubCertification struct {
	CertificationID pgtype.UUID        `json:"certification_id"`
	HubUserDid      pgtype.UUID        `json:"hub_user_did"`
	Title           string             `json:"title"`
	CredentialUrl   string             `json:"credential_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type VetchiumHubEducationalQualification struct {
	EducationalQualificationID pgtype.UUID        `json:"educational_qualification_id"`
	HubUserDid                 pgtype.UUID        `json:"hub_user_did"`
	InstitutionDomain          string             `json:"institution_domain"`
	Degree                     string             `json:"degree"`
	Title                      pgtype.Text        `json:"title"`
	SupportingText             pgtype.Text        `json:"supporting_text"`
	StartMonth                 pgtype.Date        `json:"start_month"`
	EndMonth                   pgtype.Date        `json:"end_month"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type VetchiumHubEmailChangeChallenge struct {
	ChallengeID     pgtype.UUID        `json:"challenge_id"`
	HubUserDid      pgtype.UUID        `json:"hub_user_did"`
	HubSessionID    pgtype.UUID        `json:"hub_session_id"`
	NewEmailAddress string             `json:"new_email_address"`
	CodeHash        []byte             `json:"code_hash"`
	AttemptCount    int32              `json:"attempt_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
	SupersededAt    pgtype.Timestamptz `json:"superseded_at"`
}

type VetchiumHubEmailOutbox struct {
	HubEmailOutboxID      pgtype.UUID        `json:"hub_email_outbox_id"`
	Kind                  string             `json:"kind"`
	RecipientEmailAddress string             `json:"recipient_email_address"`
	PreferredLanguage     string             `json:"preferred_language"`
	PayloadCiphertext     []byte             `json:"payload_ciphertext"`
	AttemptCount          int32              `json:"attempt_count"`
	NextAttemptAt         pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseToken            pgtype.UUID        `json:"lease_token"`
	LeasedUntil           pgtype.Timestamptz `json:"leased_until"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SentAt                pgtype.Timestamptz `json:"sent_at"`
	FailedAt              pgtype.Timestamptz `json:"failed_at"`
}

type VetchiumHubLanguageAbility struct {
	HubUserDid  pgtype.UUID                    `json:"hub_user_did"`
	Ability     VetchiumHubLanguageAbilityKind `json:"ability"`
	LanguageTag string                         `json:"language_tag"`
	CreatedAt   pgtype.Timestamptz             `json:"created_at"`
}

type VetchiumHubLoginChallenge struct {
	HubLoginChallengeID pgtype.UUID        `json:"hub_login_challenge_id"`
	HubUserDid          pgtype.UUID        `json:"hub_user_did"`
	TokenHash           []byte             `json:"token_hash"`
	Remembered          bool               `json:"remembered"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	Active              bool               `json:"active"`
}

type VetchiumHubPasswordResetToken struct {
	HubPasswordResetTokenID pgtype.UUID        `json:"hub_password_reset_token_id"`
	HubUserDid              pgtype.UUID        `json:"hub_user_did"`
	TokenHash               []byte             `json:"token_hash"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt              pgtype.Timestamptz `json:"consumed_at"`
	Active                  bool               `json:"active"`
}

type VetchiumHubPlan struct {
	HubPlanOid string `json:"hub_plan_oid"`
}

type VetchiumHubProfessionalEmail struct {
	ProfessionalEmailID pgtype.UUID        `json:"professional_email_id"`
	HubUserDid          pgtype.UUID        `json:"hub_user_did"`
	EmailAddress        string             `json:"email_address"`
	Domain              string             `json:"domain"`
	FirstVerifiedAt     pgtype.Timestamptz `json:"first_verified_at"`
	LastVerifiedAt      pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type VetchiumHubProfessionalEmailChallenge struct {
	ChallengeID         pgtype.UUID        `json:"challenge_id"`
	ProfessionalEmailID pgtype.UUID        `json:"professional_email_id"`
	CodeHash            []byte             `json:"code_hash"`
	AttemptCount        int32              `json:"attempt_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	SupersededAt        pgtype.Timestamptz `json:"superseded_at"`
}

type VetchiumHubProfilePictureObject struct {
	ObjectID          pgtype.UUID                     `json:"object_id"`
	HubUserDid        pgtype.UUID                     `json:"hub_user_did"`
	Format            VetchiumHubProfilePictureFormat `json:"format"`
	ByteSize          int32                           `json:"byte_size"`
	Width             int32                           `json:"width"`
	Height            int32                           `json:"height"`
	ContentSha256     []byte                          `json:"content_sha256"`
	State             VetchiumHubProfilePictureState  `json:"state"`
	AttemptCount      int32                           `json:"attempt_count"`
	NextAttemptAt     pgtype.Timestamptz              `json:"next_attempt_at"`
	LeaseToken        pgtype.UUID                     `json:"lease_token"`
	LeasedUntil       pgtype.Timestamptz              `json:"leased_until"`
	LastError         pgtype.Text                     `json:"last_error"`
	CreatedAt         pgtype.Timestamptz              `json:"created_at"`
	UploadExpiresAt   pgtype.Timestamptz              `json:"upload_expires_at"`
	DeleteRequestedAt pgtype.Timestamptz              `json:"delete_requested_at"`
}

type VetchiumHubSession struct {
	HubSessionID     pgtype.UUID        `json:"hub_session_id"`
	HubUserDid       pgtype.UUID        `json:"hub_user_did"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	AuthenticatedAt  pgtype.Timestamptz `json:"authenticated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Remembered       bool               `json:"remembered"`
}

type VetchiumHubSignupCompletion struct {
	OperationID           pgtype.UUID                      `json:"operation_id"`
	HubSignupRequestID    pgtype.UUID                      `json:"hub_signup_request_id"`
	TokenHash             []byte                           `json:"token_hash"`
	IdempotencyKey        string                           `json:"idempotency_key"`
	RequestDigest         []byte                           `json:"request_digest"`
	HubUserDid            pgtype.UUID                      `json:"hub_user_did"`
	Handle                string                           `json:"handle"`
	ReserveCommandID      pgtype.UUID                      `json:"reserve_command_id"`
	ActivateCommandID     pgtype.UUID                      `json:"activate_command_id"`
	PayloadCiphertext     []byte                           `json:"payload_ciphertext"`
	State                 VetchiumHubSignupCompletionState `json:"state"`
	ProvisioningExpiresAt pgtype.Timestamptz               `json:"provisioning_expires_at"`
	AttemptCount          int32                            `json:"attempt_count"`
	NextAttemptAt         pgtype.Timestamptz               `json:"next_attempt_at"`
	LastError             pgtype.Text                      `json:"last_error"`
	CreatedAt             pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz               `json:"updated_at"`
	CompletedAt           pgtype.Timestamptz               `json:"completed_at"`
	ExpiresAt             pgtype.Timestamptz               `json:"expires_at"`
}

type VetchiumHubSignupDomain struct {
	HubSignupDomainID    pgtype.UUID                  `json:"hub_signup_domain_id"`
	Domain               string                       `json:"domain"`
	HubSignupDomainState VetchiumHubSignupDomainState `json:"hub_signup_domain_state"`
	DisabledComment      pgtype.Text                  `json:"disabled_comment"`
	CreatedAt            pgtype.Timestamptz           `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz           `json:"updated_at"`
}

type VetchiumHubSignupRequest struct {
	HubSignupRequestID pgtype.UUID        `json:"hub_signup_request_id"`
	EmailAddress       string             `json:"email_address"`
	DisplayName        string             `json:"display_name"`
	PreferredLanguage  string             `json:"preferred_language"`
	ResidentCountry    string             `json:"resident_country"`
	TokenHash          []byte             `json:"token_hash"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt         pgtype.Timestamptz `json:"consumed_at"`
	Active             bool               `json:"active"`
}

type VetchiumHubSubscriptionExpiryNotice struct {
	HubSubscriptionExpiryNoticeID pgtype.UUID                       `json:"hub_subscription_expiry_notice_id"`
	HubUserDid                    pgtype.UUID                       `json:"hub_user_did"`
	PeriodEnd                     pgtype.Timestamptz                `json:"period_end"`
	LeadTime                      VetchiumHubSubscriptionNoticeLead `json:"lead_time"`
	CreatedAt                     pgtype.Timestamptz                `json:"created_at"`
}

type VetchiumHubTotpEnrollment struct {
	HubTotpEnrollmentID pgtype.UUID        `json:"hub_totp_enrollment_id"`
	HubUserDid          pgtype.UUID        `json:"hub_user_did"`
	TokenHash           []byte             `json:"token_hash"`
	SecretCiphertext    []byte             `json:"secret_ciphertext"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	Active              bool               `json:"active"`
}

type VetchiumHubTotpRecoveryCode struct {
	HubUserDid pgtype.UUID        `json:"hub_user_did"`
	CodeHash   []byte             `json:"code_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type VetchiumHubUser struct {
	HubUserDid                     pgtype.UUID                    `json:"hub_user_did"`
	Handle                         string                         `json:"handle"`
	EmailAddress                   string                         `json:"email_address"`
	DisplayName                    string                         `json:"display_name"`
	Biography                      pgtype.Text                    `json:"biography"`
	ProfileAlias                   pgtype.Text                    `json:"profile_alias"`
	AliasLastChangedAt             pgtype.Timestamptz             `json:"alias_last_changed_at"`
	ProfileVersion                 int64                          `json:"profile_version"`
	PasswordHash                   string                         `json:"password_hash"`
	HubUserState                   VetchiumHubUserState           `json:"hub_user_state"`
	PreferredLanguage              string                         `json:"preferred_language"`
	ResidentCountry                string                         `json:"resident_country"`
	PreferredJobCountries          []string                       `json:"preferred_job_countries"`
	TotpSecretCiphertext           []byte                         `json:"totp_secret_ciphertext"`
	TotpEnabled                    bool                           `json:"totp_enabled"`
	TotpLastTimestep               pgtype.Int8                    `json:"totp_last_timestep"`
	LastLoginAt                    pgtype.Timestamptz             `json:"last_login_at"`
	HubPlanOid                     string                         `json:"hub_plan_oid"`
	SubscriptionBillingInterval    NullVetchiumHubBillingInterval `json:"subscription_billing_interval"`
	SubscriptionAnchorAt           pgtype.Timestamptz             `json:"subscription_anchor_at"`
	SubscriptionPeriodStart        pgtype.Timestamptz             `json:"subscription_period_start"`
	SubscriptionPeriodEnd          pgtype.Timestamptz             `json:"subscription_period_end"`
	ScheduledHubPlanOid            pgtype.Text                    `json:"scheduled_hub_plan_oid"`
	ScheduledBillingInterval       NullVetchiumHubBillingInterval `json:"scheduled_billing_interval"`
	SubscriptionCancelsAtPeriodEnd bool                           `json:"subscription_cancels_at_period_end"`
	SubscriptionSource             VetchiumHubSubscriptionSource  `json:"subscription_source"`
	CreatedAt                      pgtype.Timestamptz             `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz             `json:"updated_at"`
}

type VetchiumHubWorkExperience struct {
	WorkExperienceID pgtype.UUID        `json:"work_experience_id"`
	HubUserDid       pgtype.UUID        `json:"hub_user_did"`
	EmployerDomain   string             `json:"employer_domain"`
	JobTitle         string             `json:"job_title"`
	StartMonth       pgtype.Date        `json:"start_month"`
	EndMonth         pgtype.Date        `json:"end_month"`
	Location         pgtype.Text        `json:"location"`
	Description      pgtype.Text        `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type VetchiumIdempotencyLedger struct {
	Operation          string             `json:"operation"`
	BindingID          string             `json:"binding_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestDigest      []byte             `json:"request_digest"`
	ResponseStatus     pgtype.Int4        `json:"response_status"`
	ResponseCiphertext []byte             `json:"response_ciphertext"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type VetchiumOrg struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
