// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_sso.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOrgSSOLoginState = `-- name: ConsumeOrgSSOLoginState :one
UPDATE vetchium.org_sso_login_states AS t
SET consumed_at = now()
WHERE t.state_hash = $1
  AND t.provider = $2
  AND t.consumed_at IS NULL
  AND t.expires_at > now()
RETURNING t.domain::text AS domain, t.nonce_hash, t.verifier_ciphertext
`

type ConsumeOrgSSOLoginStateParams struct {
	StateHash []byte `json:"state_hash"`
	Provider  string `json:"provider"`
}

type ConsumeOrgSSOLoginStateRow struct {
	Domain             string `json:"domain"`
	NonceHash          []byte `json:"nonce_hash"`
	VerifierCiphertext []byte `json:"verifier_ciphertext"`
}

// A state redeems once and only before it expires; a replay finds nothing.
func (q *Queries) ConsumeOrgSSOLoginState(ctx context.Context, arg ConsumeOrgSSOLoginStateParams) (ConsumeOrgSSOLoginStateRow, error) {
	row := q.db.QueryRow(ctx, consumeOrgSSOLoginState, arg.StateHash, arg.Provider)
	var i ConsumeOrgSSOLoginStateRow
	err := row.Scan(&i.Domain, &i.NonceHash, &i.VerifierCiphertext)
	return i, err
}

const createOrgSSOLoginState = `-- name: CreateOrgSSOLoginState :exec
INSERT INTO vetchium.org_sso_login_states (
    state_hash, provider, domain, nonce_hash, verifier_ciphertext, expires_at
)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreateOrgSSOLoginStateParams struct {
	StateHash          []byte             `json:"state_hash"`
	Provider           string             `json:"provider"`
	Domain             string             `json:"domain"`
	NonceHash          []byte             `json:"nonce_hash"`
	VerifierCiphertext []byte             `json:"verifier_ciphertext"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrgSSOLoginState(ctx context.Context, arg CreateOrgSSOLoginStateParams) error {
	_, err := q.db.Exec(ctx, createOrgSSOLoginState,
		arg.StateHash,
		arg.Provider,
		arg.Domain,
		arg.NonceHash,
		arg.VerifierCiphertext,
		arg.ExpiresAt,
	)
	return err
}

const createOrgSSOSession = `-- name: CreateOrgSSOSession :one
WITH eligible AS (
    SELECT u.org_user_id
    FROM vetchium.org_users AS u
    JOIN vetchium.orgs AS o ON o.org_did = u.org_did
    JOIN vetchium.org_domains AS d ON d.org_did = o.org_did
    WHERE u.org_user_id = $1
      AND u.org_user_state = 'active'
      AND o.org_state IN ('active', 'suspended')
      AND o.org_plan_oid = ANY($2::text[])
      AND o.google_sign_in_enabled
      AND d.domain = $3
      AND d.domain_state IN ('verified', 'failing', 'releasing')
    FOR UPDATE OF u
), linked AS (
    INSERT INTO vetchium.org_user_sso_identities (org_user_id, provider, subject)
    SELECT org_user_id, $4, $5
    FROM eligible
    ON CONFLICT (org_user_id, provider) DO UPDATE
    SET last_used_at = now()
    WHERE org_user_sso_identities.subject = EXCLUDED.subject
    RETURNING org_user_id
), updated_user AS (
    UPDATE vetchium.org_users AS u
    SET last_login_at = now(),
        updated_at = now()
    FROM linked
    WHERE u.org_user_id = linked.org_user_id
    RETURNING u.org_user_id
), session AS (
    INSERT INTO vetchium.org_sessions (
        session_token_hash,
        org_user_id,
        expires_at,
        authenticated_at
    )
    SELECT
        $6,
        org_user_id,
        $7,
        now()
    FROM updated_user
    RETURNING org_session_id, org_user_id, created_at, expires_at,
        authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $8,
        'org.session.created',
        'org_session',
        org_session_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        jsonb_build_object('method', $4::text)
    FROM session
)
SELECT org_session_id, created_at, expires_at, authenticated_at
FROM session
`

type CreateOrgSSOSessionParams struct {
	OrgUserID            pgtype.UUID        `json:"org_user_id"`
	GoogleSignInPlanOids []string           `json:"google_sign_in_plan_oids"`
	Domain               string             `json:"domain"`
	Provider             string             `json:"provider"`
	Subject              string             `json:"subject"`
	SessionTokenHash     []byte             `json:"session_token_hash"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	TenantID             string             `json:"tenant_id"`
}

type CreateOrgSSOSessionRow struct {
	OrgSessionID    pgtype.UUID        `json:"org_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
}

// Links the subject on first use, then signs in. Every condition is read
// again here, so a plan change, a disablement or a competing link that lands
// after GetOrgUserForSSO leaves no row. The Google sign-in skips Vetchium
// TOTP by design (D23), which is why this does not use CreateOrgSession.
func (q *Queries) CreateOrgSSOSession(ctx context.Context, arg CreateOrgSSOSessionParams) (CreateOrgSSOSessionRow, error) {
	row := q.db.QueryRow(ctx, createOrgSSOSession,
		arg.OrgUserID,
		arg.GoogleSignInPlanOids,
		arg.Domain,
		arg.Provider,
		arg.Subject,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.TenantID,
	)
	var i CreateOrgSSOSessionRow
	err := row.Scan(
		&i.OrgSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
	)
	return i, err
}

const getOrgUserForSSO = `-- name: GetOrgUserForSSO :one
SELECT
    u.org_user_id,
    u.org_user_state,
    u.disabled_reason,
    u.preferred_language,
    o.org_plan_oid,
    o.google_sign_in_enabled,
    COALESCE((
        SELECT i.subject
        FROM vetchium.org_user_sso_identities AS i
        WHERE i.org_user_id = u.org_user_id AND i.provider = $1
    ), '')::text AS linked_subject,
    (
        SELECT i.org_user_id
        FROM vetchium.org_user_sso_identities AS i
        WHERE i.provider = $1 AND i.subject = $2
    ) AS subject_owner_id
FROM vetchium.org_domains AS d
JOIN vetchium.orgs AS o ON o.org_did = d.org_did
JOIN vetchium.org_users AS u
    ON u.org_did = o.org_did
   AND u.email_address = $3
WHERE d.domain = $4
  AND d.domain_state IN ('verified', 'failing', 'releasing')
  AND o.org_state IN ('active', 'suspended')
  AND u.org_user_state IN ('active', 'disabled')
`

type GetOrgUserForSSOParams struct {
	Provider     string `json:"provider"`
	Subject      string `json:"subject"`
	EmailAddress string `json:"email_address"`
	Domain       string `json:"domain"`
}

type GetOrgUserForSSORow struct {
	OrgUserID           pgtype.UUID          `json:"org_user_id"`
	OrgUserState        VetchiumOrgUserState `json:"org_user_state"`
	DisabledReason      pgtype.Text          `json:"disabled_reason"`
	PreferredLanguage   string               `json:"preferred_language"`
	OrgPlanOid          string               `json:"org_plan_oid"`
	GoogleSignInEnabled bool                 `json:"google_sign_in_enabled"`
	LinkedSubject       string               `json:"linked_subject"`
	SubjectOwnerID      pgtype.UUID          `json:"subject_owner_id"`
}

// The user a verified Google identity names, with everything the sign-in
// decision reads. Google sign-in trusts the hosted-domain claim, so only an
// Org that still holds the domain qualifies: a released or re-claiming domain
// proves nothing, and the claimed-domain index makes the match unique.
func (q *Queries) GetOrgUserForSSO(ctx context.Context, arg GetOrgUserForSSOParams) (GetOrgUserForSSORow, error) {
	row := q.db.QueryRow(ctx, getOrgUserForSSO,
		arg.Provider,
		arg.Subject,
		arg.EmailAddress,
		arg.Domain,
	)
	var i GetOrgUserForSSORow
	err := row.Scan(
		&i.OrgUserID,
		&i.OrgUserState,
		&i.DisabledReason,
		&i.PreferredLanguage,
		&i.OrgPlanOid,
		&i.GoogleSignInEnabled,
		&i.LinkedSubject,
		&i.SubjectOwnerID,
	)
	return i, err
}

const lockOrgForGoogleSignIn = `-- name: LockOrgForGoogleSignIn :one
SELECT
    o.org_plan_oid, o.scheduled_org_plan_oid, o.google_sign_in_enabled
FROM vetchium.orgs AS o
WHERE o.org_did = $1
  AND o.org_state = 'active'
FOR UPDATE OF o
`

type LockOrgForGoogleSignInRow struct {
	OrgPlanOid          string      `json:"org_plan_oid"`
	ScheduledOrgPlanOid pgtype.Text `json:"scheduled_org_plan_oid"`
	GoogleSignInEnabled bool        `json:"google_sign_in_enabled"`
}

func (q *Queries) LockOrgForGoogleSignIn(ctx context.Context, orgDid pgtype.UUID) (LockOrgForGoogleSignInRow, error) {
	row := q.db.QueryRow(ctx, lockOrgForGoogleSignIn, orgDid)
	var i LockOrgForGoogleSignInRow
	err := row.Scan(&i.OrgPlanOid, &i.ScheduledOrgPlanOid, &i.GoogleSignInEnabled)
	return i, err
}

const setOrgGoogleSignIn = `-- name: SetOrgGoogleSignIn :exec
WITH changed AS (
    UPDATE vetchium.orgs AS o
    SET google_sign_in_enabled = $2::boolean,
        updated_at = now()
    WHERE o.org_did = $4
      AND o.google_sign_in_enabled <> $2::boolean
    RETURNING o.org_did
)
INSERT INTO vetchium.audit_events (
    tenant_id, action, entity_type, entity_id, actor_type, actor_id,
    source, payload
)
SELECT
    $1,
    CASE WHEN $2::boolean
        THEN 'org.google_sign_in.enabled'
        ELSE 'org.google_sign_in.disabled'
    END,
    'org',
    changed.org_did::text,
    'org_user',
    $3::text,
    'orgs-api',
    '{}'::jsonb
FROM changed
`

type SetOrgGoogleSignInParams struct {
	TenantID string      `json:"tenant_id"`
	Enabled  bool        `json:"enabled"`
	ActorID  string      `json:"actor_id"`
	OrgDid   pgtype.UUID `json:"org_did"`
}

func (q *Queries) SetOrgGoogleSignIn(ctx context.Context, arg SetOrgGoogleSignInParams) error {
	_, err := q.db.Exec(ctx, setOrgGoogleSignIn,
		arg.TenantID,
		arg.Enabled,
		arg.ActorID,
		arg.OrgDid,
	)
	return err
}
