// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_housekeeping.sql

package sqlc

import (
	"context"
)

const pruneOrgEphemeralData = `-- name: PruneOrgEphemeralData :one

WITH sessions AS (
    DELETE FROM vetchium.org_sessions AS s
    WHERE s.org_session_id IN (
        SELECT candidate.org_session_id
        FROM vetchium.org_sessions AS candidate
        WHERE candidate.expires_at <= now()
        ORDER BY candidate.expires_at
        LIMIT 1000
    )
    RETURNING s.org_session_id
), challenges AS (
    DELETE FROM vetchium.org_login_challenges AS c
    WHERE c.org_login_challenge_id IN (
        SELECT candidate.org_login_challenge_id
        FROM vetchium.org_login_challenges AS candidate
        WHERE candidate.expires_at <= now()
           OR candidate.consumed_at IS NOT NULL
           OR NOT candidate.active
        ORDER BY candidate.created_at
        LIMIT 1000
    )
    RETURNING c.org_login_challenge_id
), enrollments AS (
    DELETE FROM vetchium.org_totp_enrollments AS e
    WHERE e.org_totp_enrollment_id IN (
        SELECT candidate.org_totp_enrollment_id
        FROM vetchium.org_totp_enrollments AS candidate
        WHERE candidate.expires_at <= now()
           OR candidate.consumed_at IS NOT NULL
           OR NOT candidate.active
        ORDER BY candidate.created_at
        LIMIT 1000
    )
    RETURNING e.org_totp_enrollment_id
), resets AS (
    DELETE FROM vetchium.org_password_reset_tokens AS r
    WHERE r.org_password_reset_token_id IN (
        SELECT candidate.org_password_reset_token_id
        FROM vetchium.org_password_reset_tokens AS candidate
        WHERE candidate.expires_at <= now()
           OR candidate.consumed_at IS NOT NULL
           OR NOT candidate.active
        ORDER BY candidate.created_at
        LIMIT 1000
    )
    RETURNING r.org_password_reset_token_id
), signups AS (
    DELETE FROM vetchium.org_signup_requests AS s
    WHERE s.org_signup_request_id IN (
        SELECT candidate.org_signup_request_id
        FROM vetchium.org_signup_requests AS candidate
        WHERE candidate.expires_at <= now()
           OR NOT candidate.active
        ORDER BY candidate.created_at
        LIMIT 1000
    )
    RETURNING s.org_signup_request_id
), invitations AS (
    DELETE FROM vetchium.org_user_invitations AS i
    WHERE i.org_invitation_id IN (
        SELECT candidate.org_invitation_id
        FROM vetchium.org_user_invitations AS candidate
        WHERE candidate.expires_at <= now()
           OR NOT candidate.active
        ORDER BY candidate.created_at
        LIMIT 1000
    )
    RETURNING i.org_invitation_id
), sso_states AS (
    DELETE FROM vetchium.org_sso_login_states AS t
    WHERE t.state_hash IN (
        SELECT candidate.state_hash
        FROM vetchium.org_sso_login_states AS candidate
        WHERE candidate.expires_at <= now()
           OR candidate.consumed_at IS NOT NULL
        ORDER BY candidate.created_at
        LIMIT 1000
    )
    RETURNING t.state_hash
),
outbox AS (
    DELETE FROM vetchium.org_email_outbox AS o
    WHERE o.org_email_outbox_id IN (
        SELECT candidate.org_email_outbox_id
        FROM vetchium.org_email_outbox AS candidate
        WHERE (candidate.sent_at IS NOT NULL OR candidate.failed_at IS NOT NULL)
          AND candidate.created_at <= now() - interval '1 day'
        ORDER BY candidate.created_at
        LIMIT 1000
    )
    RETURNING o.org_email_outbox_id
), summary AS (
    SELECT
        (SELECT count(*) FROM sessions)::bigint AS sessions,
        (SELECT count(*) FROM challenges)::bigint AS challenges,
        (SELECT count(*) FROM enrollments)::bigint AS enrollments,
        (SELECT count(*) FROM resets)::bigint AS resets,
        (SELECT count(*) FROM signups)::bigint AS signups,
        (SELECT count(*) FROM invitations)::bigint AS invitations,
        (SELECT count(*) FROM sso_states)::bigint AS sso_states,
        (SELECT count(*) FROM outbox)::bigint AS outbox
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $1,
        'org.housekeeping.pruned',
        'housekeeping_batch',
        gen_random_uuid()::text,
        'worker',
        'workers',
        'workers',
        to_jsonb(summary)
    FROM summary
    WHERE sessions + challenges + enrollments + resets + signups + invitations + sso_states + outbox > 0
)
SELECT
    (sessions + challenges + enrollments + resets + signups + invitations + sso_states + outbox)::bigint
        AS deleted_count
FROM summary
`

// Deletes at most one batch per table and run, like administrator
// housekeeping, so a backlog cannot monopolize the database.
// Outbox ciphertext can contain a signup or reset link, so it is kept only
// for a day after delivery ends, whether it succeeded or not.
func (q *Queries) PruneOrgEphemeralData(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, pruneOrgEphemeralData, tenantID)
	var deleted_count int64
	err := row.Scan(&deleted_count)
	return deleted_count, err
}
