// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateOrgSession = `-- name: AuthenticateOrgSession :one
SELECT
    u.org_user_id,
    u.org_did,
    s.org_session_id,
    s.authenticated_at,
    o.org_state,
    ARRAY(
        SELECT e.permission
        FROM vetchium.org_effective_permissions AS e
        WHERE e.org_user_id = u.org_user_id
        ORDER BY e.permission
    )::text[] AS permissions
FROM vetchium.org_sessions AS s
JOIN vetchium.org_users AS u USING (org_user_id)
JOIN vetchium.orgs AS o ON o.org_did = u.org_did
WHERE s.session_token_hash = $1
  AND s.expires_at > now()
  AND u.org_user_state = 'active'
  AND o.org_state IN ('active', 'suspended')
`

type AuthenticateOrgSessionRow struct {
	OrgUserID       pgtype.UUID        `json:"org_user_id"`
	OrgDid          pgtype.UUID        `json:"org_did"`
	OrgSessionID    pgtype.UUID        `json:"org_session_id"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
	OrgState        VetchiumOrgState   `json:"org_state"`
	Permissions     []string           `json:"permissions"`
}

func (q *Queries) AuthenticateOrgSession(ctx context.Context, sessionTokenHash []byte) (AuthenticateOrgSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateOrgSession, sessionTokenHash)
	var i AuthenticateOrgSessionRow
	err := row.Scan(
		&i.OrgUserID,
		&i.OrgDid,
		&i.OrgSessionID,
		&i.AuthenticatedAt,
		&i.OrgState,
		&i.Permissions,
	)
	return i, err
}

const completeOrgRecoveryCodeLogin = `-- name: CompleteOrgRecoveryCodeLogin :one
WITH eligible_challenge AS (
    SELECT c.org_login_challenge_id, c.org_user_id
    FROM vetchium.org_login_challenges AS c
    WHERE c.org_login_challenge_id = $1
      AND c.org_user_id = $2
      AND c.active
      AND c.consumed_at IS NULL
      AND c.expires_at > now()
    FOR UPDATE
), consumed_code AS (
    UPDATE vetchium.org_totp_recovery_codes AS r
    SET consumed_at = now()
    WHERE r.org_user_id IN (SELECT org_user_id FROM eligible_challenge)
      AND r.code_hash = $3
      AND r.consumed_at IS NULL
    RETURNING r.org_user_id, r.code_hash
), consumed_challenge AS (
    UPDATE vetchium.org_login_challenges AS c
    SET consumed_at = now(),
        active = false
    FROM consumed_code AS code
    WHERE c.org_login_challenge_id = $1
      AND c.org_user_id = code.org_user_id
      AND c.active
      AND c.consumed_at IS NULL
      AND c.expires_at > now()
    RETURNING c.org_user_id
), updated_user AS (
    UPDATE vetchium.org_users AS u
    SET last_login_at = now(),
        updated_at = now()
    FROM consumed_challenge AS challenge
    WHERE u.org_user_id = challenge.org_user_id
      AND u.org_user_state = 'active'
    RETURNING u.org_user_id
), session AS (
    INSERT INTO vetchium.org_sessions (
        session_token_hash,
        org_user_id,
        expires_at,
        authenticated_at
    )
    SELECT
        $4,
        org_user_id,
        $5,
        now()
    FROM updated_user
    RETURNING org_session_id, org_user_id, created_at, expires_at,
        authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $6,
        'org.session.created-with-recovery-code',
        'org_session',
        org_session_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        $7,
        '{}'::jsonb
    FROM session
)
SELECT
    session.org_session_id,
    session.created_at,
    session.expires_at,
    session.authenticated_at,
    count(c.code_hash) FILTER (
        WHERE c.consumed_at IS NULL
          AND c.code_hash <> (SELECT code_hash FROM consumed_code)
    )::bigint AS remaining_codes
FROM session
JOIN vetchium.org_totp_recovery_codes AS c USING (org_user_id)
GROUP BY session.org_session_id, session.created_at, session.expires_at,
    session.authenticated_at
`

type CompleteOrgRecoveryCodeLoginParams struct {
	OrgLoginChallengeID pgtype.UUID        `json:"org_login_challenge_id"`
	OrgUserID           pgtype.UUID        `json:"org_user_id"`
	RecoveryCodeHash    []byte             `json:"recovery_code_hash"`
	SessionTokenHash    []byte             `json:"session_token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	TenantID            string             `json:"tenant_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
}

type CompleteOrgRecoveryCodeLoginRow struct {
	OrgSessionID    pgtype.UUID        `json:"org_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
	RemainingCodes  int64              `json:"remaining_codes"`
}

func (q *Queries) CompleteOrgRecoveryCodeLogin(ctx context.Context, arg CompleteOrgRecoveryCodeLoginParams) (CompleteOrgRecoveryCodeLoginRow, error) {
	row := q.db.QueryRow(ctx, completeOrgRecoveryCodeLogin,
		arg.OrgLoginChallengeID,
		arg.OrgUserID,
		arg.RecoveryCodeHash,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CompleteOrgRecoveryCodeLoginRow
	err := row.Scan(
		&i.OrgSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
		&i.RemainingCodes,
	)
	return i, err
}

const completeOrgTOTPLogin = `-- name: CompleteOrgTOTPLogin :one
WITH accepted_timestep AS (
    UPDATE vetchium.org_user_totp_credentials AS t
    SET last_timestep = $1
    FROM vetchium.org_users AS u
    WHERE t.org_user_id = $2
      AND u.org_user_id = t.org_user_id
      AND u.org_user_state = 'active'
      AND (
          t.last_timestep IS NULL OR
          t.last_timestep < $1
      )
    RETURNING t.org_user_id
), consumed AS (
    UPDATE vetchium.org_login_challenges AS c
    SET consumed_at = now(),
        active = false
    FROM accepted_timestep AS t
    WHERE c.org_login_challenge_id = $3
      AND c.org_user_id = t.org_user_id
      AND c.active
      AND c.consumed_at IS NULL
      AND c.expires_at > now()
    RETURNING c.org_user_id
), updated_user AS (
    UPDATE vetchium.org_users AS u
    SET last_login_at = now(),
        updated_at = now()
    FROM consumed
    WHERE u.org_user_id = consumed.org_user_id
    RETURNING u.org_user_id
), session AS (
    INSERT INTO vetchium.org_sessions (
        session_token_hash,
        org_user_id,
        expires_at,
        authenticated_at
    )
    SELECT
        $4,
        org_user_id,
        $5,
        now()
    FROM updated_user
    RETURNING org_session_id, org_user_id, created_at, expires_at,
        authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $6,
        'org.session.created-with-totp',
        'org_session',
        org_session_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        $7,
        '{}'::jsonb
    FROM session
)
SELECT org_session_id, created_at, expires_at, authenticated_at
FROM session
`

type CompleteOrgTOTPLoginParams struct {
	LastTotpTimestep    pgtype.Int8        `json:"last_totp_timestep"`
	OrgUserID           pgtype.UUID        `json:"org_user_id"`
	OrgLoginChallengeID pgtype.UUID        `json:"org_login_challenge_id"`
	SessionTokenHash    []byte             `json:"session_token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	TenantID            string             `json:"tenant_id"`
	IdempotencyKey      pgtype.Text        `json:"idempotency_key"`
}

type CompleteOrgTOTPLoginRow struct {
	OrgSessionID    pgtype.UUID        `json:"org_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
}

func (q *Queries) CompleteOrgTOTPLogin(ctx context.Context, arg CompleteOrgTOTPLoginParams) (CompleteOrgTOTPLoginRow, error) {
	row := q.db.QueryRow(ctx, completeOrgTOTPLogin,
		arg.LastTotpTimestep,
		arg.OrgUserID,
		arg.OrgLoginChallengeID,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CompleteOrgTOTPLoginRow
	err := row.Scan(
		&i.OrgSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
	)
	return i, err
}

const createOrgLoginChallenge = `-- name: CreateOrgLoginChallenge :one
WITH eligible_user AS (
    SELECT u.org_user_id
    FROM vetchium.org_users AS u
    JOIN vetchium.org_user_passwords AS p USING (org_user_id)
    JOIN vetchium.org_user_totp_credentials AS t USING (org_user_id)
    WHERE u.org_user_id = $1
      AND p.password_hash = $2
      AND u.org_user_state = 'active'
    FOR UPDATE OF u
), challenge AS (
    INSERT INTO vetchium.org_login_challenges (
        org_user_id,
        token_hash,
        expires_at
    )
    SELECT
        org_user_id,
        $3,
        $4
    FROM eligible_user
    ON CONFLICT (org_user_id) WHERE active DO UPDATE
    SET token_hash = EXCLUDED.token_hash,
        created_at = now(),
        expires_at = EXCLUDED.expires_at,
        consumed_at = NULL
    RETURNING org_login_challenge_id, org_user_id, expires_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $5,
        'org.login-challenge.created',
        'org_login_challenge',
        org_login_challenge_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        '{}'::jsonb
    FROM challenge
)
SELECT org_login_challenge_id, expires_at FROM challenge
`

type CreateOrgLoginChallengeParams struct {
	OrgUserID            pgtype.UUID        `json:"org_user_id"`
	VerifiedPasswordHash string             `json:"verified_password_hash"`
	TokenHash            []byte             `json:"token_hash"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	TenantID             string             `json:"tenant_id"`
}

type CreateOrgLoginChallengeRow struct {
	OrgLoginChallengeID pgtype.UUID        `json:"org_login_challenge_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrgLoginChallenge(ctx context.Context, arg CreateOrgLoginChallengeParams) (CreateOrgLoginChallengeRow, error) {
	row := q.db.QueryRow(ctx, createOrgLoginChallenge,
		arg.OrgUserID,
		arg.VerifiedPasswordHash,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.TenantID,
	)
	var i CreateOrgLoginChallengeRow
	err := row.Scan(&i.OrgLoginChallengeID, &i.ExpiresAt)
	return i, err
}

const createOrgSession = `-- name: CreateOrgSession :one
WITH updated_user AS (
    UPDATE vetchium.org_users AS u
    SET last_login_at = now(),
        updated_at = now()
    FROM vetchium.org_user_passwords AS p
    WHERE u.org_user_id = $1
      AND p.org_user_id = u.org_user_id
      AND u.org_user_state = 'active'
      AND p.password_hash = $2
      AND NOT EXISTS (
          SELECT 1 FROM vetchium.org_user_totp_credentials AS t
          WHERE t.org_user_id = u.org_user_id
      )
    RETURNING u.org_user_id
), session AS (
    INSERT INTO vetchium.org_sessions (
        session_token_hash,
        org_user_id,
        expires_at,
        authenticated_at
    )
    SELECT
        $3,
        org_user_id,
        $4,
        now()
    FROM updated_user
    RETURNING org_session_id, org_user_id, created_at, expires_at,
        authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $5,
        'org.session.created',
        'org_session',
        org_session_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        '{}'::jsonb
    FROM session
)
SELECT org_session_id, created_at, expires_at, authenticated_at
FROM session
`

type CreateOrgSessionParams struct {
	OrgUserID            pgtype.UUID        `json:"org_user_id"`
	VerifiedPasswordHash string             `json:"verified_password_hash"`
	SessionTokenHash     []byte             `json:"session_token_hash"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	TenantID             string             `json:"tenant_id"`
}

type CreateOrgSessionRow struct {
	OrgSessionID    pgtype.UUID        `json:"org_session_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
}

func (q *Queries) CreateOrgSession(ctx context.Context, arg CreateOrgSessionParams) (CreateOrgSessionRow, error) {
	row := q.db.QueryRow(ctx, createOrgSession,
		arg.OrgUserID,
		arg.VerifiedPasswordHash,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.TenantID,
	)
	var i CreateOrgSessionRow
	err := row.Scan(
		&i.OrgSessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
	)
	return i, err
}

const deleteOrgSessionByTokenHash = `-- name: DeleteOrgSessionByTokenHash :exec
WITH deleted AS (
    DELETE FROM vetchium.org_sessions
    WHERE session_token_hash = $1
    RETURNING org_session_id, org_user_id
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $2,
        'org.session.revoked',
        'org_session',
        org_session_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        jsonb_build_object('reason', 'logout')
    FROM deleted
    RETURNING audit_event_id
)
SELECT 1 FROM audit
`

type DeleteOrgSessionByTokenHashParams struct {
	SessionTokenHash []byte `json:"session_token_hash"`
	TenantID         string `json:"tenant_id"`
}

func (q *Queries) DeleteOrgSessionByTokenHash(ctx context.Context, arg DeleteOrgSessionByTokenHashParams) error {
	_, err := q.db.Exec(ctx, deleteOrgSessionByTokenHash, arg.SessionTokenHash, arg.TenantID)
	return err
}

const getOrgLoginChallenge = `-- name: GetOrgLoginChallenge :one
SELECT
    c.org_login_challenge_id,
    c.org_user_id,
    t.secret_ciphertext,
    u.preferred_language
FROM vetchium.org_login_challenges AS c
JOIN vetchium.org_users AS u USING (org_user_id)
JOIN vetchium.org_user_totp_credentials AS t USING (org_user_id)
WHERE c.token_hash = $1
  AND c.active
  AND c.consumed_at IS NULL
  AND c.expires_at > now()
  AND u.org_user_state = 'active'
FOR UPDATE OF c
`

type GetOrgLoginChallengeRow struct {
	OrgLoginChallengeID pgtype.UUID `json:"org_login_challenge_id"`
	OrgUserID           pgtype.UUID `json:"org_user_id"`
	SecretCiphertext    []byte      `json:"secret_ciphertext"`
	PreferredLanguage   string      `json:"preferred_language"`
}

func (q *Queries) GetOrgLoginChallenge(ctx context.Context, tokenHash []byte) (GetOrgLoginChallengeRow, error) {
	row := q.db.QueryRow(ctx, getOrgLoginChallenge, tokenHash)
	var i GetOrgLoginChallengeRow
	err := row.Scan(
		&i.OrgLoginChallengeID,
		&i.OrgUserID,
		&i.SecretCiphertext,
		&i.PreferredLanguage,
	)
	return i, err
}

const getOrgPasswordForReauthentication = `-- name: GetOrgPasswordForReauthentication :one
SELECT p.password_hash
FROM vetchium.org_sessions AS s
JOIN vetchium.org_users AS u USING (org_user_id)
JOIN vetchium.org_user_passwords AS p USING (org_user_id)
WHERE s.org_session_id = $1
  AND s.org_user_id = $2
  AND s.expires_at > now()
  AND u.org_user_state = 'active'
`

type GetOrgPasswordForReauthenticationParams struct {
	OrgSessionID pgtype.UUID `json:"org_session_id"`
	OrgUserID    pgtype.UUID `json:"org_user_id"`
}

func (q *Queries) GetOrgPasswordForReauthentication(ctx context.Context, arg GetOrgPasswordForReauthenticationParams) (string, error) {
	row := q.db.QueryRow(ctx, getOrgPasswordForReauthentication, arg.OrgSessionID, arg.OrgUserID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getOrgUserForLogin = `-- name: GetOrgUserForLogin :one
SELECT
    u.org_user_id,
    u.org_did,
    u.org_user_state,
    u.disabled_reason,
    u.preferred_language,
    p.password_hash,
    (t.org_user_id IS NOT NULL)::boolean AS totp_enabled
FROM vetchium.org_domains AS d
JOIN vetchium.orgs AS o ON o.org_did = d.org_did
JOIN vetchium.org_users AS u
    ON u.org_did = o.org_did
   AND u.email_address = $1
JOIN vetchium.org_user_passwords AS p ON p.org_user_id = u.org_user_id
LEFT JOIN vetchium.org_user_totp_credentials AS t
    ON t.org_user_id = u.org_user_id
WHERE d.domain = $2
  AND o.org_state IN ('active', 'suspended')
  AND u.org_user_state IN ('active', 'disabled')
ORDER BY (d.domain_state = 'released'), d.created_at DESC
LIMIT 1
`

type GetOrgUserForLoginParams struct {
	EmailAddress string `json:"email_address"`
	Domain       string `json:"domain"`
}

type GetOrgUserForLoginRow struct {
	OrgUserID         pgtype.UUID          `json:"org_user_id"`
	OrgDid            pgtype.UUID          `json:"org_did"`
	OrgUserState      VetchiumOrgUserState `json:"org_user_state"`
	DisabledReason    pgtype.Text          `json:"disabled_reason"`
	PreferredLanguage string               `json:"preferred_language"`
	PasswordHash      string               `json:"password_hash"`
	TotpEnabled       bool                 `json:"totp_enabled"`
}

// A suspended Org's users can still sign in, to restore the domain. When a
// released domain was claimed by another local Org, the current owner wins.
func (q *Queries) GetOrgUserForLogin(ctx context.Context, arg GetOrgUserForLoginParams) (GetOrgUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getOrgUserForLogin, arg.EmailAddress, arg.Domain)
	var i GetOrgUserForLoginRow
	err := row.Scan(
		&i.OrgUserID,
		&i.OrgDid,
		&i.OrgUserState,
		&i.DisabledReason,
		&i.PreferredLanguage,
		&i.PasswordHash,
		&i.TotpEnabled,
	)
	return i, err
}

const lockOrgUserCredentialMutation = `-- name: LockOrgUserCredentialMutation :one
SELECT org_user_id
FROM vetchium.org_users
WHERE org_user_id = $1
FOR UPDATE
`

func (q *Queries) LockOrgUserCredentialMutation(ctx context.Context, orgUserID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockOrgUserCredentialMutation, orgUserID)
	var org_user_id pgtype.UUID
	err := row.Scan(&org_user_id)
	return org_user_id, err
}

const reauthenticateOrgSession = `-- name: ReauthenticateOrgSession :one
WITH updated AS (
    UPDATE vetchium.org_sessions AS s
    SET authenticated_at = now()
    FROM vetchium.org_users AS u, vetchium.org_user_passwords AS p
    WHERE s.org_session_id = $1
      AND s.org_user_id = $2
      AND s.expires_at > now()
      AND u.org_user_id = s.org_user_id
      AND p.org_user_id = s.org_user_id
      AND u.org_user_state = 'active'
      AND p.password_hash = $3
    RETURNING s.org_session_id, s.org_user_id, s.authenticated_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.session.reauthenticated',
        'org_session',
        org_session_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        jsonb_build_object('authentication_refreshed', true)
    FROM updated
)
SELECT authenticated_at FROM updated
`

type ReauthenticateOrgSessionParams struct {
	OrgSessionID         pgtype.UUID `json:"org_session_id"`
	OrgUserID            pgtype.UUID `json:"org_user_id"`
	VerifiedPasswordHash string      `json:"verified_password_hash"`
	TenantID             string      `json:"tenant_id"`
}

func (q *Queries) ReauthenticateOrgSession(ctx context.Context, arg ReauthenticateOrgSessionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, reauthenticateOrgSession,
		arg.OrgSessionID,
		arg.OrgUserID,
		arg.VerifiedPasswordHash,
		arg.TenantID,
	)
	var authenticated_at pgtype.Timestamptz
	err := row.Scan(&authenticated_at)
	return authenticated_at, err
}

const resolveOrgLoginChallengeUser = `-- name: ResolveOrgLoginChallengeUser :one
SELECT org_user_id
FROM vetchium.org_login_challenges
WHERE token_hash = $1
  AND active
  AND consumed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) ResolveOrgLoginChallengeUser(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveOrgLoginChallengeUser, tokenHash)
	var org_user_id pgtype.UUID
	err := row.Scan(&org_user_id)
	return org_user_id, err
}
