// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableOrgUsers = `-- name: DisableOrgUsers :one
WITH targets AS (
    SELECT u.org_user_id
    FROM vetchium.org_users AS u
    WHERE u.org_did = $1
      AND u.org_user_id = ANY($2::uuid[])
), keeps_superadmin AS (
    SELECT EXISTS (
        SELECT 1
        FROM vetchium.org_effective_permissions AS e
        JOIN vetchium.org_users AS u ON u.org_user_id = e.org_user_id
        WHERE u.org_did = $1
          AND e.permission = 'org:superadmin'
          AND u.org_user_state = 'active'
          AND u.org_user_id <> ALL($2::uuid[])
    ) AS ok
), updated AS (
    UPDATE vetchium.org_users AS u
    SET org_user_state = 'disabled',
        disabled_reason = 'manual',
        disabled_at = now(),
        disabled_by = $3,
        updated_at = now()
    FROM keeps_superadmin AS k
    WHERE u.org_user_id IN (SELECT org_user_id FROM targets)
      AND u.org_user_state = 'active'
      AND k.ok
    RETURNING u.org_user_id, u.email_address
), sessions AS (
    DELETE FROM vetchium.org_sessions
    WHERE org_user_id IN (SELECT org_user_id FROM updated)
), challenges AS (
    UPDATE vetchium.org_login_challenges
    SET active = false
    WHERE org_user_id IN (SELECT org_user_id FROM updated) AND active
), resets AS (
    UPDATE vetchium.org_password_reset_tokens
    SET active = false
    WHERE org_user_id IN (SELECT org_user_id FROM updated) AND active
), enrollments AS (
    UPDATE vetchium.org_totp_enrollments
    SET active = false
    WHERE org_user_id IN (SELECT org_user_id FROM updated) AND active
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.users.disabled',
        'org',
        $1::text,
        'org_user',
        $3::text,
        'orgs-api',
        jsonb_build_object(
            'email_addresses', changed.email_addresses,
            'reason', 'manual',
            'sessions_revoked', true
        )
    FROM (
        SELECT jsonb_agg(u.email_address ORDER BY u.email_address)
            AS email_addresses
        FROM updated AS u
        HAVING count(*) > 0
    ) AS changed
)
SELECT CASE
    WHEN NOT (SELECT ok FROM keeps_superadmin) THEN 'last-superadmin'
    ELSE 'ok'
END::text AS result
`

type DisableOrgUsersParams struct {
	OrgDid         pgtype.UUID   `json:"org_did"`
	OrgUserIds     []pgtype.UUID `json:"org_user_ids"`
	ActorOrgUserID pgtype.UUID   `json:"actor_org_user_id"`
	TenantID       string        `json:"tenant_id"`
}

// Disables every active target, or none: the Org must keep an active
// superadmin outside the set. Sessions and unfinished credential flows end
// with the account.
func (q *Queries) DisableOrgUsers(ctx context.Context, arg DisableOrgUsersParams) (string, error) {
	row := q.db.QueryRow(ctx, disableOrgUsers,
		arg.OrgDid,
		arg.OrgUserIds,
		arg.ActorOrgUserID,
		arg.TenantID,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}

const enableOrgUsers = `-- name: EnableOrgUsers :one
WITH disabled AS (
    SELECT u.org_user_id
    FROM vetchium.org_users AS u
    WHERE u.org_did = $1
      AND u.org_user_id = ANY($2::uuid[])
      AND u.org_user_state = 'disabled'
), fits AS (
    SELECT (
        $3::integer IS NULL
        OR vetchium.org_seats_in_use($1)
            + (SELECT count(*) FROM disabled) <= $3::integer
    ) AS ok
), updated AS (
    UPDATE vetchium.org_users AS u
    SET org_user_state = 'active',
        disabled_reason = NULL,
        disabled_at = NULL,
        disabled_by = NULL,
        updated_at = now()
    FROM fits
    WHERE u.org_user_id IN (SELECT org_user_id FROM disabled) AND fits.ok
    RETURNING u.org_user_id, u.email_address
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.users.enabled',
        'org',
        $1::text,
        'org_user',
        $5::text,
        'orgs-api',
        jsonb_build_object('email_addresses', changed.email_addresses)
    FROM (
        SELECT jsonb_agg(u.email_address ORDER BY u.email_address)
            AS email_addresses
        FROM updated AS u
        HAVING count(*) > 0
    ) AS changed
)
SELECT CASE
    WHEN NOT (SELECT ok FROM fits) THEN 'limit-reached'
    ELSE 'ok'
END::text AS result
`

type EnableOrgUsersParams struct {
	OrgDid         pgtype.UUID   `json:"org_did"`
	OrgUserIds     []pgtype.UUID `json:"org_user_ids"`
	SeatLimit      pgtype.Int4   `json:"seat_limit"`
	TenantID       string        `json:"tenant_id"`
	ActorOrgUserID string        `json:"actor_org_user_id"`
}

// Re-enables disabled targets (either reason) when the whole batch fits the
// cap; seat_limit is NULL for an unlimited Org.
func (q *Queries) EnableOrgUsers(ctx context.Context, arg EnableOrgUsersParams) (string, error) {
	row := q.db.QueryRow(ctx, enableOrgUsers,
		arg.OrgDid,
		arg.OrgUserIds,
		arg.SeatLimit,
		arg.TenantID,
		arg.ActorOrgUserID,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}

const getOrgUserSummary = `-- name: GetOrgUserSummary :one
SELECT
    o.org_plan_oid,
    o.google_sign_in_enabled,
    vetchium.org_seats_in_use(o.org_did)::bigint AS seats_in_use,
    count(*) FILTER (WHERE u.org_user_state = 'active')::bigint
        AS active_users,
    count(*) FILTER (
        WHERE u.org_user_state = 'disabled' AND u.disabled_reason = 'manual'
    )::bigint AS disabled_manual_users,
    count(*) FILTER (
        WHERE u.org_user_state = 'disabled'
          AND u.disabled_reason = 'nonpayment'
    )::bigint AS disabled_nonpayment_users,
    count(*) FILTER (
        WHERE u.org_user_state = 'active' AND NOT EXISTS (
            SELECT 1 FROM vetchium.org_user_permissions AS g
            WHERE g.org_user_id = u.org_user_id
        )
    )::bigint AS active_users_without_permissions
FROM vetchium.orgs AS o
LEFT JOIN vetchium.org_users AS u
    ON u.org_did = o.org_did AND u.org_user_state <> 'provisioning'
WHERE o.org_did = $1
GROUP BY o.org_did, o.org_plan_oid, o.google_sign_in_enabled
`

type GetOrgUserSummaryRow struct {
	OrgPlanOid                    string `json:"org_plan_oid"`
	GoogleSignInEnabled           bool   `json:"google_sign_in_enabled"`
	SeatsInUse                    int64  `json:"seats_in_use"`
	ActiveUsers                   int64  `json:"active_users"`
	DisabledManualUsers           int64  `json:"disabled_manual_users"`
	DisabledNonpaymentUsers       int64  `json:"disabled_nonpayment_users"`
	ActiveUsersWithoutPermissions int64  `json:"active_users_without_permissions"`
}

func (q *Queries) GetOrgUserSummary(ctx context.Context, orgDid pgtype.UUID) (GetOrgUserSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOrgUserSummary, orgDid)
	var i GetOrgUserSummaryRow
	err := row.Scan(
		&i.OrgPlanOid,
		&i.GoogleSignInEnabled,
		&i.SeatsInUse,
		&i.ActiveUsers,
		&i.DisabledManualUsers,
		&i.DisabledNonpaymentUsers,
		&i.ActiveUsersWithoutPermissions,
	)
	return i, err
}

const getOrgUsersForChange = `-- name: GetOrgUsersForChange :many
SELECT
    u.org_user_id,
    u.email_address,
    u.org_user_state,
    ARRAY(
        SELECT g.permission
        FROM vetchium.org_user_permissions AS g
        WHERE g.org_user_id = u.org_user_id
        ORDER BY g.permission
    )::text[] AS granted_permissions
FROM unnest($1::text[])
    WITH ORDINALITY AS wanted(email_address, position)
JOIN vetchium.org_users AS u
    ON u.org_did = $2
   AND u.email_address = wanted.email_address
   AND u.org_user_state <> 'provisioning'
ORDER BY wanted.position
`

type GetOrgUsersForChangeParams struct {
	EmailAddresses []string    `json:"email_addresses"`
	OrgDid         pgtype.UUID `json:"org_did"`
}

type GetOrgUsersForChangeRow struct {
	OrgUserID          pgtype.UUID          `json:"org_user_id"`
	EmailAddress       string               `json:"email_address"`
	OrgUserState       VetchiumOrgUserState `json:"org_user_state"`
	GrantedPermissions []string             `json:"granted_permissions"`
}

// Reads the users a change targets, in request order, once the caller holds
// the Org row lock. A missing address is simply absent from the result.
func (q *Queries) GetOrgUsersForChange(ctx context.Context, arg GetOrgUsersForChangeParams) ([]GetOrgUsersForChangeRow, error) {
	rows, err := q.db.Query(ctx, getOrgUsersForChange, arg.EmailAddresses, arg.OrgDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrgUsersForChangeRow
	for rows.Next() {
		var i GetOrgUsersForChangeRow
		if err := rows.Scan(
			&i.OrgUserID,
			&i.EmailAddress,
			&i.OrgUserState,
			&i.GrantedPermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgPermissionCatalog = `-- name: ListOrgPermissionCatalog :many
SELECT
    c.permission,
    ARRAY(
        SELECT i.implied_permission
        FROM vetchium.org_permission_implications AS i
        WHERE i.permission = c.permission
        ORDER BY i.implied_permission
    )::text[] AS implies
FROM vetchium.org_permission_catalog AS c
ORDER BY c.permission
`

type ListOrgPermissionCatalogRow struct {
	Permission string   `json:"permission"`
	Implies    []string `json:"implies"`
}

func (q *Queries) ListOrgPermissionCatalog(ctx context.Context) ([]ListOrgPermissionCatalogRow, error) {
	rows, err := q.db.Query(ctx, listOrgPermissionCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgPermissionCatalogRow
	for rows.Next() {
		var i ListOrgPermissionCatalogRow
		if err := rows.Scan(&i.Permission, &i.Implies); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgPermissionCounts = `-- name: ListOrgPermissionCounts :many
SELECT g.permission, count(*)::bigint AS users
FROM vetchium.org_user_permissions AS g
JOIN vetchium.org_users AS u ON u.org_user_id = g.org_user_id
WHERE u.org_did = $1
  AND u.org_user_state = 'active'
GROUP BY g.permission
ORDER BY g.permission
`

type ListOrgPermissionCountsRow struct {
	Permission string `json:"permission"`
	Users      int64  `json:"users"`
}

// Active users holding each directly granted permission.
func (q *Queries) ListOrgPermissionCounts(ctx context.Context, orgDid pgtype.UUID) ([]ListOrgPermissionCountsRow, error) {
	rows, err := q.db.Query(ctx, listOrgPermissionCounts, orgDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgPermissionCountsRow
	for rows.Next() {
		var i ListOrgPermissionCountsRow
		if err := rows.Scan(&i.Permission, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUsers = `-- name: ListOrgUsers :many
SELECT
    u.org_user_id,
    u.email_address,
    u.org_user_state,
    u.disabled_reason,
    u.created_at,
    u.last_login_at,
    ARRAY(
        SELECT g.permission
        FROM vetchium.org_user_permissions AS g
        WHERE g.org_user_id = u.org_user_id
        ORDER BY g.permission
    )::text[] AS granted_permissions,
    ARRAY(
        SELECT e.permission
        FROM vetchium.org_effective_permissions AS e
        WHERE e.org_user_id = u.org_user_id
        ORDER BY e.permission
    )::text[] AS effective_permissions
FROM vetchium.org_users AS u
WHERE u.org_did = $1
  AND u.org_user_state <> 'provisioning'
  AND (
      $2::text IS NULL
      OR strpos(u.email_address, $2::text) > 0
  )
  AND (
      $3::text IS NULL
      OR ($3::text = 'active'
          AND u.org_user_state = 'active')
      OR ($3::text = 'disabled-manual'
          AND u.org_user_state = 'disabled' AND u.disabled_reason = 'manual')
      OR ($3::text = 'disabled-nonpayment'
          AND u.org_user_state = 'disabled'
          AND u.disabled_reason = 'nonpayment')
  )
  AND (
      $4::text IS NULL
      OR EXISTS (
          SELECT 1
          FROM vetchium.org_user_permissions AS g
          WHERE g.org_user_id = u.org_user_id
            AND g.permission = $4::text
      )
  )
  AND (
      NOT $5::boolean
      OR NOT EXISTS (
          SELECT 1
          FROM vetchium.org_user_permissions AS g
          WHERE g.org_user_id = u.org_user_id
      )
  )
  AND (
      $6::text IS NULL
      OR CASE
          WHEN $7::text = 'email' THEN
              CASE WHEN $8::boolean
                  THEN u.email_address < $6::text
                  ELSE u.email_address > $6::text
              END
          ELSE
              CASE WHEN $8::boolean
                  THEN (u.created_at, u.email_address) <
                      ($9::timestamptz,
                       $6::text)
                  ELSE (u.created_at, u.email_address) >
                      ($9::timestamptz,
                       $6::text)
              END
      END
  )
ORDER BY
    (CASE WHEN $7::text = 'joined'
        AND NOT $8::boolean THEN u.created_at END) ASC,
    (CASE WHEN $7::text = 'joined'
        AND $8::boolean THEN u.created_at END) DESC,
    (CASE WHEN NOT $8::boolean THEN u.email_address END) ASC,
    (CASE WHEN $8::boolean THEN u.email_address END) DESC
LIMIT $10
`

type ListOrgUsersParams struct {
	OrgDid            pgtype.UUID        `json:"org_did"`
	Search            pgtype.Text        `json:"search"`
	StateFilter       pgtype.Text        `json:"state_filter"`
	PermissionFilter  pgtype.Text        `json:"permission_filter"`
	NoPermissions     bool               `json:"no_permissions"`
	AfterEmailAddress pgtype.Text        `json:"after_email_address"`
	SortBy            string             `json:"sort_by"`
	Descending        bool               `json:"descending"`
	AfterCreatedAt    pgtype.Timestamptz `json:"after_created_at"`
	PageLimit         int32              `json:"page_limit"`
}

type ListOrgUsersRow struct {
	OrgUserID            pgtype.UUID          `json:"org_user_id"`
	EmailAddress         string               `json:"email_address"`
	OrgUserState         VetchiumOrgUserState `json:"org_user_state"`
	DisabledReason       pgtype.Text          `json:"disabled_reason"`
	CreatedAt            pgtype.Timestamptz   `json:"created_at"`
	LastLoginAt          pgtype.Timestamptz   `json:"last_login_at"`
	GrantedPermissions   []string             `json:"granted_permissions"`
	EffectivePermissions []string             `json:"effective_permissions"`
}

// Keyset-paginated member list. The sort key is the address, or the join date
// with the address as tie-breaker. The permission filter matches a direct
// grant, which is what the role label and the summary counts are built from.
func (q *Queries) ListOrgUsers(ctx context.Context, arg ListOrgUsersParams) ([]ListOrgUsersRow, error) {
	rows, err := q.db.Query(ctx, listOrgUsers,
		arg.OrgDid,
		arg.Search,
		arg.StateFilter,
		arg.PermissionFilter,
		arg.NoPermissions,
		arg.AfterEmailAddress,
		arg.SortBy,
		arg.Descending,
		arg.AfterCreatedAt,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgUsersRow
	for rows.Next() {
		var i ListOrgUsersRow
		if err := rows.Scan(
			&i.OrgUserID,
			&i.EmailAddress,
			&i.OrgUserState,
			&i.DisabledReason,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.GrantedPermissions,
			&i.EffectivePermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgUserPermissions = `-- name: SetOrgUserPermissions :one
WITH targets AS (
    SELECT u.org_user_id, u.org_user_state
    FROM vetchium.org_users AS u
    WHERE u.org_did = $1
      AND u.org_user_id = ANY($2::uuid[])
), keeps_superadmin AS (
    SELECT (
        EXISTS (
            SELECT 1
            FROM vetchium.org_effective_permissions AS e
            JOIN vetchium.org_users AS u ON u.org_user_id = e.org_user_id
            WHERE u.org_did = $1
              AND e.permission = 'org:superadmin'
              AND u.org_user_state = 'active'
              AND u.org_user_id <> ALL($2::uuid[])
        )
        OR (
            'org:superadmin' = ANY($3::text[])
            AND EXISTS (
                SELECT 1 FROM targets WHERE org_user_state = 'active'
            )
        )
    ) AS ok
), deleted AS (
    -- Sibling data-modifying CTEs run in no guaranteed order, so the two
    -- writes never touch the same key: drop only grants that go, add only
    -- grants that are new, and leave the ones that stay alone.
    DELETE FROM vetchium.org_user_permissions AS p
    WHERE p.org_user_id IN (SELECT org_user_id FROM targets)
      AND p.permission <> ALL($3::text[])
      AND (SELECT ok FROM keeps_superadmin)
), inserted AS (
    INSERT INTO vetchium.org_user_permissions (org_user_id, permission)
    SELECT t.org_user_id, requested.permission
    FROM targets AS t
    CROSS JOIN unnest($3::text[]) AS requested(permission)
    WHERE (SELECT ok FROM keeps_superadmin)
    ON CONFLICT (org_user_id, permission) DO NOTHING
    RETURNING org_user_id
), touched AS (
    UPDATE vetchium.org_users AS u
    SET updated_at = now()
    WHERE u.org_user_id IN (SELECT org_user_id FROM targets)
      AND (SELECT ok FROM keeps_superadmin)
    RETURNING u.email_address
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.users.permissions_set',
        'org',
        $1::text,
        'org_user',
        $5::text,
        'orgs-api',
        jsonb_build_object(
            'email_addresses', changed.email_addresses,
            'permissions', to_jsonb($3::text[])
        )
    FROM (
        SELECT jsonb_agg(t.email_address ORDER BY t.email_address)
            AS email_addresses
        FROM touched AS t
        HAVING count(*) > 0
    ) AS changed
)
SELECT CASE
    WHEN NOT (SELECT ok FROM keeps_superadmin) THEN 'last-superadmin'
    ELSE 'ok'
END::text AS result
`

type SetOrgUserPermissionsParams struct {
	OrgDid         pgtype.UUID   `json:"org_did"`
	OrgUserIds     []pgtype.UUID `json:"org_user_ids"`
	Permissions    []string      `json:"permissions"`
	TenantID       string        `json:"tenant_id"`
	ActorOrgUserID string        `json:"actor_org_user_id"`
}

// Replaces the direct grants of every target with one set. After the change
// the Org must still have an active superadmin: one outside the set, or a
// target that keeps the grant.
func (q *Queries) SetOrgUserPermissions(ctx context.Context, arg SetOrgUserPermissionsParams) (string, error) {
	row := q.db.QueryRow(ctx, setOrgUserPermissions,
		arg.OrgDid,
		arg.OrgUserIds,
		arg.Permissions,
		arg.TenantID,
		arg.ActorOrgUserID,
	)
	var result string
	err := row.Scan(&result)
	return result, err
}
