// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_domains.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginOrgDomainReclaim = `-- name: BeginOrgDomainReclaim :one
WITH updated AS (
    UPDATE vetchium.org_domains
    SET domain_state = 'reclaiming',
        directory_command_id = $1,
        updated_at = now()
    WHERE org_did = $2
      AND domain_state = 'released'
    RETURNING org_did, domain
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'org.domain.reclaim-started',
        'org_domain',
        org_did::text,
        $4,
        $5,
        $6,
        jsonb_build_object(
            'domain', domain,
            'directory_command_id', $1::uuid
        )
    FROM updated
)
SELECT EXISTS (SELECT 1 FROM updated) AS started
`

type BeginOrgDomainReclaimParams struct {
	DirectoryCommandID pgtype.UUID `json:"directory_command_id"`
	OrgDid             pgtype.UUID `json:"org_did"`
	TenantID           string      `json:"tenant_id"`
	ActorType          string      `json:"actor_type"`
	ActorID            pgtype.Text `json:"actor_id"`
	Source             string      `json:"source"`
}

func (q *Queries) BeginOrgDomainReclaim(ctx context.Context, arg BeginOrgDomainReclaimParams) (bool, error) {
	row := q.db.QueryRow(ctx, beginOrgDomainReclaim,
		arg.DirectoryCommandID,
		arg.OrgDid,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var started bool
	err := row.Scan(&started)
	return started, err
}

const beginOrgDomainRelease = `-- name: BeginOrgDomainRelease :one
WITH updated AS (
    UPDATE vetchium.org_domains AS d
    SET domain_state = 'releasing',
        directory_command_id = $1,
        updated_at = now()
    WHERE d.org_did = $2
      AND d.domain_state = 'failing'
      AND d.failing_since <= $3
    RETURNING d.org_did, d.domain, d.failing_since
), suspended AS (
    UPDATE vetchium.orgs AS o
    SET org_state = 'suspended',
        suspended_at = now(),
        updated_at = now()
    FROM updated
    WHERE o.org_did = updated.org_did
      AND o.org_state = 'active'
    RETURNING o.org_did
), notices AS (
    INSERT INTO vetchium.org_email_outbox (
        kind, recipient_email_address, preferred_language, payload_ciphertext
    )
    SELECT
        'org-suspended',
        u.email_address,
        u.preferred_language,
        $4
    FROM suspended AS s
    JOIN vetchium.org_users AS u ON u.org_did = s.org_did
    WHERE u.org_user_state = 'active'
      AND EXISTS (
          SELECT 1 FROM vetchium.org_effective_permissions AS ep
          WHERE ep.org_user_id = u.org_user_id
            AND ep.permission = 'org:superadmin'
      )
    RETURNING org_email_outbox_id
), domain_audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $5,
        'org.domain.release-started',
        'org_domain',
        org_did::text,
        'worker',
        'verify-org-domains',
        'workers',
        jsonb_build_object(
            'domain', domain,
            'failing_since', failing_since,
            'directory_command_id', $1::uuid
        )
    FROM updated
), org_audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $5,
        'org.suspended',
        'org',
        org_did::text,
        'worker',
        'verify-org-domains',
        'workers',
        jsonb_build_object(
            'reason', 'domain_failing_past_grace',
            'notices_queued', (SELECT count(*) FROM notices)
        )
    FROM suspended
)
SELECT EXISTS (SELECT 1 FROM updated) AS started
`

type BeginOrgDomainReleaseParams struct {
	DirectoryCommandID      pgtype.UUID        `json:"directory_command_id"`
	OrgDid                  pgtype.UUID        `json:"org_did"`
	FailingBefore           pgtype.Timestamptz `json:"failing_before"`
	NoticePayloadCiphertext []byte             `json:"notice_payload_ciphertext"`
	TenantID                string             `json:"tenant_id"`
}

// Suspends the Org locally before the global release is sent, so the Org is
// never treated as owning a domain the directory may already have released.
func (q *Queries) BeginOrgDomainRelease(ctx context.Context, arg BeginOrgDomainReleaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, beginOrgDomainRelease,
		arg.DirectoryCommandID,
		arg.OrgDid,
		arg.FailingBefore,
		arg.NoticePayloadCiphertext,
		arg.TenantID,
	)
	var started bool
	err := row.Scan(&started)
	return started, err
}

const completeOrgDomainReclaim = `-- name: CompleteOrgDomainReclaim :one
WITH updated AS (
    UPDATE vetchium.org_domains AS d
    SET domain_state = 'verified',
        directory_command_id = NULL,
        released_at = NULL,
        consecutive_failures = 0,
        consecutive_inconclusive = 0,
        last_verified_at = now(),
        last_conclusive_at = now(),
        next_check_at = $1,
        updated_at = now()
    WHERE d.org_did = $2
      AND d.domain_state = 'reclaiming'
      AND d.directory_command_id = $3
    RETURNING d.org_did, d.domain
), reactivated AS (
    UPDATE vetchium.orgs AS o
    SET org_state = 'active',
        suspended_at = NULL,
        updated_at = now()
    FROM updated
    WHERE o.org_did = updated.org_did
      AND o.org_state = 'suspended'
    RETURNING o.org_did
), domain_audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.domain.reclaimed',
        'org_domain',
        org_did::text,
        $5,
        $6,
        $7,
        jsonb_build_object('domain', domain)
    FROM updated
), org_audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.reactivated',
        'org',
        org_did::text,
        $5,
        $6,
        $7,
        jsonb_build_object('reason', 'domain_reclaimed')
    FROM reactivated
)
SELECT EXISTS (SELECT 1 FROM updated) AS completed
`

type CompleteOrgDomainReclaimParams struct {
	NextCheckAt        pgtype.Timestamptz `json:"next_check_at"`
	OrgDid             pgtype.UUID        `json:"org_did"`
	DirectoryCommandID pgtype.UUID        `json:"directory_command_id"`
	TenantID           string             `json:"tenant_id"`
	ActorType          string             `json:"actor_type"`
	ActorID            pgtype.Text        `json:"actor_id"`
	Source             string             `json:"source"`
}

func (q *Queries) CompleteOrgDomainReclaim(ctx context.Context, arg CompleteOrgDomainReclaimParams) (bool, error) {
	row := q.db.QueryRow(ctx, completeOrgDomainReclaim,
		arg.NextCheckAt,
		arg.OrgDid,
		arg.DirectoryCommandID,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var completed bool
	err := row.Scan(&completed)
	return completed, err
}

const completeOrgDomainRelease = `-- name: CompleteOrgDomainRelease :one
WITH updated AS (
    UPDATE vetchium.org_domains
    SET domain_state = 'released',
        directory_command_id = NULL,
        released_at = now(),
        failing_since = NULL,
        consecutive_failures = 0,
        consecutive_inconclusive = 0,
        next_check_at = $1,
        updated_at = now()
    WHERE org_did = $2
      AND domain_state = 'releasing'
      AND directory_command_id = $3
    RETURNING org_did, domain
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.domain.released',
        'org_domain',
        org_did::text,
        $5,
        $6,
        $7,
        jsonb_build_object(
            'domain', domain,
            'directory_command_id', $3::uuid
        )
    FROM updated
)
SELECT EXISTS (SELECT 1 FROM updated) AS completed
`

type CompleteOrgDomainReleaseParams struct {
	NextCheckAt        pgtype.Timestamptz `json:"next_check_at"`
	OrgDid             pgtype.UUID        `json:"org_did"`
	DirectoryCommandID pgtype.UUID        `json:"directory_command_id"`
	TenantID           string             `json:"tenant_id"`
	ActorType          string             `json:"actor_type"`
	ActorID            pgtype.Text        `json:"actor_id"`
	Source             string             `json:"source"`
}

func (q *Queries) CompleteOrgDomainRelease(ctx context.Context, arg CompleteOrgDomainReleaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, completeOrgDomainRelease,
		arg.NextCheckAt,
		arg.OrgDid,
		arg.DirectoryCommandID,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var completed bool
	err := row.Scan(&completed)
	return completed, err
}

const getOrgDomainForCheck = `-- name: GetOrgDomainForCheck :one
SELECT
    d.org_did,
    d.domain,
    d.verification_token,
    d.domain_state,
    d.last_conclusive_at,
    d.consecutive_inconclusive
FROM vetchium.org_domains AS d
JOIN vetchium.orgs AS o ON o.org_did = d.org_did
WHERE d.org_did = $1
  AND o.org_state IN ('active', 'suspended')
`

type GetOrgDomainForCheckRow struct {
	OrgDid                  pgtype.UUID            `json:"org_did"`
	Domain                  string                 `json:"domain"`
	VerificationToken       string                 `json:"verification_token"`
	DomainState             VetchiumOrgDomainState `json:"domain_state"`
	LastConclusiveAt        pgtype.Timestamptz     `json:"last_conclusive_at"`
	ConsecutiveInconclusive int32                  `json:"consecutive_inconclusive"`
}

func (q *Queries) GetOrgDomainForCheck(ctx context.Context, orgDid pgtype.UUID) (GetOrgDomainForCheckRow, error) {
	row := q.db.QueryRow(ctx, getOrgDomainForCheck, orgDid)
	var i GetOrgDomainForCheckRow
	err := row.Scan(
		&i.OrgDid,
		&i.Domain,
		&i.VerificationToken,
		&i.DomainState,
		&i.LastConclusiveAt,
		&i.ConsecutiveInconclusive,
	)
	return i, err
}

const listDueOrgDomains = `-- name: ListDueOrgDomains :many

SELECT
    d.org_did,
    d.domain,
    d.verification_token,
    d.domain_state,
    d.last_conclusive_at,
    d.consecutive_inconclusive
FROM vetchium.org_domains AS d
JOIN vetchium.orgs AS o ON o.org_did = d.org_did
WHERE d.next_check_at <= now()
  AND d.domain_state IN ('verified', 'failing', 'released')
  AND o.org_state IN ('active', 'suspended')
ORDER BY d.next_check_at, d.org_did
LIMIT 25
`

type ListDueOrgDomainsRow struct {
	OrgDid                  pgtype.UUID            `json:"org_did"`
	Domain                  string                 `json:"domain"`
	VerificationToken       string                 `json:"verification_token"`
	DomainState             VetchiumOrgDomainState `json:"domain_state"`
	LastConclusiveAt        pgtype.Timestamptz     `json:"last_conclusive_at"`
	ConsecutiveInconclusive int32                  `json:"consecutive_inconclusive"`
}

// Domain re-verification. Every write is guarded by the state the caller
// read, so a scheduled check and a superadmin's check-now cannot both apply a
// stale result.
func (q *Queries) ListDueOrgDomains(ctx context.Context) ([]ListDueOrgDomainsRow, error) {
	rows, err := q.db.Query(ctx, listDueOrgDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueOrgDomainsRow
	for rows.Next() {
		var i ListDueOrgDomainsRow
		if err := rows.Scan(
			&i.OrgDid,
			&i.Domain,
			&i.VerificationToken,
			&i.DomainState,
			&i.LastConclusiveAt,
			&i.ConsecutiveInconclusive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgDomainsPastGrace = `-- name: ListOrgDomainsPastGrace :many
SELECT org_did, domain, verification_token
FROM vetchium.org_domains
WHERE domain_state = 'failing'
  AND failing_since <= $1
ORDER BY failing_since, org_did
LIMIT 25
`

type ListOrgDomainsPastGraceRow struct {
	OrgDid            pgtype.UUID `json:"org_did"`
	Domain            string      `json:"domain"`
	VerificationToken string      `json:"verification_token"`
}

func (q *Queries) ListOrgDomainsPastGrace(ctx context.Context, failingBefore pgtype.Timestamptz) ([]ListOrgDomainsPastGraceRow, error) {
	rows, err := q.db.Query(ctx, listOrgDomainsPastGrace, failingBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgDomainsPastGraceRow
	for rows.Next() {
		var i ListOrgDomainsPastGraceRow
		if err := rows.Scan(&i.OrgDid, &i.Domain, &i.VerificationToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrgDomainCommands = `-- name: ListPendingOrgDomainCommands :many
SELECT org_did, domain, domain_state, directory_command_id
FROM vetchium.org_domains
WHERE domain_state IN ('releasing', 'reclaiming')
ORDER BY updated_at, org_did
LIMIT 25
`

type ListPendingOrgDomainCommandsRow struct {
	OrgDid             pgtype.UUID            `json:"org_did"`
	Domain             string                 `json:"domain"`
	DomainState        VetchiumOrgDomainState `json:"domain_state"`
	DirectoryCommandID pgtype.UUID            `json:"directory_command_id"`
}

func (q *Queries) ListPendingOrgDomainCommands(ctx context.Context) ([]ListPendingOrgDomainCommandsRow, error) {
	rows, err := q.db.Query(ctx, listPendingOrgDomainCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOrgDomainCommandsRow
	for rows.Next() {
		var i ListPendingOrgDomainCommandsRow
		if err := rows.Scan(
			&i.OrgDid,
			&i.Domain,
			&i.DomainState,
			&i.DirectoryCommandID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOrgDomainAbsent = `-- name: RecordOrgDomainAbsent :one
WITH updated AS (
    UPDATE vetchium.org_domains AS d
    SET consecutive_failures = d.consecutive_failures + 1,
        consecutive_inconclusive = 0,
        last_conclusive_at = now(),
        domain_state = CASE
            WHEN d.domain_state = 'verified'
                AND d.consecutive_failures + 1
                    >= $1::integer
                THEN 'failing'::vetchium.org_domain_state
            ELSE d.domain_state
        END,
        failing_since = CASE
            WHEN d.domain_state = 'verified'
                AND d.consecutive_failures + 1
                    >= $1::integer
                THEN now()
            ELSE d.failing_since
        END,
        next_check_at = $2,
        updated_at = now()
    WHERE d.org_did = $3
      AND d.domain_state = $4
      AND d.domain_state IN ('verified', 'failing')
    RETURNING d.org_did, d.domain, d.domain_state, d.consecutive_failures
), became_failing AS (
    SELECT org_did, domain
    FROM updated
    WHERE domain_state = 'failing'
      AND $4::vetchium.org_domain_state = 'verified'
), notices AS (
    INSERT INTO vetchium.org_email_outbox (
        kind, recipient_email_address, preferred_language, payload_ciphertext
    )
    SELECT
        'domain-failing',
        u.email_address,
        u.preferred_language,
        $5
    FROM became_failing AS f
    JOIN vetchium.org_users AS u ON u.org_did = f.org_did
    WHERE u.org_user_state = 'active'
      AND EXISTS (
          SELECT 1 FROM vetchium.org_effective_permissions AS ep
          WHERE ep.org_user_id = u.org_user_id
            AND ep.permission = 'org:superadmin'
      )
    RETURNING org_email_outbox_id
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $6,
        'org.domain.checked',
        'org_domain',
        org_did::text,
        $7,
        $8,
        $9,
        jsonb_build_object(
            'domain', domain,
            'result', 'absent',
            'previous_state', $4::text,
            'state', domain_state,
            'consecutive_failures', consecutive_failures,
            'notices_queued', (SELECT count(*) FROM notices)
        )
    FROM updated
)
SELECT
    EXISTS (SELECT 1 FROM updated) AS recorded,
    EXISTS (SELECT 1 FROM became_failing) AS became_failing
`

type RecordOrgDomainAbsentParams struct {
	FailureThreshold        int32                  `json:"failure_threshold"`
	NextCheckAt             pgtype.Timestamptz     `json:"next_check_at"`
	OrgDid                  pgtype.UUID            `json:"org_did"`
	ExpectedState           VetchiumOrgDomainState `json:"expected_state"`
	NoticePayloadCiphertext []byte                 `json:"notice_payload_ciphertext"`
	TenantID                string                 `json:"tenant_id"`
	ActorType               string                 `json:"actor_type"`
	ActorID                 pgtype.Text            `json:"actor_id"`
	Source                  string                 `json:"source"`
}

type RecordOrgDomainAbsentRow struct {
	Recorded      bool `json:"recorded"`
	BecameFailing bool `json:"became_failing"`
}

// Reaching the failure threshold moves a verified domain to failing and
// queues one notice to each active superadmin in the same transaction, so the
// notice is sent exactly once per failing period.
func (q *Queries) RecordOrgDomainAbsent(ctx context.Context, arg RecordOrgDomainAbsentParams) (RecordOrgDomainAbsentRow, error) {
	row := q.db.QueryRow(ctx, recordOrgDomainAbsent,
		arg.FailureThreshold,
		arg.NextCheckAt,
		arg.OrgDid,
		arg.ExpectedState,
		arg.NoticePayloadCiphertext,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var i RecordOrgDomainAbsentRow
	err := row.Scan(&i.Recorded, &i.BecameFailing)
	return i, err
}

const recordOrgDomainInconclusive = `-- name: RecordOrgDomainInconclusive :one
WITH updated AS (
    UPDATE vetchium.org_domains
    SET consecutive_inconclusive = consecutive_inconclusive + 1,
        next_check_at = $1,
        updated_at = now()
    WHERE org_did = $2
      AND domain_state = $3
      AND domain_state IN ('verified', 'failing', 'released')
    RETURNING org_did, domain, consecutive_inconclusive
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.domain.checked',
        'org_domain',
        org_did::text,
        $5,
        $6,
        $7,
        jsonb_build_object(
            'domain', domain,
            'result', 'inconclusive',
            'state', $3::text,
            'consecutive_inconclusive', consecutive_inconclusive
        )
    FROM updated
)
SELECT EXISTS (SELECT 1 FROM updated) AS recorded
`

type RecordOrgDomainInconclusiveParams struct {
	NextCheckAt   pgtype.Timestamptz     `json:"next_check_at"`
	OrgDid        pgtype.UUID            `json:"org_did"`
	ExpectedState VetchiumOrgDomainState `json:"expected_state"`
	TenantID      string                 `json:"tenant_id"`
	ActorType     string                 `json:"actor_type"`
	ActorID       pgtype.Text            `json:"actor_id"`
	Source        string                 `json:"source"`
}

func (q *Queries) RecordOrgDomainInconclusive(ctx context.Context, arg RecordOrgDomainInconclusiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordOrgDomainInconclusive,
		arg.NextCheckAt,
		arg.OrgDid,
		arg.ExpectedState,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var recorded bool
	err := row.Scan(&recorded)
	return recorded, err
}

const recordOrgDomainPresent = `-- name: RecordOrgDomainPresent :one
WITH updated AS (
    UPDATE vetchium.org_domains
    SET domain_state = 'verified',
        consecutive_failures = 0,
        consecutive_inconclusive = 0,
        last_verified_at = now(),
        last_conclusive_at = now(),
        failing_since = NULL,
        next_check_at = $1,
        updated_at = now()
    WHERE org_did = $2
      AND domain_state = $3
      AND domain_state IN ('verified', 'failing')
    RETURNING org_did, domain
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.domain.checked',
        'org_domain',
        org_did::text,
        $5,
        $6,
        $7,
        jsonb_build_object(
            'domain', domain,
            'result', 'present',
            'previous_state', $3::text,
            'state', 'verified'
        )
    FROM updated
)
SELECT EXISTS (SELECT 1 FROM updated) AS recorded
`

type RecordOrgDomainPresentParams struct {
	NextCheckAt   pgtype.Timestamptz     `json:"next_check_at"`
	OrgDid        pgtype.UUID            `json:"org_did"`
	ExpectedState VetchiumOrgDomainState `json:"expected_state"`
	TenantID      string                 `json:"tenant_id"`
	ActorType     string                 `json:"actor_type"`
	ActorID       pgtype.Text            `json:"actor_id"`
	Source        string                 `json:"source"`
}

func (q *Queries) RecordOrgDomainPresent(ctx context.Context, arg RecordOrgDomainPresentParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordOrgDomainPresent,
		arg.NextCheckAt,
		arg.OrgDid,
		arg.ExpectedState,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var recorded bool
	err := row.Scan(&recorded)
	return recorded, err
}

const recordReleasedOrgDomainAbsent = `-- name: RecordReleasedOrgDomainAbsent :one
WITH updated AS (
    UPDATE vetchium.org_domains
    SET consecutive_inconclusive = 0,
        last_conclusive_at = now(),
        next_check_at = $1,
        updated_at = now()
    WHERE org_did = $2
      AND domain_state = 'released'
    RETURNING org_did, domain
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'org.domain.checked',
        'org_domain',
        org_did::text,
        $4,
        $5,
        $6,
        jsonb_build_object(
            'domain', domain, 'result', 'absent', 'state', 'released'
        )
    FROM updated
)
SELECT EXISTS (SELECT 1 FROM updated) AS recorded
`

type RecordReleasedOrgDomainAbsentParams struct {
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
	OrgDid      pgtype.UUID        `json:"org_did"`
	TenantID    string             `json:"tenant_id"`
	ActorType   string             `json:"actor_type"`
	ActorID     pgtype.Text        `json:"actor_id"`
	Source      string             `json:"source"`
}

// A released domain holds no claim, so a missing record only reschedules the
// next attempt to restore it.
func (q *Queries) RecordReleasedOrgDomainAbsent(ctx context.Context, arg RecordReleasedOrgDomainAbsentParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordReleasedOrgDomainAbsent,
		arg.NextCheckAt,
		arg.OrgDid,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var recorded bool
	err := row.Scan(&recorded)
	return recorded, err
}

const rejectOrgDomainReclaim = `-- name: RejectOrgDomainReclaim :one
WITH updated AS (
    UPDATE vetchium.org_domains
    SET domain_state = 'released',
        directory_command_id = NULL,
        next_check_at = $1,
        updated_at = now()
    WHERE org_did = $2
      AND domain_state = 'reclaiming'
      AND directory_command_id = $3
    RETURNING org_did, domain
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $4,
        'org.domain.reclaim-rejected',
        'org_domain',
        org_did::text,
        $5,
        $6,
        $7,
        jsonb_build_object('domain', domain, 'reason', 'owned_by_another_org')
    FROM updated
)
SELECT EXISTS (SELECT 1 FROM updated) AS rejected
`

type RejectOrgDomainReclaimParams struct {
	NextCheckAt        pgtype.Timestamptz `json:"next_check_at"`
	OrgDid             pgtype.UUID        `json:"org_did"`
	DirectoryCommandID pgtype.UUID        `json:"directory_command_id"`
	TenantID           string             `json:"tenant_id"`
	ActorType          string             `json:"actor_type"`
	ActorID            pgtype.Text        `json:"actor_id"`
	Source             string             `json:"source"`
}

func (q *Queries) RejectOrgDomainReclaim(ctx context.Context, arg RejectOrgDomainReclaimParams) (bool, error) {
	row := q.db.QueryRow(ctx, rejectOrgDomainReclaim,
		arg.NextCheckAt,
		arg.OrgDid,
		arg.DirectoryCommandID,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Source,
	)
	var rejected bool
	err := row.Scan(&rejected)
	return rejected, err
}
