// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_totp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmOrgTOTPEnrollment = `-- name: ConfirmOrgTOTPEnrollment :one
WITH enrollment AS (
    SELECT e.org_totp_enrollment_id, e.org_user_id
    FROM vetchium.org_totp_enrollments AS e
    WHERE e.org_totp_enrollment_id = $1
      AND e.org_user_id = $2
      AND e.active
      AND e.consumed_at IS NULL
      AND e.expires_at > now()
    FOR UPDATE
), enabled AS (
    INSERT INTO vetchium.org_user_totp_credentials (
        org_user_id,
        secret_ciphertext,
        last_timestep
    )
    SELECT
        org_user_id,
        $3,
        $4
    FROM enrollment
    ON CONFLICT (org_user_id) DO NOTHING
    RETURNING org_user_id
), consumed AS (
    UPDATE vetchium.org_totp_enrollments
    SET consumed_at = now(),
        active = false
    WHERE org_totp_enrollment_id IN (
        SELECT org_totp_enrollment_id FROM enrollment
    )
      AND EXISTS (SELECT 1 FROM enabled)
    RETURNING org_user_id
), deleted_codes AS (
    DELETE FROM vetchium.org_totp_recovery_codes
    WHERE org_user_id IN (SELECT org_user_id FROM enabled)
), inserted_codes AS (
    INSERT INTO vetchium.org_totp_recovery_codes (org_user_id, code_hash)
    SELECT e.org_user_id, code_hash
    FROM enabled AS e
    CROSS JOIN unnest($5::bytea[]) AS code_hash
    RETURNING org_user_id
), sessions AS (
    DELETE FROM vetchium.org_sessions
    WHERE org_user_id IN (SELECT org_user_id FROM enabled)
      AND org_session_id <> $6
), challenges AS (
    UPDATE vetchium.org_login_challenges
    SET active = false
    WHERE org_user_id IN (SELECT org_user_id FROM enabled)
      AND active
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $7,
        'org.totp.enabled',
        'org_user',
        org_user_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        $8,
        jsonb_build_object('recovery_codes_created', 10)
    FROM consumed
    WHERE (SELECT count(*) FROM inserted_codes) = 10
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS confirmed
`

type ConfirmOrgTOTPEnrollmentParams struct {
	OrgTotpEnrollmentID pgtype.UUID `json:"org_totp_enrollment_id"`
	OrgUserID           pgtype.UUID `json:"org_user_id"`
	SecretCiphertext    []byte      `json:"secret_ciphertext"`
	TotpTimestep        pgtype.Int8 `json:"totp_timestep"`
	RecoveryCodeHashes  [][]byte    `json:"recovery_code_hashes"`
	CurrentOrgSessionID pgtype.UUID `json:"current_org_session_id"`
	TenantID            string      `json:"tenant_id"`
	IdempotencyKey      pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) ConfirmOrgTOTPEnrollment(ctx context.Context, arg ConfirmOrgTOTPEnrollmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, confirmOrgTOTPEnrollment,
		arg.OrgTotpEnrollmentID,
		arg.OrgUserID,
		arg.SecretCiphertext,
		arg.TotpTimestep,
		arg.RecoveryCodeHashes,
		arg.CurrentOrgSessionID,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var confirmed bool
	err := row.Scan(&confirmed)
	return confirmed, err
}

const createOrgTOTPEnrollment = `-- name: CreateOrgTOTPEnrollment :one
WITH eligible_user AS (
    SELECT u.org_user_id
    FROM vetchium.org_users AS u
    WHERE u.org_user_id = $1
      AND u.org_user_state = 'active'
      AND NOT EXISTS (
          SELECT 1 FROM vetchium.org_user_totp_credentials AS t
          WHERE t.org_user_id = u.org_user_id
      )
), enrollment AS (
    INSERT INTO vetchium.org_totp_enrollments (
        org_user_id,
        token_hash,
        secret_ciphertext,
        expires_at
    )
    SELECT
        org_user_id,
        $2,
        $3,
        $4
    FROM eligible_user
    ON CONFLICT (org_user_id) WHERE active DO UPDATE
    SET token_hash = EXCLUDED.token_hash,
        secret_ciphertext = EXCLUDED.secret_ciphertext,
        created_at = now(),
        expires_at = EXCLUDED.expires_at,
        consumed_at = NULL
    RETURNING org_totp_enrollment_id, org_user_id, expires_at
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $5,
        'org.totp-enrollment.started',
        'org_totp_enrollment',
        org_totp_enrollment_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        $6,
        jsonb_build_object('expires_at', expires_at)
    FROM enrollment
)
SELECT org_totp_enrollment_id, expires_at FROM enrollment
`

type CreateOrgTOTPEnrollmentParams struct {
	OrgUserID        pgtype.UUID        `json:"org_user_id"`
	TokenHash        []byte             `json:"token_hash"`
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	TenantID         string             `json:"tenant_id"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
}

type CreateOrgTOTPEnrollmentRow struct {
	OrgTotpEnrollmentID pgtype.UUID        `json:"org_totp_enrollment_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrgTOTPEnrollment(ctx context.Context, arg CreateOrgTOTPEnrollmentParams) (CreateOrgTOTPEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, createOrgTOTPEnrollment,
		arg.OrgUserID,
		arg.TokenHash,
		arg.SecretCiphertext,
		arg.ExpiresAt,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var i CreateOrgTOTPEnrollmentRow
	err := row.Scan(&i.OrgTotpEnrollmentID, &i.ExpiresAt)
	return i, err
}

const disableOrgTOTP = `-- name: DisableOrgTOTP :one
WITH eligible_user AS (
    SELECT u.org_user_id
    FROM vetchium.org_users AS u
    WHERE u.org_user_id = $1
      AND u.org_user_state = 'active'
), removed AS (
    DELETE FROM vetchium.org_user_totp_credentials
    WHERE org_user_id IN (SELECT org_user_id FROM eligible_user)
    RETURNING org_user_id
), codes AS (
    DELETE FROM vetchium.org_totp_recovery_codes
    WHERE org_user_id IN (SELECT org_user_id FROM removed)
), enrollments AS (
    UPDATE vetchium.org_totp_enrollments
    SET active = false
    WHERE org_user_id IN (SELECT org_user_id FROM removed)
      AND active
), challenges AS (
    UPDATE vetchium.org_login_challenges
    SET active = false
    WHERE org_user_id IN (SELECT org_user_id FROM removed)
      AND active
), sessions AS (
    DELETE FROM vetchium.org_sessions
    WHERE org_user_id IN (SELECT org_user_id FROM removed)
      AND org_session_id <> $2
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, payload
    )
    SELECT
        $3,
        'org.totp.disabled',
        'org_user',
        org_user_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        jsonb_build_object('other_sessions_revoked', true)
    FROM removed
)
SELECT EXISTS (SELECT 1 FROM eligible_user) AS user_active
`

type DisableOrgTOTPParams struct {
	OrgUserID           pgtype.UUID `json:"org_user_id"`
	CurrentOrgSessionID pgtype.UUID `json:"current_org_session_id"`
	TenantID            string      `json:"tenant_id"`
}

func (q *Queries) DisableOrgTOTP(ctx context.Context, arg DisableOrgTOTPParams) (bool, error) {
	row := q.db.QueryRow(ctx, disableOrgTOTP, arg.OrgUserID, arg.CurrentOrgSessionID, arg.TenantID)
	var user_active bool
	err := row.Scan(&user_active)
	return user_active, err
}

const getOrgTOTPEnrollment = `-- name: GetOrgTOTPEnrollment :one
SELECT
    e.org_totp_enrollment_id,
    e.org_user_id,
    e.secret_ciphertext
FROM vetchium.org_totp_enrollments AS e
JOIN vetchium.org_users AS u USING (org_user_id)
WHERE e.token_hash = $1
  AND e.org_user_id = $2
  AND e.active
  AND e.consumed_at IS NULL
  AND e.expires_at > now()
  AND u.org_user_state = 'active'
  AND NOT EXISTS (
      SELECT 1 FROM vetchium.org_user_totp_credentials AS t
      WHERE t.org_user_id = e.org_user_id
  )
FOR UPDATE OF e
`

type GetOrgTOTPEnrollmentParams struct {
	TokenHash []byte      `json:"token_hash"`
	OrgUserID pgtype.UUID `json:"org_user_id"`
}

type GetOrgTOTPEnrollmentRow struct {
	OrgTotpEnrollmentID pgtype.UUID `json:"org_totp_enrollment_id"`
	OrgUserID           pgtype.UUID `json:"org_user_id"`
	SecretCiphertext    []byte      `json:"secret_ciphertext"`
}

func (q *Queries) GetOrgTOTPEnrollment(ctx context.Context, arg GetOrgTOTPEnrollmentParams) (GetOrgTOTPEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getOrgTOTPEnrollment, arg.TokenHash, arg.OrgUserID)
	var i GetOrgTOTPEnrollmentRow
	err := row.Scan(&i.OrgTotpEnrollmentID, &i.OrgUserID, &i.SecretCiphertext)
	return i, err
}

const orgTOTPEnabled = `-- name: OrgTOTPEnabled :one
SELECT EXISTS (
    SELECT 1 FROM vetchium.org_user_totp_credentials AS t
    WHERE t.org_user_id = u.org_user_id
) AS enabled
FROM vetchium.org_users AS u
WHERE u.org_user_id = $1
  AND u.org_user_state = 'active'
`

func (q *Queries) OrgTOTPEnabled(ctx context.Context, orgUserID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, orgTOTPEnabled, orgUserID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const regenerateOrgTOTPRecoveryCodes = `-- name: RegenerateOrgTOTPRecoveryCodes :one
WITH eligible_user AS (
    SELECT u.org_user_id
    FROM vetchium.org_users AS u
    JOIN vetchium.org_user_totp_credentials AS t USING (org_user_id)
    WHERE u.org_user_id = $1
      AND u.org_user_state = 'active'
    FOR UPDATE OF u
), deleted_codes AS (
    DELETE FROM vetchium.org_totp_recovery_codes
    WHERE org_user_id IN (SELECT org_user_id FROM eligible_user)
), inserted_codes AS (
    INSERT INTO vetchium.org_totp_recovery_codes (org_user_id, code_hash)
    SELECT u.org_user_id, code_hash
    FROM eligible_user AS u
    CROSS JOIN unnest($2::bytea[]) AS code_hash
    RETURNING org_user_id
), sessions AS (
    DELETE FROM vetchium.org_sessions
    WHERE org_user_id IN (SELECT org_user_id FROM eligible_user)
      AND org_session_id <> $3
), challenges AS (
    UPDATE vetchium.org_login_challenges
    SET active = false
    WHERE org_user_id IN (SELECT org_user_id FROM eligible_user)
      AND active
), audit AS (
    INSERT INTO vetchium.audit_events (
        tenant_id, action, entity_type, entity_id, actor_type, actor_id,
        source, idempotency_key, payload
    )
    SELECT
        $4,
        'org.totp.recovery-codes-regenerated',
        'org_user',
        org_user_id::text,
        'org_user',
        org_user_id::text,
        'orgs-api',
        $5,
        jsonb_build_object('recovery_codes_created', 10)
    FROM eligible_user
    WHERE (SELECT count(*) FROM inserted_codes) = 10
    RETURNING audit_event_id
)
SELECT EXISTS (SELECT 1 FROM audit) AS regenerated
`

type RegenerateOrgTOTPRecoveryCodesParams struct {
	OrgUserID           pgtype.UUID `json:"org_user_id"`
	RecoveryCodeHashes  [][]byte    `json:"recovery_code_hashes"`
	CurrentOrgSessionID pgtype.UUID `json:"current_org_session_id"`
	TenantID            string      `json:"tenant_id"`
	IdempotencyKey      pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) RegenerateOrgTOTPRecoveryCodes(ctx context.Context, arg RegenerateOrgTOTPRecoveryCodesParams) (bool, error) {
	row := q.db.QueryRow(ctx, regenerateOrgTOTPRecoveryCodes,
		arg.OrgUserID,
		arg.RecoveryCodeHashes,
		arg.CurrentOrgSessionID,
		arg.TenantID,
		arg.IdempotencyKey,
	)
	var regenerated bool
	err := row.Scan(&regenerated)
	return regenerated, err
}
