package employer

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"net/http"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"vetchium-api-server.gomodule/internal/db/globaldb"
	"vetchium-api-server.gomodule/internal/db/regionaldb"
	"vetchium-api-server.gomodule/internal/email/templates"
	"vetchium-api-server.gomodule/internal/i18n"
	"vetchium-api-server.gomodule/internal/middleware"
	"vetchium-api-server.gomodule/internal/server"
	"vetchium-api-server.gomodule/internal/tokens"
	common "vetchium-api-server.typespec/common"
	employertypes "vetchium-api-server.typespec/employer"
)

func InviteUser(s *server.Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		ctx := r.Context()
		log := s.Logger(ctx)

		// Get authenticated org user from context
		orgUser := middleware.OrgUserFromContext(ctx)
		if orgUser == nil {
			log.Debug("org user not found in context")
			w.WriteHeader(http.StatusUnauthorized)
			return
		}

		// Decode request
		var req employertypes.OrgInviteUserRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			log.Debug("failed to decode request", "error", err)
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}

		// Validate request
		if errs := req.Validate(); len(errs) > 0 {
			log.Debug("validation failed", "errors", errs)
			w.WriteHeader(http.StatusBadRequest)
			json.NewEncoder(w).Encode(errs)
			return
		}

		// Hash email for global DB lookup
		emailHash := sha256.Sum256([]byte(req.EmailAddress))

		// Check if user already exists for this employer in global DB
		_, err := s.Global.GetOrgUserByEmailHashAndEmployer(ctx, globaldb.GetOrgUserByEmailHashAndEmployerParams{
			EmailAddressHash: emailHash[:],
			EmployerID:       orgUser.EmployerID,
		})
		if err == nil {
			// User already exists for this employer
			log.Debug("user already exists for this employer", "email_hash", hex.EncodeToString(emailHash[:]))
			w.WriteHeader(http.StatusConflict)
			json.NewEncoder(w).Encode(map[string]string{
				"error": "User with this email already exists for this employer",
			})
			return
		}
		if !errors.Is(err, pgx.ErrNoRows) {
			log.Error("failed to check if user exists", "error", err)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Resolve role IDs before creating any records
		var roleIDs []pgtype.UUID
		for _, roleName := range req.Roles {
			role, err := s.Regional.GetRoleByName(ctx, string(roleName))
			if err != nil {
				if errors.Is(err, pgx.ErrNoRows) {
					log.Debug("role not found", "role_name", roleName)
					w.WriteHeader(http.StatusBadRequest)
					json.NewEncoder(w).Encode([]common.ValidationError{
						common.NewValidationError("roles", common.ErrRoleNameInvalid),
					})
					return
				}
				log.Error("failed to get role", "error", err, "role_name", roleName)
				http.Error(w, "", http.StatusInternalServerError)
				return
			}
			roleIDs = append(roleIDs, role.RoleID)
		}

		// Create org user in global DB (routing fields only)
		// UUID is generated by the database
		globalUser, err := s.Global.CreateOrgUser(ctx, globaldb.CreateOrgUserParams{
			EmailAddressHash: emailHash[:],
			HashingAlgorithm: globaldb.EmailAddressHashingAlgorithmSHA256,
			EmployerID:       orgUser.EmployerID,
			HomeRegion:       s.CurrentRegion,
		})
		if err != nil {
			log.Error("failed to create org user in global DB", "error", err)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Generate invitation token
		tokenBytes := make([]byte, 32)
		if _, err := rand.Read(tokenBytes); err != nil {
			log.Error("failed to generate invitation token", "error", err)
			// Compensating transaction: delete from global DB
			if delErr := s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID); delErr != nil {
				log.Error("CONSISTENCY_ALERT: failed to delete org user from global DB", "error", delErr)
			}
			http.Error(w, "", http.StatusInternalServerError)
			return
		}
		rawToken := hex.EncodeToString(tokenBytes)

		// Add region prefix to token
		invitationToken := tokens.AddRegionPrefix(s.CurrentRegion, rawToken)

		// Wrap regional operations in a transaction
		invitationExpiry := s.TokenConfig.OrgInvitationTokenExpiry
		expiresAt := pgtype.Timestamp{Time: time.Now().Add(invitationExpiry), Valid: true}
		err = s.WithRegionalTx(ctx, func(qtx *regionaldb.Queries) error {
			// Create org user in regional DB (without password hash)
			// Don't set full_name - user will provide during complete-setup
			_, err := qtx.CreateOrgUser(ctx, regionaldb.CreateOrgUserParams{
				OrgUserID:    globalUser.OrgUserID,
				EmailAddress: string(req.EmailAddress),
				EmployerID:   orgUser.EmployerID,
				FullName: pgtype.Text{
					Valid: false, // User will provide during complete-setup
				},
				PasswordHash:      nil, // No password hash for invited users yet
				Status:            regionaldb.OrgUserStatusInvited,
				PreferredLanguage: "en-US", // Default, user will override during complete-setup
			})
			if err != nil {
				return err
			}

			// Create invitation token in regional DB
			err = qtx.CreateOrgInvitationToken(ctx, regionaldb.CreateOrgInvitationTokenParams{
				InvitationToken: rawToken,
				OrgUserID:       globalUser.OrgUserID,
				EmployerID:      orgUser.EmployerID,
				ExpiresAt:       expiresAt,
			})
			if err != nil {
				return err
			}

			// Assign roles to invited user
			for _, roleID := range roleIDs {
				if err := qtx.AssignOrgUserRole(ctx, regionaldb.AssignOrgUserRoleParams{
					OrgUserID: globalUser.OrgUserID,
					RoleID:    roleID,
				}); err != nil {
					return err
				}
			}

			return nil
		})
		if err != nil {
			log.Error("failed to create org user in regional DB", "error", err)
			// Compensating transaction: delete from global DB
			if delErr := s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID); delErr != nil {
				log.Error("CONSISTENCY_ALERT: failed to delete org user from global DB after regional tx failure", "error", delErr)
			}
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Get inviter's full name from regional DB
		inviter, err := s.Regional.GetOrgUserByID(ctx, orgUser.OrgUserID)
		if err != nil {
			log.Error("failed to get inviter info", "error", err)
			// Compensating transaction: delete everything
			s.Regional.DeleteOrgInvitationToken(ctx, rawToken)
			s.Regional.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Get employer name from global DB
		employer, err := s.Global.GetEmployerByID(ctx, orgUser.EmployerID)
		if err != nil {
			log.Error("failed to get employer info", "error", err)
			// Compensating transaction: delete everything
			s.Regional.DeleteOrgInvitationToken(ctx, rawToken)
			s.Regional.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Send invitation email
		// Determine email language: use invite_email_language if provided, otherwise inviter's preferred_language
		emailLanguage := orgUser.PreferredLanguage
		if req.InviteEmailLanguage != "" {
			emailLanguage = string(req.InviteEmailLanguage)
		}
		lang := i18n.Match(emailLanguage)
		inviterName := inviter.FullName.String
		if inviterName == "" {
			inviterName = inviter.EmailAddress // Fallback to email if no full name
		}

		emailData := templates.EmployerInvitationData{
			InvitationToken: invitationToken,
			InviterName:     inviterName,
			EmployerName:    employer.EmployerName,
			Days:            int(invitationExpiry.Hours() / 24),
			BaseURL:         s.UIConfig.OrgURL,
		}

		_, err = s.Regional.EnqueueEmail(ctx, regionaldb.EnqueueEmailParams{
			EmailType:     regionaldb.EmailTemplateTypeOrgInvitation,
			EmailTo:       string(req.EmailAddress),
			EmailSubject:  templates.EmployerInvitationSubject(lang, emailData),
			EmailTextBody: templates.EmployerInvitationTextBody(lang, emailData),
			EmailHtmlBody: templates.EmployerInvitationHTMLBody(lang, emailData),
		})
		if err != nil {
			log.Error("failed to enqueue invitation email", "error", err)
			// Compensating transaction: delete everything
			s.Regional.DeleteOrgInvitationToken(ctx, rawToken)
			s.Regional.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		log.Info("user invited successfully", "org_user_id", globalUser.OrgUserID, "inviter_id", orgUser.OrgUserID)

		// Return response
		response := employertypes.OrgInviteUserResponse{
			InvitationID: globalUser.OrgUserID.String(),
			ExpiresAt:    expiresAt.Time.Format(time.RFC3339),
		}

		w.WriteHeader(http.StatusCreated)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			log.Error("failed to encode response", "error", err)
		}
	}
}
