# Migration runner using goose
FROM golang:alpine

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /migrations

COPY db/migrations/global ./global
COPY db/migrations/regional ./regional

ENTRYPOINT ["goose"]
