// Kept free of imports for the same reason as portal-environment.ts.

/**
 * The response headers a static portal needs, rendered for both places that
 * serve it: the static host's `_headers` file in production and the nginx
 * include that dev and CI use. One policy feeds both renderers so the two
 * deployments cannot drift.
 */
export interface SecurityHeaderPolicy {
  /** Origins the portal calls with `fetch`, such as every region's API. */
  readonly connectSources: readonly string[];
  /** Origins the portal renders images from, such as every media origin. */
  readonly imageSources: readonly string[];
  /** Path prefixes, ending in "/", whose responses must not be indexed. */
  readonly noindexPathPrefixes: readonly string[];
  /** Whether the site is served only over HTTPS, so browsers may be told
   * never to use plain HTTP for it or its subdomains. */
  readonly strictTransportSecurity: boolean;
}

const immutableAssets = "public, max-age=31536000, immutable";

function sources(values: readonly string[]): string {
  for (const value of values) {
    let origin: string | undefined;
    try {
      origin = new URL(value).origin;
    } catch {
      // Reported below.
    }
    if (origin !== value) throw new Error(`${value} is not an origin`);
  }
  return [...new Set(values)]
    .sort()
    .map((value) => ` ${value}`)
    .join("");
}

function prefixes(values: readonly string[]): readonly string[] {
  for (const value of values) {
    if (!/^\/[a-z0-9-]+\/$/.test(value)) {
      throw new Error(`${value} must be a single path segment like /u/`);
    }
  }
  return values;
}

export function contentSecurityPolicy(policy: SecurityHeaderPolicy): string {
  return [
    "default-src 'self'",
    "base-uri 'self'",
    `connect-src 'self'${sources(policy.connectSources)}`,
    "font-src 'self' data:",
    "form-action 'self'",
    "frame-ancestors 'self'",
    `img-src 'self' data:${sources(policy.imageSources)}`,
    "object-src 'none'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
  ].join("; ");
}

function commonHeaders(policy: SecurityHeaderPolicy): [string, string][] {
  const headers: [string, string][] = [
    ["Content-Security-Policy", contentSecurityPolicy(policy)],
    ["X-Content-Type-Options", "nosniff"],
    ["X-Frame-Options", "SAMEORIGIN"],
    ["Referrer-Policy", "strict-origin-when-cross-origin"],
  ];
  if (policy.strictTransportSecurity) {
    headers.push([
      "Strict-Transport-Security",
      "max-age=31536000; includeSubDomains",
    ]);
  }
  return headers;
}

/** The `_redirects` file serving the single-page app for every path that is
 * not a built file. Cloudflare Pages already does this when the bundle has no
 * 404.html and ignores the rule; Netlify needs it. */
export const staticHostRedirects = "/* /index.html 200\n";

/** The `_headers` file static hosts such as Cloudflare Pages and Netlify
 * read; every matching rule applies, so path rules add to `/*`. */
export function staticHostHeaders(policy: SecurityHeaderPolicy): string {
  const rule = (path: string, headers: [string, string][]) =>
    [path, ...headers.map(([name, value]) => `  ${name}: ${value}`)].join("\n");
  return `${[
    rule("/*", commonHeaders(policy)),
    rule("/assets/*", [["Cache-Control", immutableAssets]]),
    ...prefixes(policy.noindexPathPrefixes).map((prefix) =>
      rule(`${prefix}*`, [["X-Robots-Tag", "noindex"]]),
    ),
  ].join("\n")}\n`;
}

/**
 * Server-level directives for an nginx `server` block serving the built
 * portal. nginx drops inherited `add_header` directives in any location that
 * declares its own, so every location repeats the common headers.
 */
export function nginxPortalInclude(policy: SecurityHeaderPolicy): string {
  const common = commonHeaders(policy).map(
    ([name, value]) => `add_header ${name} "${value}" always;`,
  );
  const location = (match: string, lines: string[]) =>
    [
      `location ${match} {`,
      ...[...common, ...lines].map((line) => `    ${line}`),
      "}",
    ].join("\n");
  return `${[
    "# Generated by @vetchium/portal-ui/security-headers. Do not edit.",
    ...common,
    location("/assets/", [
      `add_header Cache-Control "${immutableAssets}";`,
      "try_files $uri =404;",
    ]),
    ...prefixes(policy.noindexPathPrefixes).map((prefix) =>
      location(prefix, [
        'add_header X-Robots-Tag "noindex" always;',
        // A final try_files argument is an internal redirect that would leave
        // this location and its headers; =404 keeps index.html served here.
        "try_files $uri /index.html =404;",
      ]),
    ),
    location("/", ["try_files $uri $uri/ /index.html;"]),
  ].join("\n")}\n`;
}
