package org

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"net/http"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"vetchium-api-server.gomodule/internal/db/globaldb"
	"vetchium-api-server.gomodule/internal/db/regionaldb"
	"vetchium-api-server.gomodule/internal/email/templates"
	"vetchium-api-server.gomodule/internal/i18n"
	"vetchium-api-server.gomodule/internal/middleware"
	"vetchium-api-server.gomodule/internal/server"
	"vetchium-api-server.gomodule/internal/tokens"
	"vetchium-api-server.typespec/org"
)

func InviteUser(s *server.Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		ctx := r.Context()
		log := s.Logger(ctx)

		// Get authenticated org user from context
		orgUser := middleware.OrgUserFromContext(ctx)
		if orgUser == nil {
			log.Debug("org user not found in context")
			w.WriteHeader(http.StatusUnauthorized)
			return
		}

		// Check if user has permission to invite users
		inviteUsersRole, roleErr := s.Global.GetRoleByName(ctx, "invite_users")
		if roleErr != nil {
			log.Error("failed to get invite_users role", "error", roleErr)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		hasInviteRole, roleErr := s.Global.HasOrgUserRole(ctx, globaldb.HasOrgUserRoleParams{
			OrgUserID: orgUser.OrgUserID,
			RoleID:    inviteUsersRole.RoleID,
		})
		if roleErr != nil {
			log.Error("failed to check invite_users role", "error", roleErr)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		if !hasInviteRole && !orgUser.IsAdmin {
			log.Debug("user does not have permission to invite users", "org_user_id", orgUser.OrgUserID)
			w.WriteHeader(http.StatusForbidden)
			return
		}

		// Decode request
		var req org.OrgInviteUserRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			log.Debug("failed to decode request", "error", err)
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}

		// Validate request
		if errs := req.Validate(); len(errs) > 0 {
			log.Debug("validation failed", "errors", errs)
			w.WriteHeader(http.StatusBadRequest)
			json.NewEncoder(w).Encode(errs)
			return
		}

		// Hash email for global DB lookup
		emailHash := sha256.Sum256([]byte(req.EmailAddress))

		// Check if user already exists for this employer in global DB
		_, err := s.Global.GetOrgUserByEmailHashAndEmployer(ctx, globaldb.GetOrgUserByEmailHashAndEmployerParams{
			EmailAddressHash: emailHash[:],
			EmployerID:       orgUser.EmployerID,
		})
		if err == nil {
			// User already exists for this employer
			log.Debug("user already exists for this employer", "email_hash", hex.EncodeToString(emailHash[:]))
			w.WriteHeader(http.StatusConflict)
			json.NewEncoder(w).Encode(map[string]string{
				"error": "User with this email already exists for this employer",
			})
			return
		}
		if !errors.Is(err, pgx.ErrNoRows) {
			log.Error("failed to check if user exists", "error", err)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Get region for the authenticated user (inviter)
		region := middleware.OrgRegionFromContext(ctx)
		if region == "" {
			log.Error("region not found in context")
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Get regional DB
		regionalDB := s.GetRegionalDB(globaldb.Region(region))
		if regionalDB == nil {
			log.Error("regional database not available", "region", region)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		language := "en-US"
		if req.PreferredLanguage != "" {
			language = string(req.PreferredLanguage)
		}

		// Create org user in global DB with status='invited'
		// UUID is generated by the database
		globalUser, err := s.Global.CreateOrgUser(ctx, globaldb.CreateOrgUserParams{
			EmailAddressHash:  emailHash[:],
			HashingAlgorithm:  globaldb.EmailAddressHashingAlgorithmSHA256,
			EmployerID:        orgUser.EmployerID,
			FullName:          pgtype.Text{String: string(req.FullName), Valid: true},
			IsAdmin:           false, // New users are not admins by default
			Status:            globaldb.OrgUserStatusInvited,
			PreferredLanguage: language, // Validated in request
			HomeRegion:        globaldb.Region(region),
		})
		if err != nil {
			log.Error("failed to create org user in global DB", "error", err)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Create org user in regional DB (without password hash)
		_, err = regionalDB.CreateOrgUser(ctx, regionaldb.CreateOrgUserParams{
			OrgUserID:    globalUser.OrgUserID,
			EmailAddress: string(req.EmailAddress),
			EmployerID:   orgUser.EmployerID,
			FullName: pgtype.Text{
				String: string(req.FullName),
				Valid:  true,
			},
			PasswordHash: nil, // No password hash for invited users yet
		})
		if err != nil {
			log.Error("failed to create org user in regional DB", "error", err)
			// Compensating transaction: delete from global DB
			if delErr := s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID); delErr != nil {
				log.Error("failed to delete org user from global DB", "error", delErr)
			}
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Generate invitation token
		tokenBytes := make([]byte, 32)
		if _, err := rand.Read(tokenBytes); err != nil {
			log.Error("failed to generate invitation token", "error", err)
			// Compensating transaction: delete from both DBs
			regionalDB.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}
		rawToken := hex.EncodeToString(tokenBytes)

		// Add region prefix to token
		invitationToken := tokens.AddRegionPrefix(globaldb.Region(region), rawToken)

		// Create invitation token in regional DB
		invitationExpiry := s.TokenConfig.OrgInvitationTokenExpiry
		expiresAt := pgtype.Timestamp{Time: time.Now().Add(invitationExpiry), Valid: true}
		err = regionalDB.CreateOrgInvitationToken(ctx, regionaldb.CreateOrgInvitationTokenParams{
			InvitationToken: rawToken,
			OrgUserID:       globalUser.OrgUserID,
			EmployerID:      orgUser.EmployerID,
			ExpiresAt:       expiresAt,
		})
		if err != nil {
			log.Error("failed to create invitation token", "error", err)
			// Compensating transaction: delete from both DBs
			regionalDB.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Get inviter's full name from regional DB
		inviter, err := regionalDB.GetOrgUserByID(ctx, orgUser.OrgUserID)
		if err != nil {
			log.Error("failed to get inviter info", "error", err)
			// Compensating transaction: delete everything
			regionalDB.DeleteOrgInvitationToken(ctx, rawToken)
			regionalDB.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Get employer name from global DB
		employer, err := s.Global.GetEmployerByID(ctx, orgUser.EmployerID)
		if err != nil {
			log.Error("failed to get employer info", "error", err)
			// Compensating transaction: delete everything
			regionalDB.DeleteOrgInvitationToken(ctx, rawToken)
			regionalDB.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		// Send invitation email
		lang := i18n.Match(orgUser.PreferredLanguage)
		inviterName := inviter.FullName.String
		if inviterName == "" {
			inviterName = inviter.EmailAddress // Fallback to email if no full name
		}

		emailData := templates.OrgInvitationData{
			InvitationToken: invitationToken,
			InviterName:     inviterName,
			EmployerName:    employer.EmployerName,
			Days:            int(invitationExpiry.Hours() / 24),
			BaseURL:         s.UIConfig.OrgURL,
		}

		_, err = regionalDB.EnqueueEmail(ctx, regionaldb.EnqueueEmailParams{
			EmailType:     regionaldb.EmailTemplateTypeOrgInvitation,
			EmailTo:       string(req.EmailAddress),
			EmailSubject:  templates.OrgInvitationSubject(lang, emailData),
			EmailTextBody: templates.OrgInvitationTextBody(lang, emailData),
			EmailHtmlBody: templates.OrgInvitationHTMLBody(lang, emailData),
		})
		if err != nil {
			log.Error("failed to enqueue invitation email", "error", err)
			// Compensating transaction: delete everything
			regionalDB.DeleteOrgInvitationToken(ctx, rawToken)
			regionalDB.DeleteOrgUser(ctx, globalUser.OrgUserID)
			s.Global.DeleteOrgUser(ctx, globalUser.OrgUserID)
			http.Error(w, "", http.StatusInternalServerError)
			return
		}

		log.Info("user invited successfully", "org_user_id", globalUser.OrgUserID, "inviter_id", orgUser.OrgUserID)

		// Return response
		response := org.OrgInviteUserResponse{
			InvitationID: globalUser.OrgUserID.String(),
			ExpiresAt:    expiresAt.Time.Format(time.RFC3339),
		}

		w.WriteHeader(http.StatusCreated)
		if err := json.NewEncoder(w).Encode(response); err != nil {
			log.Error("failed to encode response", "error", err)
		}
	}
}
