// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: directory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireCommandLock = `-- name: AcquireCommandLock :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::text, 0)
)
`

func (q *Queries) AcquireCommandLock(ctx context.Context, commandID string) error {
	_, err := q.db.Exec(ctx, acquireCommandLock, commandID)
	return err
}

const activateHubPrincipal = `-- name: ActivateHubPrincipal :one
WITH activated_principal AS (
    UPDATE vetchium.hub_principals
    SET state = 'active', provisioning_expires_at = NULL,
        activated_at = now(), updated_at = now(),
        directory_version = directory_version + 1
    WHERE hub_principals.hub_user_did = $1
      AND home_tenant_id = $2
      AND state = 'provisioning'
      AND provisioning_expires_at > now()
    RETURNING hub_user_did, directory_version
), activated_claim AS (
    UPDATE vetchium.hub_account_email_claims AS claim
    SET state = 'active', updated_at = now()
    FROM activated_principal
    WHERE claim.hub_user_did = activated_principal.hub_user_did
      AND claim.state = 'provisioning'
    RETURNING claim.email_digest
)
SELECT
    p.hub_user_did,
    p.directory_version,
    (SELECT count(*) FROM activated_claim) AS activated_claim_count
FROM activated_principal AS p
`

type ActivateHubPrincipalParams struct {
	HubUserDid     pgtype.UUID `json:"hub_user_did"`
	CallerTenantID string      `json:"caller_tenant_id"`
}

type ActivateHubPrincipalRow struct {
	HubUserDid          pgtype.UUID `json:"hub_user_did"`
	DirectoryVersion    int64       `json:"directory_version"`
	ActivatedClaimCount int64       `json:"activated_claim_count"`
}

// Activates the principal and, in the same statement, its provisioning
// account email claim (GU-DIR-003). The claim update depends on
// activated_principal via a real FROM reference, so the claim's transition
// trigger sees the principal already active.
func (q *Queries) ActivateHubPrincipal(ctx context.Context, arg ActivateHubPrincipalParams) (ActivateHubPrincipalRow, error) {
	row := q.db.QueryRow(ctx, activateHubPrincipal, arg.HubUserDid, arg.CallerTenantID)
	var i ActivateHubPrincipalRow
	err := row.Scan(&i.HubUserDid, &i.DirectoryVersion, &i.ActivatedClaimCount)
	return i, err
}

const deleteHubAlias = `-- name: DeleteHubAlias :exec
DELETE FROM vetchium.hub_profile_slugs
WHERE hub_user_did = $1
  AND kind = 'alias'
`

func (q *Queries) DeleteHubAlias(ctx context.Context, hubUserDid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHubAlias, hubUserDid)
	return err
}

const getCommandResult = `-- name: GetCommandResult :one
SELECT
    command_id,
    operation,
    caller_tenant_id,
    request_digest,
    response_status,
    response_body,
    completed_at
FROM vetchium.global_command_ledger
WHERE command_id = $1
`

func (q *Queries) GetCommandResult(ctx context.Context, commandID pgtype.UUID) (VetchiumGlobalCommandLedger, error) {
	row := q.db.QueryRow(ctx, getCommandResult, commandID)
	var i VetchiumGlobalCommandLedger
	err := row.Scan(
		&i.CommandID,
		&i.Operation,
		&i.CallerTenantID,
		&i.RequestDigest,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CompletedAt,
	)
	return i, err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT
    hub_user_did,
    home_tenant_id,
    state,
    routing_version,
    directory_version,
    provisioning_operation_id,
    provisioning_expires_at,
    activated_at,
    alias_changed_at,
    created_at,
    updated_at
FROM vetchium.hub_principals
WHERE hub_user_did = $1
`

type GetPrincipalRow struct {
	HubUserDid              pgtype.UUID                  `json:"hub_user_did"`
	HomeTenantID            string                       `json:"home_tenant_id"`
	State                   VetchiumGlobalPrincipalState `json:"state"`
	RoutingVersion          int64                        `json:"routing_version"`
	DirectoryVersion        int64                        `json:"directory_version"`
	ProvisioningOperationID pgtype.UUID                  `json:"provisioning_operation_id"`
	ProvisioningExpiresAt   pgtype.Timestamptz           `json:"provisioning_expires_at"`
	ActivatedAt             pgtype.Timestamptz           `json:"activated_at"`
	AliasChangedAt          pgtype.Timestamptz           `json:"alias_changed_at"`
	CreatedAt               pgtype.Timestamptz           `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz           `json:"updated_at"`
}

func (q *Queries) GetPrincipal(ctx context.Context, hubUserDid pgtype.UUID) (GetPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getPrincipal, hubUserDid)
	var i GetPrincipalRow
	err := row.Scan(
		&i.HubUserDid,
		&i.HomeTenantID,
		&i.State,
		&i.RoutingVersion,
		&i.DirectoryVersion,
		&i.ProvisioningOperationID,
		&i.ProvisioningExpiresAt,
		&i.ActivatedAt,
		&i.AliasChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrincipalCommandView = `-- name: GetPrincipalCommandView :one
SELECT
    p.hub_user_did,
    h.slug AS handle,
    a.slug AS profile_alias,
    p.home_tenant_id,
    p.routing_version,
    p.directory_version,
    p.state
FROM vetchium.hub_principals AS p
INNER JOIN vetchium.hub_profile_slugs AS h
    ON h.hub_user_did = p.hub_user_did AND h.kind = 'handle'
LEFT JOIN vetchium.hub_profile_slugs AS a
    ON a.hub_user_did = p.hub_user_did AND a.kind = 'alias'
WHERE p.hub_user_did = $1
`

type GetPrincipalCommandViewRow struct {
	HubUserDid       pgtype.UUID                  `json:"hub_user_did"`
	Handle           string                       `json:"handle"`
	ProfileAlias     pgtype.Text                  `json:"profile_alias"`
	HomeTenantID     string                       `json:"home_tenant_id"`
	RoutingVersion   int64                        `json:"routing_version"`
	DirectoryVersion int64                        `json:"directory_version"`
	State            VetchiumGlobalPrincipalState `json:"state"`
}

func (q *Queries) GetPrincipalCommandView(ctx context.Context, hubUserDid pgtype.UUID) (GetPrincipalCommandViewRow, error) {
	row := q.db.QueryRow(ctx, getPrincipalCommandView, hubUserDid)
	var i GetPrincipalCommandViewRow
	err := row.Scan(
		&i.HubUserDid,
		&i.Handle,
		&i.ProfileAlias,
		&i.HomeTenantID,
		&i.RoutingVersion,
		&i.DirectoryVersion,
		&i.State,
	)
	return i, err
}

const insertCommandResult = `-- name: InsertCommandResult :exec
INSERT INTO vetchium.global_command_ledger (
    command_id, operation, caller_tenant_id, request_digest,
    response_status, response_body
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type InsertCommandResultParams struct {
	CommandID      pgtype.UUID `json:"command_id"`
	Operation      string      `json:"operation"`
	CallerTenantID string      `json:"caller_tenant_id"`
	RequestDigest  []byte      `json:"request_digest"`
	ResponseStatus int32       `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
}

func (q *Queries) InsertCommandResult(ctx context.Context, arg InsertCommandResultParams) error {
	_, err := q.db.Exec(ctx, insertCommandResult,
		arg.CommandID,
		arg.Operation,
		arg.CallerTenantID,
		arg.RequestDigest,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const insertGlobalAuditEvent = `-- name: InsertGlobalAuditEvent :exec
INSERT INTO vetchium.global_audit_events (
    action, entity_type, entity_id, actor_tenant_id, command_id, payload
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type InsertGlobalAuditEventParams struct {
	Action        string      `json:"action"`
	EntityType    string      `json:"entity_type"`
	EntityID      string      `json:"entity_id"`
	ActorTenantID string      `json:"actor_tenant_id"`
	CommandID     pgtype.UUID `json:"command_id"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) InsertGlobalAuditEvent(ctx context.Context, arg InsertGlobalAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertGlobalAuditEvent,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.ActorTenantID,
		arg.CommandID,
		arg.Payload,
	)
	return err
}

const insertGlobalOutboxEvent = `-- name: InsertGlobalOutboxEvent :exec
INSERT INTO vetchium.global_outbox_events (
    aggregate_type, aggregate_id, aggregate_version, event_type, payload
) VALUES (
    $1, $2,
    $3, $4, $5
)
`

type InsertGlobalOutboxEventParams struct {
	AggregateType    string `json:"aggregate_type"`
	AggregateID      string `json:"aggregate_id"`
	AggregateVersion int64  `json:"aggregate_version"`
	EventType        string `json:"event_type"`
	Payload          []byte `json:"payload"`
}

func (q *Queries) InsertGlobalOutboxEvent(ctx context.Context, arg InsertGlobalOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertGlobalOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const insertHubAlias = `-- name: InsertHubAlias :exec
INSERT INTO vetchium.hub_profile_slugs (slug, hub_user_did, kind)
VALUES ($1, $2, 'alias')
`

type InsertHubAliasParams struct {
	ProfileAlias string      `json:"profile_alias"`
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
}

func (q *Queries) InsertHubAlias(ctx context.Context, arg InsertHubAliasParams) error {
	_, err := q.db.Exec(ctx, insertHubAlias, arg.ProfileAlias, arg.HubUserDid)
	return err
}

const lockPrincipalForAlias = `-- name: LockPrincipalForAlias :one
SELECT
    p.hub_user_did,
    p.home_tenant_id,
    p.state,
    p.alias_changed_at,
    p.directory_version,
    a.slug AS profile_alias,
    (
        p.alias_changed_at IS NULL OR
        p.alias_changed_at <= now() - interval '7 days'
    ) AS alias_change_allowed
FROM vetchium.hub_principals AS p
LEFT JOIN vetchium.hub_profile_slugs AS a
    ON a.hub_user_did = p.hub_user_did AND a.kind = 'alias'
WHERE p.hub_user_did = $1
FOR UPDATE OF p
`

type LockPrincipalForAliasRow struct {
	HubUserDid         pgtype.UUID                  `json:"hub_user_did"`
	HomeTenantID       string                       `json:"home_tenant_id"`
	State              VetchiumGlobalPrincipalState `json:"state"`
	AliasChangedAt     pgtype.Timestamptz           `json:"alias_changed_at"`
	DirectoryVersion   int64                        `json:"directory_version"`
	ProfileAlias       pgtype.Text                  `json:"profile_alias"`
	AliasChangeAllowed pgtype.Bool                  `json:"alias_change_allowed"`
}

func (q *Queries) LockPrincipalForAlias(ctx context.Context, hubUserDid pgtype.UUID) (LockPrincipalForAliasRow, error) {
	row := q.db.QueryRow(ctx, lockPrincipalForAlias, hubUserDid)
	var i LockPrincipalForAliasRow
	err := row.Scan(
		&i.HubUserDid,
		&i.HomeTenantID,
		&i.State,
		&i.AliasChangedAt,
		&i.DirectoryVersion,
		&i.ProfileAlias,
		&i.AliasChangeAllowed,
	)
	return i, err
}

const reapExpiredHubPrincipalReservations = `-- name: ReapExpiredHubPrincipalReservations :one
WITH candidates AS MATERIALIZED (
    SELECT hub_user_did, home_tenant_id, provisioning_operation_id
    FROM vetchium.hub_principals
    WHERE state = 'provisioning'
      AND provisioning_expires_at <= now()
    ORDER BY provisioning_expires_at
    FOR UPDATE SKIP LOCKED
    LIMIT 100
), deleted_slugs AS (
    DELETE FROM vetchium.hub_profile_slugs AS slug
    USING candidates
    WHERE slug.hub_user_did = candidates.hub_user_did
    RETURNING slug.hub_user_did
), deleted_claims AS (
    DELETE FROM vetchium.hub_account_email_claims AS claim
    USING candidates
    WHERE claim.hub_user_did = candidates.hub_user_did
    RETURNING claim.hub_user_did
), deleted AS (
    DELETE FROM vetchium.hub_principals AS principal
    USING candidates
    WHERE principal.hub_user_did = candidates.hub_user_did
      AND EXISTS (
          SELECT 1 FROM deleted_slugs
          WHERE deleted_slugs.hub_user_did = principal.hub_user_did
      )
    RETURNING principal.hub_user_did
), audit AS (
    INSERT INTO vetchium.global_audit_events (
        action, entity_type, entity_id, actor_tenant_id, command_id, payload
    )
    SELECT
        'global_directory.hub_principal_reservation_expired',
        'hub_principal',
        c.hub_user_did::text,
        c.home_tenant_id,
        c.provisioning_operation_id,
        jsonb_build_object(
            'schema_version', 1,
            'actor', 'global-coordinator',
            'email_claim_released', EXISTS (
                SELECT 1 FROM deleted_claims AS dc
                WHERE dc.hub_user_did = c.hub_user_did
            )
        )
    FROM candidates AS c
    INNER JOIN deleted AS removed ON removed.hub_user_did = c.hub_user_did
)
SELECT count(*) FROM deleted
`

// The coordinator reaps a reservation its home tenant never activated,
// together with its provisioning account-email claim (GU-DIR-010). The audit
// event names that tenant, whose signup the reservation belonged to.
func (q *Queries) ReapExpiredHubPrincipalReservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, reapExpiredHubPrincipalReservations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordHubAliasChange = `-- name: RecordHubAliasChange :one
UPDATE vetchium.hub_principals
SET alias_changed_at = CASE WHEN $1::boolean
        THEN now() ELSE alias_changed_at END,
    alias_revision = alias_revision + 1,
    updated_at = now(),
    directory_version = directory_version + 1
WHERE hub_user_did = $2
RETURNING directory_version
`

type RecordHubAliasChangeParams struct {
	RecordCooldown bool        `json:"record_cooldown"`
	HubUserDid     pgtype.UUID `json:"hub_user_did"`
}

func (q *Queries) RecordHubAliasChange(ctx context.Context, arg RecordHubAliasChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordHubAliasChange, arg.RecordCooldown, arg.HubUserDid)
	var directory_version int64
	err := row.Scan(&directory_version)
	return directory_version, err
}

const reserveHubPrincipal = `-- name: ReserveHubPrincipal :one
WITH principal AS (
    INSERT INTO vetchium.hub_principals (
        hub_user_did, home_tenant_id, state, provisioning_operation_id,
        provisioning_expires_at
    ) VALUES (
        $1, $2, 'provisioning',
        $3, $4
    )
    RETURNING hub_user_did, home_tenant_id, routing_version,
        directory_version, state
), claim AS (
    INSERT INTO vetchium.hub_account_email_claims (
        email_digest, hub_user_did, state, command_id
    )
    SELECT $5, hub_user_did, 'provisioning',
        $3
    FROM principal
    RETURNING email_digest
), handle AS (
    INSERT INTO vetchium.hub_profile_slugs (slug, hub_user_did, kind)
    SELECT $6, principal.hub_user_did, 'handle'
    FROM principal
    INNER JOIN claim ON TRUE
    RETURNING slug
)
SELECT
    p.hub_user_did, h.slug AS handle, NULL::text AS profile_alias,
    p.home_tenant_id, p.routing_version, p.directory_version, p.state
FROM principal AS p
CROSS JOIN handle AS h
`

type ReserveHubPrincipalParams struct {
	HubUserDid            pgtype.UUID        `json:"hub_user_did"`
	HomeTenantID          string             `json:"home_tenant_id"`
	CommandID             pgtype.UUID        `json:"command_id"`
	ProvisioningExpiresAt pgtype.Timestamptz `json:"provisioning_expires_at"`
	AccountEmailDigest    []byte             `json:"account_email_digest"`
	Handle                string             `json:"handle"`
}

type ReserveHubPrincipalRow struct {
	HubUserDid       pgtype.UUID                  `json:"hub_user_did"`
	Handle           string                       `json:"handle"`
	ProfileAlias     pgtype.Text                  `json:"profile_alias"`
	HomeTenantID     string                       `json:"home_tenant_id"`
	RoutingVersion   int64                        `json:"routing_version"`
	DirectoryVersion int64                        `json:"directory_version"`
	State            VetchiumGlobalPrincipalState `json:"state"`
}

// The claim is inserted before the handle, and its failure aborts the whole
// statement before the handle insert even runs, so a digest already claimed
// elsewhere never burns a handle-rotation attempt (GU-DIR-002).
func (q *Queries) ReserveHubPrincipal(ctx context.Context, arg ReserveHubPrincipalParams) (ReserveHubPrincipalRow, error) {
	row := q.db.QueryRow(ctx, reserveHubPrincipal,
		arg.HubUserDid,
		arg.HomeTenantID,
		arg.CommandID,
		arg.ProvisioningExpiresAt,
		arg.AccountEmailDigest,
		arg.Handle,
	)
	var i ReserveHubPrincipalRow
	err := row.Scan(
		&i.HubUserDid,
		&i.Handle,
		&i.ProfileAlias,
		&i.HomeTenantID,
		&i.RoutingVersion,
		&i.DirectoryVersion,
		&i.State,
	)
	return i, err
}

const resolveProfileSlug = `-- name: ResolveProfileSlug :one
SELECT
    p.hub_user_did,
    s.slug,
    s.kind,
    p.home_tenant_id,
    p.routing_version
FROM vetchium.hub_profile_slugs AS s
INNER JOIN vetchium.hub_principals AS p
    ON p.hub_user_did = s.hub_user_did
WHERE s.slug = $1
  AND p.state = 'active'
`

type ResolveProfileSlugRow struct {
	HubUserDid     pgtype.UUID                   `json:"hub_user_did"`
	Slug           string                        `json:"slug"`
	Kind           VetchiumGlobalProfileSlugKind `json:"kind"`
	HomeTenantID   string                        `json:"home_tenant_id"`
	RoutingVersion int64                         `json:"routing_version"`
}

func (q *Queries) ResolveProfileSlug(ctx context.Context, slug string) (ResolveProfileSlugRow, error) {
	row := q.db.QueryRow(ctx, resolveProfileSlug, slug)
	var i ResolveProfileSlugRow
	err := row.Scan(
		&i.HubUserDid,
		&i.Slug,
		&i.Kind,
		&i.HomeTenantID,
		&i.RoutingVersion,
	)
	return i, err
}
