// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_email_directory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonReservedHubAccountEmailChange = `-- name: AbandonReservedHubAccountEmailChange :one
WITH cancelled_reservation AS (
    UPDATE vetchium.hub_account_email_change_reservations AS reservation
    SET state = 'cancelled', updated_at = now()
    WHERE reservation.change_id = $1
      AND reservation.state = 'reserved'
    RETURNING reservation.change_id AS change_id,
        reservation.hub_user_did AS hub_user_did
), deleted_claim AS (
    DELETE FROM vetchium.hub_account_email_claims AS claim
    USING cancelled_reservation
    WHERE claim.change_id = cancelled_reservation.change_id
      AND claim.state = 'pending_change'
    RETURNING claim.email_digest AS email_digest
)
SELECT
    (SELECT change_id FROM cancelled_reservation) AS change_id,
    (SELECT email_digest FROM deleted_claim) AS email_digest
`

type AbandonReservedHubAccountEmailChangeRow struct {
	ChangeID    pgtype.UUID `json:"change_id"`
	EmailDigest []byte      `json:"email_digest"`
}

// Requires the caller to have already locked the reservation as 'reserved'.
func (q *Queries) AbandonReservedHubAccountEmailChange(ctx context.Context, changeID pgtype.UUID) (AbandonReservedHubAccountEmailChangeRow, error) {
	row := q.db.QueryRow(ctx, abandonReservedHubAccountEmailChange, changeID)
	var i AbandonReservedHubAccountEmailChangeRow
	err := row.Scan(&i.ChangeID, &i.EmailDigest)
	return i, err
}

const acknowledgeHubProfessionalEmailSupersessions = `-- name: AcknowledgeHubProfessionalEmailSupersessions :exec
UPDATE vetchium.hub_professional_email_feed_cursors
SET acknowledged_seq = $1
WHERE tenant_id = $2
`

type AcknowledgeHubProfessionalEmailSupersessionsParams struct {
	AcknowledgedSeq int64  `json:"acknowledged_seq"`
	TenantID        string `json:"tenant_id"`
}

func (q *Queries) AcknowledgeHubProfessionalEmailSupersessions(ctx context.Context, arg AcknowledgeHubProfessionalEmailSupersessionsParams) error {
	_, err := q.db.Exec(ctx, acknowledgeHubProfessionalEmailSupersessions, arg.AcknowledgedSeq, arg.TenantID)
	return err
}

const checkHubProfessionalEmailHoldings = `-- name: CheckHubProfessionalEmailHoldings :many
SELECT
    requested_did.hub_user_did::uuid AS hub_user_did,
    requested_digest.email_digest::bytea AS email_digest,
    claim.hub_user_did AS holder_hub_user_did,
    claim.claim_revision AS claim_revision
FROM unnest($1::uuid[]) WITH ORDINALITY
        AS requested_did (hub_user_did, ord)
INNER JOIN unnest($2::bytea[]) WITH ORDINALITY
        AS requested_digest (email_digest, ord)
    ON requested_digest.ord = requested_did.ord
LEFT JOIN vetchium.hub_professional_email_claims AS claim
    ON claim.email_digest = requested_digest.email_digest
`

type CheckHubProfessionalEmailHoldingsParams struct {
	HubUserDids  []pgtype.UUID `json:"hub_user_dids"`
	EmailDigests [][]byte      `json:"email_digests"`
}

type CheckHubProfessionalEmailHoldingsRow struct {
	HubUserDid       pgtype.UUID `json:"hub_user_did"`
	EmailDigest      []byte      `json:"email_digest"`
	HolderHubUserDid pgtype.UUID `json:"holder_hub_user_did"`
	ClaimRevision    pgtype.Int8 `json:"claim_revision"`
}

// claim.hub_user_did and claim.claim_revision are both null when no claim
// row exists at all; claim.hub_user_did alone is null when the row is
// released. The caller derives held_by_requested_user and treats
// claim_revision as absent unless claim.hub_user_did is non-null, since a
// released row still carries its last revision in this raw result
// (GU-DIR-011).
func (q *Queries) CheckHubProfessionalEmailHoldings(ctx context.Context, arg CheckHubProfessionalEmailHoldingsParams) ([]CheckHubProfessionalEmailHoldingsRow, error) {
	rows, err := q.db.Query(ctx, checkHubProfessionalEmailHoldings, arg.HubUserDids, arg.EmailDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckHubProfessionalEmailHoldingsRow
	for rows.Next() {
		var i CheckHubProfessionalEmailHoldingsRow
		if err := rows.Scan(
			&i.HubUserDid,
			&i.EmailDigest,
			&i.HolderHubUserDid,
			&i.ClaimRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countHubPrincipalsNotHomedAtTenant = `-- name: CountHubPrincipalsNotHomedAtTenant :one
SELECT count(*)
FROM unnest($1::uuid[]) AS requested (hub_user_did)
WHERE NOT EXISTS (
    SELECT 1 FROM vetchium.hub_principals AS principal
    WHERE principal.hub_user_did = requested.hub_user_did
      AND principal.home_tenant_id = $2
)
`

type CountHubPrincipalsNotHomedAtTenantParams struct {
	HubUserDids    []pgtype.UUID `json:"hub_user_dids"`
	CallerTenantID string        `json:"caller_tenant_id"`
}

// Rejects the whole batch (empty result absent, non-zero count present) when
// any requested DID is not homed at the caller, so the holdings check never
// answers about a DID it does not own (GU-DIR-011).
func (q *Queries) CountHubPrincipalsNotHomedAtTenant(ctx context.Context, arg CountHubPrincipalsNotHomedAtTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHubPrincipalsNotHomedAtTenant, arg.HubUserDids, arg.CallerTenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAcknowledgedHubProfessionalEmailSupersessions = `-- name: DeleteAcknowledgedHubProfessionalEmailSupersessions :execrows
DELETE FROM vetchium.hub_professional_email_supersessions
WHERE previous_home_tenant_id = $1
  AND supersession_seq <= $2
`

type DeleteAcknowledgedHubProfessionalEmailSupersessionsParams struct {
	TenantID        string `json:"tenant_id"`
	AcknowledgedSeq int64  `json:"acknowledged_seq"`
}

func (q *Queries) DeleteAcknowledgedHubProfessionalEmailSupersessions(ctx context.Context, arg DeleteAcknowledgedHubProfessionalEmailSupersessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAcknowledgedHubProfessionalEmailSupersessions, arg.TenantID, arg.AcknowledgedSeq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureHubProfessionalEmailFeedCursor = `-- name: EnsureHubProfessionalEmailFeedCursor :exec
INSERT INTO vetchium.hub_professional_email_feed_cursors (tenant_id)
VALUES ($1)
ON CONFLICT DO NOTHING
`

// The row lock is held until commit, so sequence N+1 cannot be issued, let
// alone become visible, until N has committed or rolled back (GU-GDB-003).
func (q *Queries) EnsureHubProfessionalEmailFeedCursor(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, ensureHubProfessionalEmailFeedCursor, tenantID)
	return err
}

const finalizeHubAccountEmailChange = `-- name: FinalizeHubAccountEmailChange :one
WITH released_active AS (
    DELETE FROM vetchium.hub_account_email_claims AS claim
    WHERE claim.hub_user_did = $2
      AND claim.state = 'active'
    RETURNING claim.hub_user_did
), promoted_claim AS (
    UPDATE vetchium.hub_account_email_claims AS claim
    SET state = 'active', change_id = NULL, updated_at = now()
    FROM (SELECT 1 AS marker) AS base
    LEFT JOIN released_active ON TRUE
    WHERE claim.change_id = $1
      AND claim.state = 'pending_change'
    RETURNING claim.hub_user_did, claim.email_digest
)
UPDATE vetchium.hub_account_email_change_reservations AS reservation
SET state = 'finalized', updated_at = now()
FROM promoted_claim
WHERE reservation.change_id = $1
RETURNING promoted_claim.hub_user_did, promoted_claim.email_digest
`

type FinalizeHubAccountEmailChangeParams struct {
	ChangeID   pgtype.UUID `json:"change_id"`
	HubUserDid pgtype.UUID `json:"hub_user_did"`
}

type FinalizeHubAccountEmailChangeRow struct {
	HubUserDid  pgtype.UUID `json:"hub_user_did"`
	EmailDigest []byte      `json:"email_digest"`
}

// Requires the caller to have already locked the reservation as 'reserved'.
// Deletes the user's current active claim (if any) before promoting the
// pending_change claim, so the one-current-claim index is never violated,
// and marks the reservation finalized in the same statement (GU-DIR-005).
func (q *Queries) FinalizeHubAccountEmailChange(ctx context.Context, arg FinalizeHubAccountEmailChangeParams) (FinalizeHubAccountEmailChangeRow, error) {
	row := q.db.QueryRow(ctx, finalizeHubAccountEmailChange, arg.ChangeID, arg.HubUserDid)
	var i FinalizeHubAccountEmailChangeRow
	err := row.Scan(&i.HubUserDid, &i.EmailDigest)
	return i, err
}

const insertAbandonedHubAccountEmailChangeTombstone = `-- name: InsertAbandonedHubAccountEmailChangeTombstone :exec
INSERT INTO vetchium.hub_account_email_change_reservations (
    change_id, hub_user_did, email_digest, state, not_after
) VALUES (
    $1, $2, NULL, 'cancelled',
    $3
)
`

type InsertAbandonedHubAccountEmailChangeTombstoneParams struct {
	ChangeID   pgtype.UUID        `json:"change_id"`
	HubUserDid pgtype.UUID        `json:"hub_user_did"`
	NotAfter   pgtype.Timestamptz `json:"not_after"`
}

// The change id alone fences a reserve that has not arrived yet: a later
// reserve for the same change id finds this tombstone and is rejected
// (GU-DIR-006).
func (q *Queries) InsertAbandonedHubAccountEmailChangeTombstone(ctx context.Context, arg InsertAbandonedHubAccountEmailChangeTombstoneParams) error {
	_, err := q.db.Exec(ctx, insertAbandonedHubAccountEmailChangeTombstone, arg.ChangeID, arg.HubUserDid, arg.NotAfter)
	return err
}

const insertHubProfessionalEmailClaimIfAbsent = `-- name: InsertHubProfessionalEmailClaimIfAbsent :one
INSERT INTO vetchium.hub_professional_email_claims (
    email_digest, hub_user_did, claim_revision, claimed_at
) VALUES (
    $1, $2, 1, now()
)
ON CONFLICT (email_digest) DO NOTHING
RETURNING claim_revision
`

type InsertHubProfessionalEmailClaimIfAbsentParams struct {
	EmailDigest []byte      `json:"email_digest"`
	HubUserDid  pgtype.UUID `json:"hub_user_did"`
}

// Safe under concurrency without a savepoint-based retry loop: a racing
// first claim of the same never-before-seen digest blocks here until the
// winner commits, then finds the row already present and takes the
// LockHubProfessionalEmailClaim + TransferHubProfessionalEmailClaim path.
func (q *Queries) InsertHubProfessionalEmailClaimIfAbsent(ctx context.Context, arg InsertHubProfessionalEmailClaimIfAbsentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertHubProfessionalEmailClaimIfAbsent, arg.EmailDigest, arg.HubUserDid)
	var claim_revision int64
	err := row.Scan(&claim_revision)
	return claim_revision, err
}

const insertHubProfessionalEmailSupersession = `-- name: InsertHubProfessionalEmailSupersession :exec
INSERT INTO vetchium.hub_professional_email_supersessions (
    previous_home_tenant_id, supersession_seq, email_digest,
    previous_hub_user_did, superseded_by_revision
) VALUES (
    $1, $2,
    $3, $4,
    $5
)
`

type InsertHubProfessionalEmailSupersessionParams struct {
	PreviousHomeTenantID string      `json:"previous_home_tenant_id"`
	SupersessionSeq      int64       `json:"supersession_seq"`
	EmailDigest          []byte      `json:"email_digest"`
	PreviousHubUserDid   pgtype.UUID `json:"previous_hub_user_did"`
	SupersededByRevision int64       `json:"superseded_by_revision"`
}

func (q *Queries) InsertHubProfessionalEmailSupersession(ctx context.Context, arg InsertHubProfessionalEmailSupersessionParams) error {
	_, err := q.db.Exec(ctx, insertHubProfessionalEmailSupersession,
		arg.PreviousHomeTenantID,
		arg.SupersessionSeq,
		arg.EmailDigest,
		arg.PreviousHubUserDid,
		arg.SupersededByRevision,
	)
	return err
}

const listPendingHubProfessionalEmailSupersessions = `-- name: ListPendingHubProfessionalEmailSupersessions :many
SELECT supersession_seq, email_digest, previous_hub_user_did,
    superseded_by_revision, created_at
FROM vetchium.hub_professional_email_supersessions
WHERE previous_home_tenant_id = $1
  AND supersession_seq > $2
ORDER BY supersession_seq
LIMIT $3
`

type ListPendingHubProfessionalEmailSupersessionsParams struct {
	TenantID        string `json:"tenant_id"`
	AcknowledgedSeq int64  `json:"acknowledged_seq"`
	RowLimit        int32  `json:"row_limit"`
}

type ListPendingHubProfessionalEmailSupersessionsRow struct {
	SupersessionSeq      int64              `json:"supersession_seq"`
	EmailDigest          []byte             `json:"email_digest"`
	PreviousHubUserDid   pgtype.UUID        `json:"previous_hub_user_did"`
	SupersededByRevision int64              `json:"superseded_by_revision"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingHubProfessionalEmailSupersessions(ctx context.Context, arg ListPendingHubProfessionalEmailSupersessionsParams) ([]ListPendingHubProfessionalEmailSupersessionsRow, error) {
	rows, err := q.db.Query(ctx, listPendingHubProfessionalEmailSupersessions, arg.TenantID, arg.AcknowledgedSeq, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingHubProfessionalEmailSupersessionsRow
	for rows.Next() {
		var i ListPendingHubProfessionalEmailSupersessionsRow
		if err := rows.Scan(
			&i.SupersessionSeq,
			&i.EmailDigest,
			&i.PreviousHubUserDid,
			&i.SupersededByRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHubAccountEmailChangeReservation = `-- name: LockHubAccountEmailChangeReservation :one
SELECT change_id, hub_user_did, email_digest, state, not_after
FROM vetchium.hub_account_email_change_reservations
WHERE change_id = $1
FOR UPDATE
`

type LockHubAccountEmailChangeReservationRow struct {
	ChangeID    pgtype.UUID                               `json:"change_id"`
	HubUserDid  pgtype.UUID                               `json:"hub_user_did"`
	EmailDigest []byte                                    `json:"email_digest"`
	State       VetchiumGlobalEmailChangeReservationState `json:"state"`
	NotAfter    pgtype.Timestamptz                        `json:"not_after"`
}

func (q *Queries) LockHubAccountEmailChangeReservation(ctx context.Context, changeID pgtype.UUID) (LockHubAccountEmailChangeReservationRow, error) {
	row := q.db.QueryRow(ctx, lockHubAccountEmailChangeReservation, changeID)
	var i LockHubAccountEmailChangeReservationRow
	err := row.Scan(
		&i.ChangeID,
		&i.HubUserDid,
		&i.EmailDigest,
		&i.State,
		&i.NotAfter,
	)
	return i, err
}

const lockHubProfessionalEmailClaim = `-- name: LockHubProfessionalEmailClaim :one
SELECT claim.hub_user_did, claim.claim_revision, principal.home_tenant_id
FROM vetchium.hub_professional_email_claims AS claim
LEFT JOIN vetchium.hub_principals AS principal
    ON principal.hub_user_did = claim.hub_user_did
WHERE claim.email_digest = $1
FOR UPDATE OF claim
`

type LockHubProfessionalEmailClaimRow struct {
	HubUserDid    pgtype.UUID `json:"hub_user_did"`
	ClaimRevision int64       `json:"claim_revision"`
	HomeTenantID  pgtype.Text `json:"home_tenant_id"`
}

// Absent: the row does not exist yet, so nothing to lock; the caller inserts
// it directly (InsertHubProfessionalEmailClaimIfAbsent). Otherwise, the
// caller locks the existing row with this query and then always applies
// TransferHubProfessionalEmailClaim, whether the previous holder was this
// same user, another user, or nobody (released) -- newest proof always wins
// and always bumps the revision (GU-DIR-007).
func (q *Queries) LockHubProfessionalEmailClaim(ctx context.Context, emailDigest []byte) (LockHubProfessionalEmailClaimRow, error) {
	row := q.db.QueryRow(ctx, lockHubProfessionalEmailClaim, emailDigest)
	var i LockHubProfessionalEmailClaimRow
	err := row.Scan(&i.HubUserDid, &i.ClaimRevision, &i.HomeTenantID)
	return i, err
}

const lockHubProfessionalEmailFeedCursor = `-- name: LockHubProfessionalEmailFeedCursor :one
INSERT INTO vetchium.hub_professional_email_feed_cursors (tenant_id)
VALUES ($1)
ON CONFLICT (tenant_id) DO UPDATE SET tenant_id = EXCLUDED.tenant_id
RETURNING tenant_id, last_issued_seq, acknowledged_seq
`

func (q *Queries) LockHubProfessionalEmailFeedCursor(ctx context.Context, tenantID string) (VetchiumHubProfessionalEmailFeedCursor, error) {
	row := q.db.QueryRow(ctx, lockHubProfessionalEmailFeedCursor, tenantID)
	var i VetchiumHubProfessionalEmailFeedCursor
	err := row.Scan(&i.TenantID, &i.LastIssuedSeq, &i.AcknowledgedSeq)
	return i, err
}

const nextHubProfessionalEmailSupersessionSeq = `-- name: NextHubProfessionalEmailSupersessionSeq :one
UPDATE vetchium.hub_professional_email_feed_cursors
SET last_issued_seq = last_issued_seq + 1
WHERE tenant_id = $1
RETURNING last_issued_seq
`

func (q *Queries) NextHubProfessionalEmailSupersessionSeq(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextHubProfessionalEmailSupersessionSeq, tenantID)
	var last_issued_seq int64
	err := row.Scan(&last_issued_seq)
	return last_issued_seq, err
}

const oldestPendingHubProfessionalEmailSupersession = `-- name: OldestPendingHubProfessionalEmailSupersession :one
SELECT min(created_at)::timestamptz AS oldest_pending_created_at
FROM vetchium.hub_professional_email_supersessions
WHERE previous_home_tenant_id = $1
`

func (q *Queries) OldestPendingHubProfessionalEmailSupersession(ctx context.Context, tenantID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestPendingHubProfessionalEmailSupersession, tenantID)
	var oldest_pending_created_at pgtype.Timestamptz
	err := row.Scan(&oldest_pending_created_at)
	return oldest_pending_created_at, err
}

const pruneTerminalHubAccountEmailChangeReservations = `-- name: PruneTerminalHubAccountEmailChangeReservations :execrows
DELETE FROM vetchium.hub_account_email_change_reservations
WHERE state IN ('cancelled', 'finalized')
  AND not_after < $1
`

func (q *Queries) PruneTerminalHubAccountEmailChangeReservations(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneTerminalHubAccountEmailChangeReservations, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseHubProfessionalEmailClaim = `-- name: ReleaseHubProfessionalEmailClaim :execrows
UPDATE vetchium.hub_professional_email_claims
SET hub_user_did = NULL
WHERE email_digest = $1
  AND hub_user_did = $2
  AND claim_revision = $3
`

type ReleaseHubProfessionalEmailClaimParams struct {
	EmailDigest   []byte      `json:"email_digest"`
	HubUserDid    pgtype.UUID `json:"hub_user_did"`
	ClaimRevision int64       `json:"claim_revision"`
}

// A stale revision, or a digest already released by someone else's newer
// proof, is a safe no-op (GU-DIR-008).
func (q *Queries) ReleaseHubProfessionalEmailClaim(ctx context.Context, arg ReleaseHubProfessionalEmailClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseHubProfessionalEmailClaim, arg.EmailDigest, arg.HubUserDid, arg.ClaimRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveHubAccountEmailChange = `-- name: ReserveHubAccountEmailChange :one
WITH stale_reservation AS (
    UPDATE vetchium.hub_account_email_change_reservations AS reservation
    SET state = 'cancelled', updated_at = now()
    WHERE reservation.hub_user_did = $1
      AND reservation.state = 'reserved'
      AND reservation.change_id <> $2
    RETURNING reservation.change_id
), stale_claim AS (
    DELETE FROM vetchium.hub_account_email_claims AS claim
    USING stale_reservation
    WHERE claim.hub_user_did = $1
      AND claim.state = 'pending_change'
      AND claim.change_id = stale_reservation.change_id
    RETURNING claim.email_digest
), inserted_reservation AS (
    INSERT INTO vetchium.hub_account_email_change_reservations (
        change_id, hub_user_did, email_digest, state, not_after
    )
    SELECT $2, $1,
        $3, 'reserved', $4
    RETURNING change_id
), inserted_claim AS (
    INSERT INTO vetchium.hub_account_email_claims (
        email_digest, hub_user_did, state, command_id, change_id
    )
    SELECT $3, $1, 'pending_change',
        $5, inserted_reservation.change_id
    FROM inserted_reservation
    -- Forces stale_claim to run first, freeing this user's one
    -- pending_change slot before this insert claims it.
    LEFT JOIN stale_claim ON TRUE
    RETURNING email_digest
)
SELECT
    (SELECT change_id FROM inserted_reservation) AS change_id,
    (SELECT count(*) FROM inserted_claim) AS inserted_claim_count
`

type ReserveHubAccountEmailChangeParams struct {
	HubUserDid  pgtype.UUID        `json:"hub_user_did"`
	ChangeID    pgtype.UUID        `json:"change_id"`
	EmailDigest []byte             `json:"email_digest"`
	NotAfter    pgtype.Timestamptz `json:"not_after"`
	CommandID   pgtype.UUID        `json:"command_id"`
}

type ReserveHubAccountEmailChangeRow struct {
	ChangeID           pgtype.UUID `json:"change_id"`
	InsertedClaimCount int64       `json:"inserted_claim_count"`
}

// Cancels any other reservation this user still has open and deletes its
// pending_change claim before inserting the new one, so the partial unique
// index on one pending_change claim per user is never violated (GU-DIR-004).
// The caller has already locked (or confirmed absent) the row for change_id.
func (q *Queries) ReserveHubAccountEmailChange(ctx context.Context, arg ReserveHubAccountEmailChangeParams) (ReserveHubAccountEmailChangeRow, error) {
	row := q.db.QueryRow(ctx, reserveHubAccountEmailChange,
		arg.HubUserDid,
		arg.ChangeID,
		arg.EmailDigest,
		arg.NotAfter,
		arg.CommandID,
	)
	var i ReserveHubAccountEmailChangeRow
	err := row.Scan(&i.ChangeID, &i.InsertedClaimCount)
	return i, err
}

const resolveHubAccountEmail = `-- name: ResolveHubAccountEmail :one
SELECT claim.hub_user_did, principal.home_tenant_id
FROM vetchium.hub_account_email_claims AS claim
INNER JOIN vetchium.hub_principals AS principal
    ON principal.hub_user_did = claim.hub_user_did
WHERE claim.email_digest = $1
  AND claim.state IN ('provisioning', 'active')
`

type ResolveHubAccountEmailRow struct {
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
	HomeTenantID string      `json:"home_tenant_id"`
}

func (q *Queries) ResolveHubAccountEmail(ctx context.Context, emailDigest []byte) (ResolveHubAccountEmailRow, error) {
	row := q.db.QueryRow(ctx, resolveHubAccountEmail, emailDigest)
	var i ResolveHubAccountEmailRow
	err := row.Scan(&i.HubUserDid, &i.HomeTenantID)
	return i, err
}

const transferHubProfessionalEmailClaim = `-- name: TransferHubProfessionalEmailClaim :one
UPDATE vetchium.hub_professional_email_claims
SET hub_user_did = $1,
    claim_revision = claim_revision + 1,
    claimed_at = now()
WHERE email_digest = $2
RETURNING claim_revision
`

type TransferHubProfessionalEmailClaimParams struct {
	HubUserDid  pgtype.UUID `json:"hub_user_did"`
	EmailDigest []byte      `json:"email_digest"`
}

// The caller must already hold the row lock from LockHubProfessionalEmailClaim
// in this transaction.
func (q *Queries) TransferHubProfessionalEmailClaim(ctx context.Context, arg TransferHubProfessionalEmailClaimParams) (int64, error) {
	row := q.db.QueryRow(ctx, transferHubProfessionalEmailClaim, arg.HubUserDid, arg.EmailDigest)
	var claim_revision int64
	err := row.Scan(&claim_revision)
	return claim_revision, err
}
