// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hub_email_directory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonReservedHubAccountEmailChange = `-- name: AbandonReservedHubAccountEmailChange :one
WITH cancelled_reservation AS (
    UPDATE vetchium.hub_account_email_change_reservations AS reservation
    SET state = 'cancelled', updated_at = now()
    WHERE reservation.change_id = $1
      AND reservation.state = 'reserved'
    RETURNING reservation.change_id AS change_id,
        reservation.hub_user_did AS hub_user_did
), deleted_claim AS (
    DELETE FROM vetchium.hub_account_email_claims AS claim
    USING cancelled_reservation
    WHERE claim.change_id = cancelled_reservation.change_id
      AND claim.state = 'pending_change'
    RETURNING claim.email_digest AS email_digest
)
SELECT
    (SELECT change_id FROM cancelled_reservation) AS change_id,
    (SELECT email_digest FROM deleted_claim) AS email_digest
`

type AbandonReservedHubAccountEmailChangeRow struct {
	ChangeID    pgtype.UUID `json:"change_id"`
	EmailDigest []byte      `json:"email_digest"`
}

// Requires the caller to have already locked the reservation as 'reserved'.
func (q *Queries) AbandonReservedHubAccountEmailChange(ctx context.Context, changeID pgtype.UUID) (AbandonReservedHubAccountEmailChangeRow, error) {
	row := q.db.QueryRow(ctx, abandonReservedHubAccountEmailChange, changeID)
	var i AbandonReservedHubAccountEmailChangeRow
	err := row.Scan(&i.ChangeID, &i.EmailDigest)
	return i, err
}

const finalizeHubAccountEmailChange = `-- name: FinalizeHubAccountEmailChange :one
WITH released_active AS (
    DELETE FROM vetchium.hub_account_email_claims AS claim
    WHERE claim.hub_user_did = $2
      AND claim.state = 'active'
    RETURNING claim.hub_user_did
), promoted_claim AS (
    UPDATE vetchium.hub_account_email_claims AS claim
    SET state = 'active', change_id = NULL, updated_at = now()
    FROM (SELECT 1 AS marker) AS base
    LEFT JOIN released_active ON TRUE
    WHERE claim.change_id = $1
      AND claim.state = 'pending_change'
    RETURNING claim.hub_user_did, claim.email_digest
)
UPDATE vetchium.hub_account_email_change_reservations AS reservation
SET state = 'finalized', updated_at = now()
FROM promoted_claim
WHERE reservation.change_id = $1
RETURNING promoted_claim.hub_user_did, promoted_claim.email_digest
`

type FinalizeHubAccountEmailChangeParams struct {
	ChangeID   pgtype.UUID `json:"change_id"`
	HubUserDid pgtype.UUID `json:"hub_user_did"`
}

type FinalizeHubAccountEmailChangeRow struct {
	HubUserDid  pgtype.UUID `json:"hub_user_did"`
	EmailDigest []byte      `json:"email_digest"`
}

// Requires the caller to have already locked the reservation as 'reserved'.
// Deletes the user's current active claim (if any) before promoting the
// pending_change claim, so the one-current-claim index is never violated,
// and marks the reservation finalized in the same statement (GU-DIR-005).
func (q *Queries) FinalizeHubAccountEmailChange(ctx context.Context, arg FinalizeHubAccountEmailChangeParams) (FinalizeHubAccountEmailChangeRow, error) {
	row := q.db.QueryRow(ctx, finalizeHubAccountEmailChange, arg.ChangeID, arg.HubUserDid)
	var i FinalizeHubAccountEmailChangeRow
	err := row.Scan(&i.HubUserDid, &i.EmailDigest)
	return i, err
}

const insertAbandonedHubAccountEmailChangeTombstone = `-- name: InsertAbandonedHubAccountEmailChangeTombstone :exec
INSERT INTO vetchium.hub_account_email_change_reservations (
    change_id, hub_user_did, email_digest, state, not_after
) VALUES (
    $1, $2, NULL, 'cancelled',
    $3
)
`

type InsertAbandonedHubAccountEmailChangeTombstoneParams struct {
	ChangeID   pgtype.UUID        `json:"change_id"`
	HubUserDid pgtype.UUID        `json:"hub_user_did"`
	NotAfter   pgtype.Timestamptz `json:"not_after"`
}

// The change id alone fences a reserve that has not arrived yet: a later
// reserve for the same change id finds this tombstone and is rejected
// (GU-DIR-006).
func (q *Queries) InsertAbandonedHubAccountEmailChangeTombstone(ctx context.Context, arg InsertAbandonedHubAccountEmailChangeTombstoneParams) error {
	_, err := q.db.Exec(ctx, insertAbandonedHubAccountEmailChangeTombstone, arg.ChangeID, arg.HubUserDid, arg.NotAfter)
	return err
}

const lockHubAccountEmailChangeReservation = `-- name: LockHubAccountEmailChangeReservation :one
SELECT change_id, hub_user_did, email_digest, state, not_after
FROM vetchium.hub_account_email_change_reservations
WHERE change_id = $1
FOR UPDATE
`

type LockHubAccountEmailChangeReservationRow struct {
	ChangeID    pgtype.UUID                               `json:"change_id"`
	HubUserDid  pgtype.UUID                               `json:"hub_user_did"`
	EmailDigest []byte                                    `json:"email_digest"`
	State       VetchiumGlobalEmailChangeReservationState `json:"state"`
	NotAfter    pgtype.Timestamptz                        `json:"not_after"`
}

func (q *Queries) LockHubAccountEmailChangeReservation(ctx context.Context, changeID pgtype.UUID) (LockHubAccountEmailChangeReservationRow, error) {
	row := q.db.QueryRow(ctx, lockHubAccountEmailChangeReservation, changeID)
	var i LockHubAccountEmailChangeReservationRow
	err := row.Scan(
		&i.ChangeID,
		&i.HubUserDid,
		&i.EmailDigest,
		&i.State,
		&i.NotAfter,
	)
	return i, err
}

const pruneTerminalHubAccountEmailChangeReservations = `-- name: PruneTerminalHubAccountEmailChangeReservations :execrows
DELETE FROM vetchium.hub_account_email_change_reservations
WHERE state IN ('cancelled', 'finalized')
  AND not_after < $1
`

func (q *Queries) PruneTerminalHubAccountEmailChangeReservations(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneTerminalHubAccountEmailChangeReservations, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveHubAccountEmailChange = `-- name: ReserveHubAccountEmailChange :one
WITH stale_reservation AS (
    UPDATE vetchium.hub_account_email_change_reservations AS reservation
    SET state = 'cancelled', updated_at = now()
    WHERE reservation.hub_user_did = $1
      AND reservation.state = 'reserved'
      AND reservation.change_id <> $2
    RETURNING reservation.change_id
), stale_claim AS (
    DELETE FROM vetchium.hub_account_email_claims AS claim
    USING stale_reservation
    WHERE claim.hub_user_did = $1
      AND claim.state = 'pending_change'
      AND claim.change_id = stale_reservation.change_id
    RETURNING claim.email_digest
), inserted_reservation AS (
    INSERT INTO vetchium.hub_account_email_change_reservations (
        change_id, hub_user_did, email_digest, state, not_after
    )
    SELECT $2, $1,
        $3, 'reserved', $4
    RETURNING change_id
), inserted_claim AS (
    INSERT INTO vetchium.hub_account_email_claims (
        email_digest, hub_user_did, state, command_id, change_id
    )
    SELECT $3, $1, 'pending_change',
        $5, inserted_reservation.change_id
    FROM inserted_reservation
    -- Forces stale_claim to run first, freeing this user's one
    -- pending_change slot before this insert claims it.
    LEFT JOIN stale_claim ON TRUE
    RETURNING email_digest
)
SELECT
    (SELECT change_id FROM inserted_reservation) AS change_id,
    (SELECT count(*) FROM inserted_claim) AS inserted_claim_count
`

type ReserveHubAccountEmailChangeParams struct {
	HubUserDid  pgtype.UUID        `json:"hub_user_did"`
	ChangeID    pgtype.UUID        `json:"change_id"`
	EmailDigest []byte             `json:"email_digest"`
	NotAfter    pgtype.Timestamptz `json:"not_after"`
	CommandID   pgtype.UUID        `json:"command_id"`
}

type ReserveHubAccountEmailChangeRow struct {
	ChangeID           pgtype.UUID `json:"change_id"`
	InsertedClaimCount int64       `json:"inserted_claim_count"`
}

// Cancels any other reservation this user still has open and deletes its
// pending_change claim before inserting the new one, so the partial unique
// index on one pending_change claim per user is never violated (GU-DIR-004).
// The caller has already locked (or confirmed absent) the row for change_id.
func (q *Queries) ReserveHubAccountEmailChange(ctx context.Context, arg ReserveHubAccountEmailChangeParams) (ReserveHubAccountEmailChangeRow, error) {
	row := q.db.QueryRow(ctx, reserveHubAccountEmailChange,
		arg.HubUserDid,
		arg.ChangeID,
		arg.EmailDigest,
		arg.NotAfter,
		arg.CommandID,
	)
	var i ReserveHubAccountEmailChangeRow
	err := row.Scan(&i.ChangeID, &i.InsertedClaimCount)
	return i, err
}

const resolveHubAccountEmail = `-- name: ResolveHubAccountEmail :one
SELECT claim.hub_user_did, principal.home_tenant_id
FROM vetchium.hub_account_email_claims AS claim
INNER JOIN vetchium.hub_principals AS principal
    ON principal.hub_user_did = claim.hub_user_did
WHERE claim.email_digest = $1
  AND claim.state IN ('provisioning', 'active')
`

type ResolveHubAccountEmailRow struct {
	HubUserDid   pgtype.UUID `json:"hub_user_did"`
	HomeTenantID string      `json:"home_tenant_id"`
}

func (q *Queries) ResolveHubAccountEmail(ctx context.Context, emailDigest []byte) (ResolveHubAccountEmailRow, error) {
	row := q.db.QueryRow(ctx, resolveHubAccountEmail, emailDigest)
	var i ResolveHubAccountEmailRow
	err := row.Scan(&i.HubUserDid, &i.HomeTenantID)
	return i, err
}
