// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_directory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateOrgPrincipal = `-- name: ActivateOrgPrincipal :one
UPDATE vetchium.org_principals
SET state = 'active', provisioning_expires_at = NULL,
    activated_at = now(), updated_at = now(),
    directory_version = directory_version + 1
WHERE org_did = $1
  AND home_tenant_id = $2
  AND state = 'provisioning'
  AND provisioning_expires_at > now()
RETURNING org_did, directory_version
`

type ActivateOrgPrincipalParams struct {
	OrgDid         pgtype.UUID `json:"org_did"`
	CallerTenantID string      `json:"caller_tenant_id"`
}

type ActivateOrgPrincipalRow struct {
	OrgDid           pgtype.UUID `json:"org_did"`
	DirectoryVersion int64       `json:"directory_version"`
}

func (q *Queries) ActivateOrgPrincipal(ctx context.Context, arg ActivateOrgPrincipalParams) (ActivateOrgPrincipalRow, error) {
	row := q.db.QueryRow(ctx, activateOrgPrincipal, arg.OrgDid, arg.CallerTenantID)
	var i ActivateOrgPrincipalRow
	err := row.Scan(&i.OrgDid, &i.DirectoryVersion)
	return i, err
}

const deleteOrgDomain = `-- name: DeleteOrgDomain :execrows
DELETE FROM vetchium.org_domains
WHERE org_did = $1
  AND domain = $2
`

type DeleteOrgDomainParams struct {
	OrgDid pgtype.UUID `json:"org_did"`
	Domain string      `json:"domain"`
}

func (q *Queries) DeleteOrgDomain(ctx context.Context, arg DeleteOrgDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrgDomain, arg.OrgDid, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrgPrincipal = `-- name: GetOrgPrincipal :one
SELECT org_did, home_tenant_id, state
FROM vetchium.org_principals
WHERE org_did = $1
`

type GetOrgPrincipalRow struct {
	OrgDid       pgtype.UUID                  `json:"org_did"`
	HomeTenantID string                       `json:"home_tenant_id"`
	State        VetchiumGlobalPrincipalState `json:"state"`
}

func (q *Queries) GetOrgPrincipal(ctx context.Context, orgDid pgtype.UUID) (GetOrgPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getOrgPrincipal, orgDid)
	var i GetOrgPrincipalRow
	err := row.Scan(&i.OrgDid, &i.HomeTenantID, &i.State)
	return i, err
}

const getOrgPrincipalCommandView = `-- name: GetOrgPrincipalCommandView :one
SELECT
    p.org_did,
    d.domain,
    p.home_tenant_id,
    p.routing_version,
    p.state
FROM vetchium.org_principals AS p
LEFT JOIN vetchium.org_domains AS d
    ON d.org_did = p.org_did
WHERE p.org_did = $1
`

type GetOrgPrincipalCommandViewRow struct {
	OrgDid         pgtype.UUID                  `json:"org_did"`
	Domain         pgtype.Text                  `json:"domain"`
	HomeTenantID   string                       `json:"home_tenant_id"`
	RoutingVersion int64                        `json:"routing_version"`
	State          VetchiumGlobalPrincipalState `json:"state"`
}

func (q *Queries) GetOrgPrincipalCommandView(ctx context.Context, orgDid pgtype.UUID) (GetOrgPrincipalCommandViewRow, error) {
	row := q.db.QueryRow(ctx, getOrgPrincipalCommandView, orgDid)
	var i GetOrgPrincipalCommandViewRow
	err := row.Scan(
		&i.OrgDid,
		&i.Domain,
		&i.HomeTenantID,
		&i.RoutingVersion,
		&i.State,
	)
	return i, err
}

const insertOrgDomain = `-- name: InsertOrgDomain :exec
INSERT INTO vetchium.org_domains (domain, org_did)
VALUES ($1, $2)
`

type InsertOrgDomainParams struct {
	Domain string      `json:"domain"`
	OrgDid pgtype.UUID `json:"org_did"`
}

func (q *Queries) InsertOrgDomain(ctx context.Context, arg InsertOrgDomainParams) error {
	_, err := q.db.Exec(ctx, insertOrgDomain, arg.Domain, arg.OrgDid)
	return err
}

const lockOrgPrincipal = `-- name: LockOrgPrincipal :one
SELECT
    p.org_did,
    p.home_tenant_id,
    p.state,
    d.domain
FROM vetchium.org_principals AS p
LEFT JOIN vetchium.org_domains AS d
    ON d.org_did = p.org_did
WHERE p.org_did = $1
FOR UPDATE OF p
`

type LockOrgPrincipalRow struct {
	OrgDid       pgtype.UUID                  `json:"org_did"`
	HomeTenantID string                       `json:"home_tenant_id"`
	State        VetchiumGlobalPrincipalState `json:"state"`
	Domain       pgtype.Text                  `json:"domain"`
}

func (q *Queries) LockOrgPrincipal(ctx context.Context, orgDid pgtype.UUID) (LockOrgPrincipalRow, error) {
	row := q.db.QueryRow(ctx, lockOrgPrincipal, orgDid)
	var i LockOrgPrincipalRow
	err := row.Scan(
		&i.OrgDid,
		&i.HomeTenantID,
		&i.State,
		&i.Domain,
	)
	return i, err
}

const reapExpiredOrgPrincipalReservations = `-- name: ReapExpiredOrgPrincipalReservations :execrows
WITH candidates AS MATERIALIZED (
    SELECT org_did
    FROM vetchium.org_principals
    WHERE state = 'provisioning'
      AND provisioning_expires_at <= now()
    ORDER BY provisioning_expires_at
    FOR UPDATE SKIP LOCKED
    LIMIT 100
), deleted_domains AS (
    DELETE FROM vetchium.org_domains AS domain
    USING candidates
    WHERE domain.org_did = candidates.org_did
    RETURNING domain.org_did
)
DELETE FROM vetchium.org_principals AS principal
USING candidates
WHERE principal.org_did = candidates.org_did
  AND EXISTS (
      SELECT 1 FROM deleted_domains
      WHERE deleted_domains.org_did = principal.org_did
  )
`

func (q *Queries) ReapExpiredOrgPrincipalReservations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredOrgPrincipalReservations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordOrgDomainChange = `-- name: RecordOrgDomainChange :one
UPDATE vetchium.org_principals
SET directory_version = directory_version + 1,
    updated_at = now()
WHERE org_did = $1
RETURNING directory_version
`

func (q *Queries) RecordOrgDomainChange(ctx context.Context, orgDid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, recordOrgDomainChange, orgDid)
	var directory_version int64
	err := row.Scan(&directory_version)
	return directory_version, err
}

const reserveOrgPrincipal = `-- name: ReserveOrgPrincipal :one
WITH principal AS (
    INSERT INTO vetchium.org_principals (
        org_did, home_tenant_id, state, provisioning_operation_id,
        provisioning_expires_at
    ) VALUES (
        $1, $2, 'provisioning',
        $3, $4
    )
    RETURNING org_did, home_tenant_id, routing_version, directory_version,
        state
), claimed AS (
    INSERT INTO vetchium.org_domains (domain, org_did)
    SELECT $5, org_did FROM principal
    RETURNING domain
)
SELECT
    p.org_did, c.domain, p.home_tenant_id, p.routing_version,
    p.directory_version, p.state
FROM principal AS p
CROSS JOIN claimed AS c
`

type ReserveOrgPrincipalParams struct {
	OrgDid                pgtype.UUID        `json:"org_did"`
	HomeTenantID          string             `json:"home_tenant_id"`
	CommandID             pgtype.UUID        `json:"command_id"`
	ProvisioningExpiresAt pgtype.Timestamptz `json:"provisioning_expires_at"`
	Domain                string             `json:"domain"`
}

type ReserveOrgPrincipalRow struct {
	OrgDid           pgtype.UUID                  `json:"org_did"`
	Domain           string                       `json:"domain"`
	HomeTenantID     string                       `json:"home_tenant_id"`
	RoutingVersion   int64                        `json:"routing_version"`
	DirectoryVersion int64                        `json:"directory_version"`
	State            VetchiumGlobalPrincipalState `json:"state"`
}

func (q *Queries) ReserveOrgPrincipal(ctx context.Context, arg ReserveOrgPrincipalParams) (ReserveOrgPrincipalRow, error) {
	row := q.db.QueryRow(ctx, reserveOrgPrincipal,
		arg.OrgDid,
		arg.HomeTenantID,
		arg.CommandID,
		arg.ProvisioningExpiresAt,
		arg.Domain,
	)
	var i ReserveOrgPrincipalRow
	err := row.Scan(
		&i.OrgDid,
		&i.Domain,
		&i.HomeTenantID,
		&i.RoutingVersion,
		&i.DirectoryVersion,
		&i.State,
	)
	return i, err
}

const resolveOrgDomain = `-- name: ResolveOrgDomain :one
SELECT
    p.org_did,
    d.domain,
    p.home_tenant_id,
    p.routing_version
FROM vetchium.org_domains AS d
INNER JOIN vetchium.org_principals AS p
    ON p.org_did = d.org_did
WHERE d.domain = $1
  AND p.state = 'active'
`

type ResolveOrgDomainRow struct {
	OrgDid         pgtype.UUID `json:"org_did"`
	Domain         string      `json:"domain"`
	HomeTenantID   string      `json:"home_tenant_id"`
	RoutingVersion int64       `json:"routing_version"`
}

func (q *Queries) ResolveOrgDomain(ctx context.Context, domain string) (ResolveOrgDomainRow, error) {
	row := q.db.QueryRow(ctx, resolveOrgDomain, domain)
	var i ResolveOrgDomainRow
	err := row.Scan(
		&i.OrgDid,
		&i.Domain,
		&i.HomeTenantID,
		&i.RoutingVersion,
	)
	return i, err
}
