// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Requires the caller to have already locked the reservation as 'reserved'.
	AbandonReservedHubAccountEmailChange(ctx context.Context, changeID pgtype.UUID) (AbandonReservedHubAccountEmailChangeRow, error)
	AcknowledgeHubProfessionalEmailSupersessions(ctx context.Context, arg AcknowledgeHubProfessionalEmailSupersessionsParams) error
	AcquireCommandLock(ctx context.Context, commandID string) error
	// Activates the principal and, in the same statement, its provisioning
	// account email claim (GU-DIR-003). The claim update depends on
	// activated_principal via a real FROM reference, so the claim's transition
	// trigger sees the principal already active.
	ActivateHubPrincipal(ctx context.Context, arg ActivateHubPrincipalParams) (ActivateHubPrincipalRow, error)
	ActivateOrgPrincipal(ctx context.Context, arg ActivateOrgPrincipalParams) (ActivateOrgPrincipalRow, error)
	// claim.hub_user_did and claim.claim_revision are both null when no claim
	// row exists at all; claim.hub_user_did alone is null when the row is
	// released. The caller derives held_by_requested_user and treats
	// claim_revision as absent unless claim.hub_user_did is non-null, since a
	// released row still carries its last revision in this raw result
	// (GU-DIR-011).
	CheckHubProfessionalEmailHoldings(ctx context.Context, arg CheckHubProfessionalEmailHoldingsParams) ([]CheckHubProfessionalEmailHoldingsRow, error)
	// Rejects the whole batch (empty result absent, non-zero count present) when
	// any requested DID is not homed at the caller, so the holdings check never
	// answers about a DID it does not own (GU-DIR-011).
	CountHubPrincipalsNotHomedAtTenant(ctx context.Context, arg CountHubPrincipalsNotHomedAtTenantParams) (int64, error)
	DeleteAcknowledgedHubProfessionalEmailSupersessions(ctx context.Context, arg DeleteAcknowledgedHubProfessionalEmailSupersessionsParams) (int64, error)
	DeleteHubAlias(ctx context.Context, hubUserDid pgtype.UUID) error
	DeleteOrgDomain(ctx context.Context, arg DeleteOrgDomainParams) (int64, error)
	// The row lock is held until commit, so sequence N+1 cannot be issued, let
	// alone become visible, until N has committed or rolled back (GU-GDB-003).
	EnsureHubProfessionalEmailFeedCursor(ctx context.Context, tenantID string) error
	// Requires the caller to have already locked the reservation as 'reserved'.
	// Deletes the user's current active claim (if any) before promoting the
	// pending_change claim, so the one-current-claim index is never violated,
	// and marks the reservation finalized in the same statement (GU-DIR-005).
	FinalizeHubAccountEmailChange(ctx context.Context, arg FinalizeHubAccountEmailChangeParams) (FinalizeHubAccountEmailChangeRow, error)
	GetCommandResult(ctx context.Context, commandID pgtype.UUID) (VetchiumGlobalCommandLedger, error)
	GetOrgPrincipal(ctx context.Context, orgDid pgtype.UUID) (GetOrgPrincipalRow, error)
	GetOrgPrincipalCommandView(ctx context.Context, orgDid pgtype.UUID) (GetOrgPrincipalCommandViewRow, error)
	GetPrincipal(ctx context.Context, hubUserDid pgtype.UUID) (GetPrincipalRow, error)
	GetPrincipalCommandView(ctx context.Context, hubUserDid pgtype.UUID) (GetPrincipalCommandViewRow, error)
	// The change id alone fences a reserve that has not arrived yet: a later
	// reserve for the same change id finds this tombstone and is rejected
	// (GU-DIR-006).
	InsertAbandonedHubAccountEmailChangeTombstone(ctx context.Context, arg InsertAbandonedHubAccountEmailChangeTombstoneParams) error
	InsertCommandResult(ctx context.Context, arg InsertCommandResultParams) error
	InsertGlobalAuditEvent(ctx context.Context, arg InsertGlobalAuditEventParams) error
	InsertGlobalOutboxEvent(ctx context.Context, arg InsertGlobalOutboxEventParams) error
	InsertHubAlias(ctx context.Context, arg InsertHubAliasParams) error
	// Safe under concurrency without a savepoint-based retry loop: a racing
	// first claim of the same never-before-seen digest blocks here until the
	// winner commits, then finds the row already present and takes the
	// LockHubProfessionalEmailClaim + TransferHubProfessionalEmailClaim path.
	InsertHubProfessionalEmailClaimIfAbsent(ctx context.Context, arg InsertHubProfessionalEmailClaimIfAbsentParams) (int64, error)
	InsertHubProfessionalEmailSupersession(ctx context.Context, arg InsertHubProfessionalEmailSupersessionParams) error
	InsertOrgDomain(ctx context.Context, arg InsertOrgDomainParams) error
	ListPendingHubProfessionalEmailSupersessions(ctx context.Context, arg ListPendingHubProfessionalEmailSupersessionsParams) ([]ListPendingHubProfessionalEmailSupersessionsRow, error)
	LockHubAccountEmailChangeReservation(ctx context.Context, changeID pgtype.UUID) (LockHubAccountEmailChangeReservationRow, error)
	// Absent: the row does not exist yet, so nothing to lock; the caller inserts
	// it directly (InsertHubProfessionalEmailClaimIfAbsent). Otherwise, the
	// caller locks the existing row with this query and then always applies
	// TransferHubProfessionalEmailClaim, whether the previous holder was this
	// same user, another user, or nobody (released) -- newest proof always wins
	// and always bumps the revision (GU-DIR-007).
	LockHubProfessionalEmailClaim(ctx context.Context, emailDigest []byte) (LockHubProfessionalEmailClaimRow, error)
	LockHubProfessionalEmailFeedCursor(ctx context.Context, tenantID string) (VetchiumHubProfessionalEmailFeedCursor, error)
	LockOrgPrincipal(ctx context.Context, orgDid pgtype.UUID) (LockOrgPrincipalRow, error)
	LockPrincipalForAlias(ctx context.Context, hubUserDid pgtype.UUID) (LockPrincipalForAliasRow, error)
	NextHubProfessionalEmailSupersessionSeq(ctx context.Context, tenantID string) (int64, error)
	OldestPendingHubProfessionalEmailSupersession(ctx context.Context, tenantID string) (pgtype.Timestamptz, error)
	PruneTerminalHubAccountEmailChangeReservations(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	ReapExpiredHubPrincipalReservations(ctx context.Context) (int64, error)
	// The coordinator reaps a reservation its home tenant never activated. The
	// audit event names that tenant, whose signup the reservation belonged to.
	ReapExpiredOrgPrincipalReservations(ctx context.Context) (int64, error)
	RecordHubAliasChange(ctx context.Context, arg RecordHubAliasChangeParams) (int64, error)
	RecordOrgDomainChange(ctx context.Context, orgDid pgtype.UUID) (int64, error)
	// A stale revision, or a digest already released by someone else's newer
	// proof, is a safe no-op (GU-DIR-008).
	ReleaseHubProfessionalEmailClaim(ctx context.Context, arg ReleaseHubProfessionalEmailClaimParams) (int64, error)
	// Cancels any other reservation this user still has open and deletes its
	// pending_change claim before inserting the new one, so the partial unique
	// index on one pending_change claim per user is never violated (GU-DIR-004).
	// The caller has already locked (or confirmed absent) the row for change_id.
	ReserveHubAccountEmailChange(ctx context.Context, arg ReserveHubAccountEmailChangeParams) (ReserveHubAccountEmailChangeRow, error)
	// The claim is inserted before the handle, and its failure aborts the whole
	// statement before the handle insert even runs, so a digest already claimed
	// elsewhere never burns a handle-rotation attempt (GU-DIR-002).
	ReserveHubPrincipal(ctx context.Context, arg ReserveHubPrincipalParams) (ReserveHubPrincipalRow, error)
	ReserveOrgPrincipal(ctx context.Context, arg ReserveOrgPrincipalParams) (ReserveOrgPrincipalRow, error)
	ResolveHubAccountEmail(ctx context.Context, emailDigest []byte) (ResolveHubAccountEmailRow, error)
	ResolveOrgDomain(ctx context.Context, domain string) (ResolveOrgDomainRow, error)
	ResolveProfileSlug(ctx context.Context, slug string) (ResolveProfileSlugRow, error)
	// The caller must already hold the row lock from LockHubProfessionalEmailClaim
	// in this transaction.
	TransferHubProfessionalEmailClaim(ctx context.Context, arg TransferHubProfessionalEmailClaimParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
