// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireCommandLock(ctx context.Context, commandID string) error
	ActivateHubPrincipal(ctx context.Context, arg ActivateHubPrincipalParams) (ActivateHubPrincipalRow, error)
	DeleteHubAlias(ctx context.Context, hubUserDid pgtype.UUID) error
	GetCommandResult(ctx context.Context, commandID pgtype.UUID) (VetchiumGlobalCommandLedger, error)
	GetPrincipal(ctx context.Context, hubUserDid pgtype.UUID) (GetPrincipalRow, error)
	GetPrincipalCommandView(ctx context.Context, hubUserDid pgtype.UUID) (GetPrincipalCommandViewRow, error)
	InsertCommandResult(ctx context.Context, arg InsertCommandResultParams) error
	InsertGlobalAuditEvent(ctx context.Context, arg InsertGlobalAuditEventParams) error
	InsertGlobalOutboxEvent(ctx context.Context, arg InsertGlobalOutboxEventParams) error
	InsertHubAlias(ctx context.Context, arg InsertHubAliasParams) error
	LockPrincipalForAlias(ctx context.Context, hubUserDid pgtype.UUID) (LockPrincipalForAliasRow, error)
	ReapExpiredHubPrincipalReservations(ctx context.Context) (int64, error)
	RecordHubAliasChange(ctx context.Context, arg RecordHubAliasChangeParams) (int64, error)
	ReserveHubPrincipal(ctx context.Context, arg ReserveHubPrincipalParams) (ReserveHubPrincipalRow, error)
	ResolveProfileSlug(ctx context.Context, slug string) (ResolveProfileSlugRow, error)
}

var _ Querier = (*Queries)(nil)
