export interface Country {
	code: string; // ISO 3166-1 alpha-2
	name: string;
}

export const COUNTRIES: Country[] = [
	{ code: "AF", name: "Afghanistan" },
	{ code: "AL", name: "Albania" },
	{ code: "DZ", name: "Algeria" },
	{ code: "AR", name: "Argentina" },
	{ code: "AU", name: "Australia" },
	{ code: "AT", name: "Austria" },
	{ code: "BD", name: "Bangladesh" },
	{ code: "BE", name: "Belgium" },
	{ code: "BR", name: "Brazil" },
	{ code: "BG", name: "Bulgaria" },
	{ code: "CA", name: "Canada" },
	{ code: "CL", name: "Chile" },
	{ code: "CN", name: "China" },
	{ code: "CO", name: "Colombia" },
	{ code: "CR", name: "Costa Rica" },
	{ code: "HR", name: "Croatia" },
	{ code: "CZ", name: "Czech Republic" },
	{ code: "DK", name: "Denmark" },
	{ code: "EG", name: "Egypt" },
	{ code: "EE", name: "Estonia" },
	{ code: "FI", name: "Finland" },
	{ code: "FR", name: "France" },
	{ code: "DE", name: "Germany" },
	{ code: "GR", name: "Greece" },
	{ code: "HK", name: "Hong Kong" },
	{ code: "HU", name: "Hungary" },
	{ code: "IS", name: "Iceland" },
	{ code: "IN", name: "India" },
	{ code: "ID", name: "Indonesia" },
	{ code: "IE", name: "Ireland" },
	{ code: "IL", name: "Israel" },
	{ code: "IT", name: "Italy" },
	{ code: "JP", name: "Japan" },
	{ code: "KE", name: "Kenya" },
	{ code: "KR", name: "Korea, Republic of" },
	{ code: "LV", name: "Latvia" },
	{ code: "LT", name: "Lithuania" },
	{ code: "LU", name: "Luxembourg" },
	{ code: "MY", name: "Malaysia" },
	{ code: "MX", name: "Mexico" },
	{ code: "NL", name: "Netherlands" },
	{ code: "NZ", name: "New Zealand" },
	{ code: "NG", name: "Nigeria" },
	{ code: "NO", name: "Norway" },
	{ code: "PK", name: "Pakistan" },
	{ code: "PE", name: "Peru" },
	{ code: "PH", name: "Philippines" },
	{ code: "PL", name: "Poland" },
	{ code: "PT", name: "Portugal" },
	{ code: "RO", name: "Romania" },
	{ code: "RU", name: "Russian Federation" },
	{ code: "SA", name: "Saudi Arabia" },
	{ code: "RS", name: "Serbia" },
	{ code: "SG", name: "Singapore" },
	{ code: "SK", name: "Slovakia" },
	{ code: "SI", name: "Slovenia" },
	{ code: "ZA", name: "South Africa" },
	{ code: "ES", name: "Spain" },
	{ code: "LK", name: "Sri Lanka" },
	{ code: "SE", name: "Sweden" },
	{ code: "CH", name: "Switzerland" },
	{ code: "TW", name: "Taiwan" },
	{ code: "TH", name: "Thailand" },
	{ code: "TR", name: "Turkey" },
	{ code: "UA", name: "Ukraine" },
	{ code: "AE", name: "United Arab Emirates" },
	{ code: "GB", name: "United Kingdom" },
	{ code: "US", name: "United States" },
	{ code: "VN", name: "Vietnam" },
];
