package common

type SecurityEffect string

const (
	CreateLoginChallenge          SecurityEffect = "create-login-challenge"
	ConsumeLoginChallenge         SecurityEffect = "consume-login-challenge"
	InvalidateLoginChallenges     SecurityEffect = "invalidate-login-challenges"
	RefreshSessionAuthentication  SecurityEffect = "refresh-session-authentication"
	RejectTOTPReplay              SecurityEffect = "reject-totp-replay"
	CreateTOTPEnrollment          SecurityEffect = "create-totp-enrollment"
	ConsumeTOTPEnrollment         SecurityEffect = "consume-totp-enrollment"
	InvalidateTOTPEnrollments     SecurityEffect = "invalidate-totp-enrollments"
	EnableTOTP                    SecurityEffect = "enable-totp"
	DisableTOTP                   SecurityEffect = "disable-totp"
	GenerateRecoveryCodes         SecurityEffect = "generate-recovery-codes"
	ConsumeRecoveryCode           SecurityEffect = "consume-recovery-code"
	InvalidateRecoveryCodes       SecurityEffect = "invalidate-recovery-codes"
	RotatePassword                SecurityEffect = "rotate-password"
	CreatePasswordResetToken      SecurityEffect = "create-password-reset-token"
	InvalidatePasswordResetTokens SecurityEffect = "invalidate-password-reset-tokens"
	QueuePasswordResetEmail       SecurityEffect = "queue-password-reset-email"
	CreateAdminInvitation         SecurityEffect = "create-admin-invitation"
	ConsumeAdminInvitation        SecurityEffect = "consume-admin-invitation"
	QueueAdminInvitationEmail     SecurityEffect = "queue-admin-invitation-email"
	CreateAdminUser               SecurityEffect = "create-admin-user"
	CreateHubSignup               SecurityEffect = "create-hub-signup"
	ConsumeHubSignup              SecurityEffect = "consume-hub-signup"
	QueueHubSignupEmail           SecurityEffect = "queue-hub-signup-email"
	CreateHubUser                 SecurityEffect = "create-hub-user"
	RevokeOtherSessions           SecurityEffect = "revoke-other-sessions"
	RevokeAllSessions             SecurityEffect = "revoke-all-sessions"
	DisableAdminUser              SecurityEffect = "disable-admin-user"
	EnableAdminUser               SecurityEffect = "enable-admin-user"
	ReplaceAdminPermissions       SecurityEffect = "replace-admin-permissions"
)
